### ISSUE TITLE
Using CURVE

### ISSUE THREAD

**Issue by super-cache-money** [zeromq/zeromq.js#102]
How would I authenticate with CURVE?

**Comment by manikawnth** [comment]
Hi,
The zeromq rfc spec# 26 has excellent detail on the process.
Even if it takes a week to understand (at least for me it took) spend the time. It's worthy.
https://rfc.zeromq.org/spec:26/CURVEZMQ

If you want code to implement a authenticated + encrypted communication using Curve Zmq, there is an example in the test suite

https://github.com/zeromq/zeromq.js/blob/master/test/socket.zap.js

There are 3 mechanisms implemented. You can ignore null (no auth) and Plain (id, pwd) and just retain the code of Curve mechanism.
Hope this helps.

**Comment by vtellier** [comment]
Hi,

Is it possible to write a bit about encryptioon with NodeJS binding in documentation?
The examples from the test suite looks really nice, but it would be amazing to have an API description about encryption.

**Comment by vtellier** [comment]
Hi,

I tried to use CURVE with node.js, and I didn't understood how to explicitly install the package with libSodium or tweetNacl (not good enough with npm): _see my post on [stackoverflow](https://stackoverflow.com/questions/44238555/how-to-get-zeromq-binding-for-node-js-properly-installed-with-libsodium)_

However, after digging a bit deeper, i found out the TweetNacl library is by default activated for compilation on linux (currently zmq version 4.1.6)

I have at least to different behaviors on windows and linux for this simple trace:
```
var zmq = require('zeromq');

try {
  zmq.zmqCurveKeypair();
  console.log("Zmq CURVE is activated.");
} catch(e) {
  console.log(e);
  return;
}
```
On windows:

> Error: zmq_curve_keypair operation failed. Method support in libzmq v4+ -with-libsodium.

On Ubuntu 16:

> Zmq CURVE is activated.

My understanding is:
 * Under window, the installation will download prebuilt binaries which are probably not compiled with tweetNacl or libSodium.
 * On Linux, the installation will download the sources of the release 4.1.6 and compile it with the tweetNacl library enabled by default.

This discrepency between Linux and Windows sounds wrong to me:
 * I am using Node.Js __especially__ for multiplatform compatibility
 * And **mainly** to _"take advantage of the elegant simplicity of binaries."._

I am really satisfied by the binding of zmq, it matches perfectly with the two points above, until I needed encryption.
Therefor, I think this issue should be taken into account, so we can at least have :
 * Have a proper paragraph in the README.md to explain to newbies like me how to install the package with libSodium or tweetNacl
 * Fix the discrepency between windows and linux in the installatino scripts.

I also suggest the **Enhancement** and **Help wanted** labels for this issue :)

**Comment by rolftimmermans** [comment]
Prebuilds for all platforms should now include support for CURVE security. The best example is probably in https://github.com/zeromq/zeromq.js/blob/master/test/unit/socket-curve-send-receive-test.ts. If there are any problems feel free to open a new issue!
