### ISSUE TITLE
electron app cannot find zeromq module

### ISSUE THREAD

**Issue by bakkiraju** [zeromq/zeromq.js#118]
Electron version : 1.4.13

Description: zeromq works fine in node environment when I start electron app with "npm start"
But when I bundle the app using electron-packager it fails to find zeromq module

I have rebuilt zeromq as recommended in

https://github.com/zeromq/zeromq.js#rebuilding-for-electron

npm rebuild zeromq --runtime=electron --target=1.4.13

But when I bundle my electron app with below electron-packager command,

it complains that zeromq module couldn't be found

electron-packager . --overwrite  --platform=darwin --arch=x64 --prune=true

Any suggestions on how I can include zeromq module into my electron
app successfully.

Appreciate it

**Comment by bakkiraju** [comment]
![image](https://cloud.githubusercontent.com/assets/1934468/21871623/32960810-d818-11e6-9ce6-fb6a189f2fbd.png)

**Comment by lgeiger** [comment]
I've never used `electron-packager` before. In [`nteract`](https://github.com/nteract/nteract) we use [`electron-builder`](https://github.com/electron-userland/electron-builder) which handles the rebuilding and packaging of the application.

Do other dependencies work? Could you try omitting `--prune=true`?

**Comment by bakkiraju** [comment]
yes I tried 
  "node-fs" : "^0.1.7"


And in my entry point to electron app, I do this,

const fs = require('fs')
const zmq = require('zeromq')

And am able to build and package the app with electron-packager and I see that app is still only failing to reference zeromq. Will try electron-builder to package the app.

Note: --prune has no affect on the failure to launch behavior of the app

**Comment by bakkiraju** [comment]
My bad, 

I was including zeromq in devDependencies  instead of listing it in, 

Moving it to dependencies and using electron-packager works now.

"dependencies": {
    "electron": "^1.4.14",
    "zeromq" : "^4.1.1",
  }

 closing the issue.

**Comment by lgeiger** [comment]
That's great 🎉

**Comment by rgbkrk** [comment]
Hoorah!
