### ISSUE TITLE
"npm install" requires access to github.com

### ISSUE THREAD

**Issue by stanleyxu2005** [zeromq/zeromq.js#119]
Dear developers,

When I use `npm install` on Linux, the script attempts to fetch something from github.com. However in a corporation this might not be always possible. Could you revise the installation script, so that use `npm install` to do everything?
```
> zeromq@4.1.1 build:libzmq /path/to/proj/node_modules/zeromq
> node scripts/preinstall.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)

npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/path/to/node" "/path/to/npm" "run" "build:libzmq"

4198 error node v6.2.0
4199 error npm  v3.8.9
4200 error code ELIFECYCLE
4201 error zeromq@4.1.1 install: `prebuild-install || (npm run build:libzmq && node-gyp rebuild)`
4201 error Exit status 1
4202 error Failed at the zeromq@4.1.1 install script 'prebuild-install || (npm run build:libzmq && node-gyp rebuild)'.
4202 error Make sure you have the latest version of node.js and npm installed.
4202 error If you do, this is most likely a problem with the zeromq package,
4202 error not with npm itself.
4202 error Tell the author that this fails on your system:
4202 error     prebuild-install || (npm run build:libzmq && node-gyp rebuild)
4202 error You can get information on how to open an issue for this project with:
4202 error     npm bugs zeromq
4202 error Or if that isn't available, you can get their info via:
4202 error     npm owner ls zeromq
4202 error There is likely additional logging output above.
4203 verbose exit [ 1, true ]
```

**Comment by rgbkrk** [comment]
Hi again @stanleyxu2005. If you recall from our previous conversations, the reason it reaches out to GitHub is to get the prebuilds which allow ease of installation on macOS, Linux, and even Windows. You can download the prebuilds yourself onto your own corporate network and then use those. Prebuild does support a cached directory you could download these into. Handling mirrors of the prebuilds is not something I'll actively work on, so it's up to you to support it.
 
The alternative to that is to go back to basics and [build from source](https://github.com/zeromq/zeromq.js#installation---from-source). Building from source will also require getting access to libzmq though so you're in for a different set of workarounds for a restrictive work environment.

**Comment by stanleyxu2005** [comment]
Thanks. I will study more into the script and find a way to specify the prebuild link instead of downloading from github.com

**Comment by stanleyxu2005** [comment]
What I mean is if there is an environment variable to point some zip files from local network instead of from github.com

**Comment by lgeiger** [comment]
@stanleyxu2005 There is a location where `prebuild-install` looks for prebuilt binaries on your system before downloading. The path it looks for is mentioned in the error log of the install.

Take a look at https://github.com/nteract/hydrogen/issues/558#issuecomment-272475363 for a example.

**Comment by stanleyxu2005** [comment]
Thank you @lgeiger , I think I now understand, how to trigger a manual build. (However I still dont have a way to build everything with npm/yarn directly. So I manually build it for target platform and maintain it into a private npm registery)
