### ISSUE TITLE
socker('req').send is queued?

### ISSUE THREAD

**Issue by jeffrson** [zeromq/zeromq.js#124]
Hi,
I'm having some problem with understanding this nodejs binding and make use of it.

First, in C#, reqsock.send twice throws an exception, because it violates the pattern.

In zeromq.js, however. all reqsock.send seem to be queued. They will be executed as soon as there is a connection. Then all responses will come in in reqsocket.on('message', ...).

If there's no server, a lot of requests may queue whose response (at some time in the future) is not important anymore and may in fact cause wrong behaviour.

How is this intended to work? Is there any way to clear the queue?

Thanks

**Comment by expelledboy** [comment]
I am trying to understand this wrapper as well, but it would seem if you want the same behaviour as in c# you would `socket.send(...)` async twice, and monitor for `socket.on('error', ...)` messages.

See the [_outgoing](https://github.com/zeromq/zeromq.js/blob/v4.1.1/lib/index.js#L294) variable on how the queue is implemented in the JS portion, however it basically gets queued in `libzmq` itself pretty [soon after](https://github.com/zeromq/zeromq.js/blob/v4.1.1/lib/index.js#L643) it zeromq.js gets the message, regardless of connection state.

**Comment by rolftimmermans** [comment]
This is addressed as of 6.0.0-beta.1, which is a reimplementation that addresses a number of fundamental issues with the previous versions of this library. For more background see #189.
