### ISSUE TITLE
Example of using RCVTIMEO option

### ISSUE THREAD

**Issue by expelledboy** [zeromq/zeromq.js#126]
Does this support the RCVTIMEO option, and if so how would I used it?

**Comment by interpretor** [comment]
The socket option is supported: https://github.com/zeromq/zeromq.js/blob/master/lib/index.js#L73
To set this option you have to:
```js
const zeromq = require('zeromq');

const socket = zeromq.socket('dealer');
socket.setsockopt(zeromq.ZMQ_RCVTIMEO, 0);
```
