### ISSUE TITLE
What is FD_SETSIZE set to?

### ISSUE THREAD

**Issue by mroosen** [zeromq/zeromq.js#130]
I'm having a boost of new clients using my Windows server and my previously compiled 0MQ (4.0.4) module hit a FD limit.

Do you have any idea what the current FD_SETSIZE for 4.2.0 (specifically the zeromq.js release) is ?

**Comment by rgbkrk** [comment]
[It's 1024 on Windows](https://github.com/zeromq/libzmq/blob/v4.2.0/builds/msvc/vs2015_xp/platform.hpp#L10) with our builds (I think).

**Comment by rgbkrk** [comment]
Just a note that we do build against libzmq 4.2.0 on Windows currently.

**Comment by mroosen** [comment]
Besides the vs2015_xp solution, all the other ones define FD_SIZE as 16384. Is the vs2015_xp version lagging behind compared to the other ones ?
https://github.com/zeromq/libzmq/search?utf8=%E2%9C%93&q=fd_setsize&type=

I've compiled libzmq but I have no idea how to make use of it regarding NodeJS.  Do you have any idea or tips how I could obtain/create the FD_SIZE 16384 build NodeJS binary ?

**Comment by rgbkrk** [comment]
I have no background on why `FD_SETSIZE` is 1024 there. Maybe it is just lagging and a PR needs to be made to increase it.

> Do you have any idea or tips how I could obtain/create the FD_SIZE 16384 build NodeJS binary ?

No clue, I'd love to hear how you do it though! There's probably a way to use your local build of libzmq for starters, you'd have to look at our build scripts.

We need more maintainers so I'm happy you've come by.

**Comment by rolftimmermans** [comment]
As of the latest 6.0 beta release all platforms include the same libzmq version (currently 4.3.2). If there is still an issue with `FD_SETSIZE` it should probably be addressed in libzmq itself..?
