### ISSUE TITLE
libzmq.5.dylib linking issue with electron-packager

### ISSUE THREAD

**Issue by jhargis** [zeromq/zeromq.js#131]
I'm fairly new to everything Node. Trying to build an Electron app on OSX 10.12.  I've used homebrew to install zeromq. My app requires  zerorpc  and zmq.  I set these env vars

```
npm_config_target="1.6.2" 
npm_config_runtime="electron"
npm_config_disturl="https://atom.io/download/electron"
npm_config_build_from_source="true"
```
Then package.  

```
./node_modules/.bin/electron-packager .  --overwrite
```

It works fine on the local dev machine but when copied to another machine it fails because the dylib for zeromq is not found.  

![zmq-dylib-fail](https://cloud.githubusercontent.com/assets/143113/24439526/907cfc1e-1403-11e7-81f9-f449036fb719.png)

I'm not really clear on what I need to do to get that file inside the packaged app.  Perhaps I'm doing something wrong or missed a step.

**Comment by lgeiger** [comment]
@jhargis You are not using this module.
You have [`zmq`](https://github.com/JustinTulloss/zeromq.node) installed which doesn't provide prebuild statically linked binaries. So you can't package your app with this module.

Please install `zeromq` (this module) with `npm i zeromq --save` and require it instead. You don't need to install external dependencies via homebrew.

**Comment by jhargis** [comment]
ugh. I somehow was confused and thought they were the same package just aliased. Could have swore I tried all combinations including just zeromq and not zmq. At any rate, thank you.

**Comment by jhargis** [comment]
The confusion I had was that I need the zerorpc package which requires zmq. The example I was working from mapped the dep for zerorpc to a forked version that substitutes zmq and msgpack with zeromq and msgpack-lite.
