### ISSUE TITLE
Unknown error message when using this lib

### ISSUE THREAD

**Issue by stanleyxu2005** [zeromq/zeromq.js#140]
I'm switching from zmq to zeromq. As all the apis are compatible, the migration process is quite smooth. After running my app for couple of days, I might randomly see such a warning. I don't know, whether it is related to zeromq. Could you kindly have a quick look?

> Assertion failed: Invalid argument (..\..\..\..\src\select.cpp:97)

**Comment by n-riesco** [comment]
The exception comes from `libzmq`. The main difference in terms of exception handling between `zmq` and `zeromq` is that a `libzmq` exception would cause `zmq` to die, whereas `zeromq` will throw it as JS exception (and thus your code could capture it with a `process.on('uncaughtException', onUncaughtException)` listener; in fact, this could give you a bit more insight where the exception is coming from).

It's hard to tell without having code to reproduce the error. If possible (I understand this is a hard request), could you post a code example to reproduce the error?

**Comment by stanleyxu2005** [comment]
This error appears randomly when I shutdown my app. Very likely, my code does not quit all zmq clients properly.

**Comment by stanleyxu2005** [comment]
I found the issue. I was not terminate my app correct (simply use a `process.exit()`). Now the code is properly exit, no more issue. Thank you for the kindly answer.
