### ISSUE TITLE
Process doesn't terminate even ZeroMQ socket closed

### ISSUE THREAD

**Issue by kiralex** [zeromq/zeromq.js#141]
I'm making a publish subscribe using ZeroMQ. Here is a simplified code :

```
import zmq from 'zeromq';
import d from 'debug';

const debug = d('publisher');

let port = '8000';
let subject = 'FLIGHTS';

const socket = zmq.socket('pub');

socket.on('close', function(...toto) {
  debug('connection closed');
});
socket.on('close_error', function(...toto) {
  debug('error while closing connexion');
});

socket.monitor(10, 0);
socket.bindSync('tcp://*:' + port);

export function send(message: object) {
  const jsonMessage = JSON.stringify(message);
  socket.send([subject, jsonMessage]);
}

export function close() {
  socket.close();
}

setTimeout( () =>
close()
, 3000 );
```
The problem I have is that the process won't exit even if the socket is closed after 3 seconds. I can't use process.exit because the module I'm making is used in a lot a jest tests. I didn't find anything in the ZeroMQ documentation. Can you help me, please ?

Thanks in advance.

**Comment by n-riesco** [comment]
I've tried an ES5 version of that code on Node v4.2.6, and it works for me:

```js
var zmq = require('zeromq');
var debug = require('debug')('publisher');

var port = '8000';
var subject = 'FLIGHTS';

var socket = zmq.socket('pub');

socket.on('close', function() {
  debug('connection closed');
});

socket.on('close_error', function() {
  debug('error while closing connexion');
});

socket.monitor(10, 0);
socket.bindSync('tcp://*:' + port);

function close() {
  socket.close();
}

setTimeout(close, 3000);
```

I'd have a look at the output of the transpiler you're using.

**Comment by rgbkrk** [comment]
> `import zmq from 'zeromq';`

We don't expose a `default` export so you'll want to do `import * as zmq from 'zeromq'`.

**Comment by lgeiger** [comment]
@rgbkrk should we add a default export?

**Comment by rgbkrk** [comment]
If we get another person that runs into this, I could see us doing it. It's a minor bump on a stable library, I'd prefer to save it for a time when it's really necessary. However, if someone adds it, I'll still happily merge it in.

**Comment by n-riesco** [comment]
@rgbkrk Is this possible while keeping compatibility with Node v0.10?

**Comment by rgbkrk** [comment]
`module.exports.default = module.exports` I think 🤔

**Comment by n-riesco** [comment]
https://github.com/esnext/es6-module-transpiler/issues/85

**Comment by n-riesco** [comment]
Looks like a harmless change?
