### ISSUE TITLE
ZMQ_ROUTER_HANDOVER not available

### ISSUE THREAD

**Issue by interpretor** [zeromq/zeromq.js#146]
The `ZMQ_ROUTER_HANDOVER` option is not available in the current version, it was only added in the Windows header file.
This is already version > 4.1, so it should be available.

**Comment by interpretor** [comment]
When is the next release planned? I would need this option for the zyre port I am currently working on and I cannot make a new release without the handover option.

**Comment by rgbkrk** [comment]
After we bring in #148 (assuming no issues) I'll be happy to ship the next release.

**Comment by rgbkrk** [comment]
All set, let us know how it goes.

**Comment by interpretor** [comment]
All working now, thanks!
