### ISSUE TITLE
TypeError: zmq.zmqVersion is not a function

### ISSUE THREAD

**Issue by nim65s** [zeromq/zeromq.js#150]
Hi,

When I try to import ZeroMQ (`var zmq = require('zeromq');`) in a new React application created with `create-react-app`, I get this error: `TypeError: zmq.zmqVersion is not a function`.

Has someone succeeded in using ZeroMQ with React ? I only need a subscriber to monitor what is sent from a ZeroMQ application written in Python.

**Comment by lgeiger** [comment]
> Has someone succeeded in using ZeroMQ with React?

Yeah, we're using it in [nteract](https://github.com/nteract/nteract/) and [Hydrogen](https://github.com/nteract/hydrogen/).

`zeromq` doesn't export `zmq.zmqVersion()`. Try using `zmq.version` instead.

**Comment by nim65s** [comment]
I don't care about the version, but it is exported here: https://github.com/zeromq/zeromq.js/blob/master/lib/index.js#L19

Should we remove this line then ?

**Comment by lgeiger** [comment]
It is exported as `version`.  We only call it `zmqVersion()` internally. Take a look at [this test](https://github.com/zeromq/zeromq.js/blob/master/test/exports.js#L7).

**Comment by nim65s** [comment]
Sorry, but I don't understand :/

I get this error when I add `var zmq = require('zeromq');` in my code, when I try to copy paste the subber.js example from the readme.

I just created a new project with `create-react-app`, then added `var zmq = require('zeromq');` in the generated `src/App.js`, and I got this error.

**Comment by lgeiger** [comment]
Oh I see, I thought you were trying to access the `zmqVersion` and that's why it's throwing.

If I recall correctly `create-react-app` uses webpack to bundle all dependencies. Since `zeromq` is a native module (uses C++ code) it cannot be packaged via webpack. Webpack should have a option to ignore this module.

Thinking about this again, I actually don't think it's even possible to run native modules in the browser. They are intended to be used in a Node.js environment like a server or an Electron app.

**Comment by nim65s** [comment]
ok, I should have detailed this from the beginning, sorry.

Do you know an alternative to get a ZeroMQ subscriber in a web browser ?

**Comment by nim65s** [comment]
I'll try https://github.com/zeromq/JSMQ, thanks for your clarifications :)

**Comment by rgbkrk** [comment]
> Do you know an alternative to get a ZeroMQ subscriber in a web browser ?

You'll need to proxy zeromq sockets with websockets for a regular web app, which means you'll need to write a node server.
