### ISSUE TITLE
Weird and not reproducible error "Resource temporarily unavailable (src/signaler.cpp:282)"

### ISSUE THREAD

**Issue by interpretor** [zeromq/zeromq.js#151]
I am building a node.js port of zyre (https://github.com/interpretor/zyre.js). As specified in https://rfc.zeromq.org/spec:36/ZRE/, I am using router and dealer sockets for communication.
My simple (and not final) unit test of the zyre module is throwing not reproducible errors only in Travis:
```
  Zyre
    ✓ should create a new instance of Zyre
    ✓ should inform about evasive peers (5104ms)
    ✓ should inform about expired peers (30103ms)
Resource temporarily unavailable (src/signaler.cpp:282)
Aborted (core dumped)
npm ERR! Test failed.  See above for more details.
```
On my Mac and my Ubuntu machine, I don't have those errors, and they don't occur every time in Travis. They even don't occur on the same unit test every time, this varies.
In the example above, the last test that passed creates two zmq router and two zmq dealer socket, and then closes those sockets after some time.
Then the next test should create another two zmq router and dealer sockets, and that is the point where it seems to crash.

Can someone give me a hint, what could be a possible reason for this behavior? This could be an issue of the zeromq.js binding, since the error happens somewhere in the libzmq binary.

**Comment by interpretor** [comment]
Looks like https://github.com/zeromq/libzmq/issues/1583 is the issue.

In libzmq 4.2, https://github.com/zeromq/libzmq/commit/e9e03f5ade3808f41ce5e53079bcecfd724b4610 and https://github.com/zeromq/libzmq/commit/596d6e5b1c2d060b2b5b09d01f7ebd207041791d seemed to have fixed this problem. This should explain why this problem only shows up in travis:
Slower machine, linux system (So libzmq 4.1 is used).

To fix this issue, we can either patch the libzmq 4.1 or update to 4.2 on linux systems.
Why is zeromq.js using 4.1 on linux, but not on macOS or Windows?

**Comment by lgeiger** [comment]
Thanks for investigating.

We rolled back to libzmq 4.1.6 on Linux because we were running into #94 which prevented us from shipping prebuilt binaries.

**Comment by interpretor** [comment]
I just read about it and edited my post.
So could we maybe investigate https://github.com/zeromq/zeromq.js/issues/94 again to solve it in another way than rolling back?

**Comment by interpretor** [comment]
Let's try a new release with libzmq 4.2.2?

**Comment by rgbkrk** [comment]
I can ship a release, what should our version number be since we're bumping libzmq underneath?

**Comment by lgeiger** [comment]
Both a patch or minor bump sounds good to me.

**Comment by rgbkrk** [comment]
Published, didn't run the `postpublish` step though, just like last time:

```
> zeromq@4.3.0 postpublish .
> ./scripts/trigger_travis_build.sh

{
  "@type": "error",
  "error_type": "wrong_credentials",
  "error_message": "access denied"
}{"message":"Authorization required"}+ zeromq@4.3.0
```

**Comment by lgeiger** [comment]
Retriggered the test builds manually:
https://travis-ci.org/zeromq/zeromq.js/builds/241455027
https://ci.appveyor.com/project/zeromq/zeromq-js/build/1.0.194

**Comment by rgbkrk** [comment]
Thank you!

**Comment by interpretor** [comment]
Seems to be fixed now.
If the error occurs again, feel free to reopen this issue.
