### ISSUE TITLE
Is it possible to use zeromq node.js binding with Angular/Cordova app?

### ISSUE THREAD

**Issue by manish-drake** [zeromq/zeromq.js#155]
I have tried importing node.js binding from npm. Obviously, the 'require' keyword does not work in the angular/cordova app. Neither does the 'import' keyword, apparently because the zmq.node binary is not really built for an angular/cordova app. I tried to browserify and that failed too. So my question here is if it is possible at all to use a node.js binding inside an angular/cordova mobile app to create a zmq client communicating with a zmq server running in a different device?

**Comment by minrk** [comment]
zeromq.js is bindings for the libzmq C library. It cannot be used in a browser.

**Comment by manish-drake** [comment]
That hurts!

**Comment by manish-drake** [comment]
Any suggestions if this is a terminal pursuit?

**Comment by interpretor** [comment]
Take a look into https://github.com/zeromq/JSMQ and see if it suits your needs.
