### ISSUE TITLE
Module mismatch. Expected 46, got 48

### ISSUE THREAD

**Issue by smeckels** [zeromq/zeromq.js#170]
> npm install zeromq

example.js:
```
let zmq = require('zeromq');
let sock = zmq.socket('sub');

sock.connect(pubSocket);
sock.subscribe('');

sock.on('message', function(topic, message){
  console.log(message);
})
```

> nodejs example.js

> module.js:435
>   return process.dlopen(module, path._makeLong(filename));
>                  ^
> 
> Error: Module version mismatch. Expected 46, got 48.
>     at Error (native)
>     at Object.Module._extensions..node (module.js:435:18)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/home/tulip/Documents/hsl/module/sources/gpio/node_modules/zeromq/lib/index.js:6:11)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)

**Comment by rgbkrk** [comment]
Run `npm rebuild`. Module versions will mismatch when you change node versions (or to electron).

**Comment by smeckels** [comment]
npm rebuild doesn't fix this. Manually deleting the node_module folder and doing npm install zeromq doesn't fix this. Doing npm install zeromq --build-from-source also doesn't work.

node -v = v6.10.2
npm -v = 3.10.10

>  npm install zeromq --build-from-source

> 
> > zeromq@4.5.0 install /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq
> > node scripts/prebuild-install.js || (npm run build:libzmq && node-gyp rebuild)
> 
> 
> prebuild-install info begin Prebuild-install version 2.2.0
> prebuild-install info install --build-from-source specified, not attempting download.
> 
> 
> > zeromq@4.5.0 build:libzmq /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq
> > node scripts/preinstall.js
> 
> Building libzmq for linux
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether UID '1001' is supported by ustar format... yes
> checking whether GID '1001' is supported by ustar format... yes
> checking how to create a ustar tar archive... gnutar
> checking whether make supports nested variables... (cached) yes
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking for style of include used by make... GNU
> checking dependency style of gcc... gcc3
> checking whether C compiler accepts -std=gnu11... yes
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... gcc3
> checking whether g++ supports C++11 features by default... no
> checking whether g++ supports C++11 features with -std=gnu++11... yes
> checking for a sed that does not truncate output... /bin/sed
> checking whether to build with code coverage support... no
> checking for a sed that does not truncate output... (cached) /bin/sed
> checking for gawk... (cached) mawk
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for xmlto... no
> checking for asciidoc... no
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking how to print strings... printf
> checking for a sed that does not truncate output... (cached) /bin/sed
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for fgrep... /bin/grep -F
> checking for ld used by gcc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking whether the shell understands some XSI constructs... yes
> checking whether the shell understands "+="... yes
> checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
> checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... dlltool
> checking how to associate runtime and link libraries... printf %s\n
> checking for ar... ar
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for mt... mt
> checking if mt is a manifest tool... no
> checking how to run the C preprocessor... gcc -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -fPIC -DPIC
> checking if gcc PIC flag -fPIC -DPIC works... yes
> checking if gcc static flag -static works... yes
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... no
> checking whether to build static libraries... yes
> checking how to run the C++ preprocessor... g++ -std=gnu++11 -E
> checking for ld used by g++ -std=gnu++11... /usr/bin/ld -m elf_x86_64
> checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
> checking whether the g++ -std=gnu++11 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking for g++ -std=gnu++11 option to produce PIC... -fPIC -DPIC
> checking if g++ -std=gnu++11 PIC flag -fPIC -DPIC works... yes
> checking if g++ -std=gnu++11 static flag -static works... yes
> checking if g++ -std=gnu++11 supports -c -o file.o... yes
> checking if g++ -std=gnu++11 supports -c -o file.o... (cached) yes
> checking whether the g++ -std=gnu++11 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking dynamic linker characteristics... (cached) GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking for valgrind... no
> checking whether the C compiler works... yes
> checking whether we are using Intel C compiler... no
> checking whether we are using Sun Studio C compiler... no
> checking whether we are using clang C compiler... no
> checking whether we are using gcc >= 4 C compiler... yes
> checking whether the C++ compiler works... yes
> checking whether we are using Intel C++ compiler... no
> checking whether we are using Sun Studio C++ compiler... no
> checking whether we are using clang C++ compiler... no
> checking whether we are using gcc >= 4 C++ compiler... yes
> checking whether to enable debugging information... no
> checking whether to enable code coverage... no
> checking if TIPC is available and supports nonblocking connect... no
> checking for library containing dladdr... -ldl
> checking for pthread_create in -lpthread... yes
> checking for clock_gettime in -lrt... yes
> checking whether C++ compiler supports -fvisibility=hidden... yes
> checking whether C++ compiler supports dso visibility... yes
> checking whether to build documentation... no
> checking whether to install manpages... no
> configure: Choosing polling system from 'kqueue epoll devpoll pollset poll select'...
> configure: Using 'epoll' polling system with CLOEXEC
> checking for ANSI C header files... (cached) yes
> checking errno.h usability... yes
> checking errno.h presence... yes
> checking for errno.h... yes
> checking time.h usability... yes
> checking time.h presence... yes
> checking for time.h... yes
> checking for unistd.h... (cached) yes
> checking limits.h usability... yes
> checking limits.h presence... yes
> checking for limits.h... yes
> checking stddef.h usability... yes
> checking stddef.h presence... yes
> checking for stddef.h... yes
> checking for stdlib.h... (cached) yes
> checking for string.h... (cached) yes
> checking arpa/inet.h usability... yes
> checking arpa/inet.h presence... yes
> checking for arpa/inet.h... yes
> checking netinet/tcp.h usability... yes
> checking netinet/tcp.h presence... yes
> checking for netinet/tcp.h... yes
> checking netinet/in.h usability... yes
> checking netinet/in.h presence... yes
> checking for netinet/in.h... yes
> checking sys/socket.h usability... yes
> checking sys/socket.h presence... yes
> checking for sys/socket.h... yes
> checking sys/time.h usability... yes
> checking sys/time.h presence... yes
> checking for sys/time.h... yes
> checking ifaddrs.h usability... yes
> checking ifaddrs.h presence... yes
> checking for ifaddrs.h... yes
> checking sys/uio.h usability... yes
> checking sys/uio.h presence... yes
> checking for sys/uio.h... yes
> checking sys/eventfd.h usability... yes
> checking sys/eventfd.h presence... yes
> checking for sys/eventfd.h... yes
> checking whether EFD_CLOEXEC is supported... yes
> checking whether SO_PEERCRED is declared... yes
> checking whether LOCAL_PEERCRED is declared... no
> checking for stdbool.h that conforms to C99... no
> checking for _Bool... no
> checking for an ANSI C-conforming const... yes
> checking for inline... inline
> checking for size_t... yes
> checking for ssize_t... yes
> checking whether time.h and sys/time.h may both be included... yes
> checking for uint32_t... yes
> checking for working volatile... yes
> configure: Using tweetnacl for CURVE security
> checking "with_norm_ext = no"... no
> checking how to enable additional warnings for C++ compiler... -Wall
> checking how to turn warnings to errors in C++ compiler... -Werror
> checking whether compiler supports __atomic_Xxx intrinsics... yes
> checking return type of signal handlers... void
> checking for perror... yes
> checking for gettimeofday... yes
> checking for clock_gettime... yes
> checking for memset... yes
> checking for socket... yes
> checking for getifaddrs... yes
> checking for freeifaddrs... yes
> checking for fork... yes
> checking for posix_memalign... yes
> checking for mkdtemp... yes
> checking alloca.h usability... yes
> checking alloca.h presence... yes
> checking for alloca.h... yes
> checking whether SOCK_CLOEXEC is supported... yes
> checking whether SO_KEEPALIVE is supported... yes
> checking whether TCP_KEEPCNT is supported... yes
> checking whether TCP_KEEPIDLE is supported... yes
> checking whether TCP_KEEPINTVL is supported... yes
> checking whether TCP_KEEPALIVE is supported... no
> checking for ./.git... no
> configure: Building stable and legacy API (no draft API)
> checking for LIBUNWIND... no
> configure: WARNING: Cannot find libunwind
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating src/libzmq.pc
> config.status: creating doc/Makefile
> config.status: creating builds/Makefile
> config.status: creating builds/msvc/Makefile
> config.status: creating src/platform.hpp
> config.status: executing depfiles commands
> config.status: executing libtool commands
> Making all in doc
> make[1]: Entering directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
> make[1]: Entering directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2'
>   CXX      src/src_libzmq_la-address.lo
>   CXX      src/src_libzmq_la-client.lo
>   CXX      src/src_libzmq_la-clock.lo
>   CXX      src/src_libzmq_la-ctx.lo
>   CXX      src/src_libzmq_la-curve_client.lo
>   CXX      src/src_libzmq_la-curve_server.lo
>   CXX      src/src_libzmq_la-dealer.lo
>   CXX      src/src_libzmq_la-devpoll.lo
>   CXX      src/src_libzmq_la-dgram.lo
>   CXX      src/src_libzmq_la-dish.lo
>   CXX      src/src_libzmq_la-dist.lo
>   CXX      src/src_libzmq_la-epoll.lo
>   CXX      src/src_libzmq_la-err.lo
>   CXX      src/src_libzmq_la-fq.lo
>   CXX      src/src_libzmq_la-gather.lo
>   CXX      src/src_libzmq_la-gssapi_mechanism_base.lo
>   CXX      src/src_libzmq_la-gssapi_client.lo
>   CXX      src/src_libzmq_la-gssapi_server.lo
>   CXX      src/src_libzmq_la-io_object.lo
>   CXX      src/src_libzmq_la-io_thread.lo
>   CXX      src/src_libzmq_la-ip.lo
>   CXX      src/src_libzmq_la-ipc_address.lo
>   CXX      src/src_libzmq_la-ipc_connecter.lo
>   CXX      src/src_libzmq_la-ipc_listener.lo
>   CXX      src/src_libzmq_la-kqueue.lo
>   CXX      src/src_libzmq_la-lb.lo
>   CXX      src/src_libzmq_la-mailbox.lo
>   CXX      src/src_libzmq_la-mailbox_safe.lo
>   CXX      src/src_libzmq_la-mechanism.lo
>   CXX      src/src_libzmq_la-metadata.lo
>   CXX      src/src_libzmq_la-msg.lo
>   CXX      src/src_libzmq_la-mtrie.lo
>   CXX      src/src_libzmq_la-norm_engine.lo
>   CXX      src/src_libzmq_la-null_mechanism.lo
>   CXX      src/src_libzmq_la-object.lo
>   CXX      src/src_libzmq_la-options.lo
>   CXX      src/src_libzmq_la-own.lo
>   CXX      src/src_libzmq_la-pair.lo
>   CXX      src/src_libzmq_la-pgm_receiver.lo
>   CXX      src/src_libzmq_la-pgm_sender.lo
>   CXX      src/src_libzmq_la-pgm_socket.lo
>   CXX      src/src_libzmq_la-pipe.lo
>   CXX      src/src_libzmq_la-plain_client.lo
>   CXX      src/src_libzmq_la-plain_server.lo
>   CXX      src/src_libzmq_la-poll.lo
>   CXX      src/src_libzmq_la-poller_base.lo
>   CXX      src/src_libzmq_la-pollset.lo
>   CXX      src/src_libzmq_la-precompiled.lo
>   CXX      src/src_libzmq_la-proxy.lo
>   CXX      src/src_libzmq_la-pub.lo
>   CXX      src/src_libzmq_la-pull.lo
>   CXX      src/src_libzmq_la-push.lo
>   CXX      src/src_libzmq_la-radio.lo
>   CXX      src/src_libzmq_la-random.lo
>   CXX      src/src_libzmq_la-raw_decoder.lo
>   CXX      src/src_libzmq_la-raw_encoder.lo
>   CXX      src/src_libzmq_la-reaper.lo
>   CXX      src/src_libzmq_la-rep.lo
>   CXX      src/src_libzmq_la-req.lo
>   CXX      src/src_libzmq_la-router.lo
>   CXX      src/src_libzmq_la-scatter.lo
>   CXX      src/src_libzmq_la-select.lo
>   CXX      src/src_libzmq_la-server.lo
>   CXX      src/src_libzmq_la-session_base.lo
>   CXX      src/src_libzmq_la-signaler.lo
>   CXX      src/src_libzmq_la-socket_base.lo
>   CXX      src/src_libzmq_la-socks.lo
>   CXX      src/src_libzmq_la-socks_connecter.lo
>   CXX      src/src_libzmq_la-stream.lo
>   CXX      src/src_libzmq_la-stream_engine.lo
>   CXX      src/src_libzmq_la-sub.lo
>   CXX      src/src_libzmq_la-tcp.lo
>   CXX      src/src_libzmq_la-tcp_address.lo
>   CXX      src/src_libzmq_la-tcp_connecter.lo
>   CXX      src/src_libzmq_la-tcp_listener.lo
>   CXX      src/src_libzmq_la-thread.lo
>   CXX      src/src_libzmq_la-timers.lo
>   CXX      src/src_libzmq_la-tipc_address.lo
>   CXX      src/src_libzmq_la-tipc_connecter.lo
>   CXX      src/src_libzmq_la-tipc_listener.lo
>   CXX      src/src_libzmq_la-trie.lo
>   CXX      src/src_libzmq_la-udp_address.lo
>   CXX      src/src_libzmq_la-udp_engine.lo
>   CXX      src/src_libzmq_la-v1_decoder.lo
>   CXX      src/src_libzmq_la-v2_decoder.lo
>   CXX      src/src_libzmq_la-v1_encoder.lo
>   CXX      src/src_libzmq_la-v2_encoder.lo
>   CXX      src/src_libzmq_la-vmci.lo
>   CXX      src/src_libzmq_la-vmci_address.lo
>   CXX      src/src_libzmq_la-vmci_connecter.lo
>   CXX      src/src_libzmq_la-vmci_listener.lo
>   CXX      src/src_libzmq_la-xpub.lo
>   CXX      src/src_libzmq_la-xsub.lo
>   CXX      src/src_libzmq_la-zmq.lo
>   CXX      src/src_libzmq_la-zmq_utils.lo
>   CXX      src/src_libzmq_la-decoder_allocators.lo
>   CXX      src/src_libzmq_la-socket_poller.lo
>   CC       src/src_libzmq_la-tweetnacl.lo
>   CXX      tools/curve_keygen.o
>   CXX      perf/local_lat.o
>   CXX      perf/remote_lat.o
>   CXX      perf/local_thr.o
>   CXX      perf/remote_thr.o
>   CXX      perf/inproc_lat.o
>   CXX      perf/inproc_thr.o
>   CXXLD    src/libzmq.la
> ar: `u' modifier ignored since `D' is the default (see `U')
>   CXXLD    perf/local_lat
>   CXXLD    tools/curve_keygen
>   CXXLD    perf/local_thr
>   CXXLD    perf/remote_lat
>   CXXLD    perf/remote_thr
>   CXXLD    perf/inproc_lat
>   CXXLD    perf/inproc_thr
> make[1]: Leaving directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2'
> Making install in doc
> make[1]: Entering directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
> make[2]: Entering directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
> make[2]: Nothing to be done for 'install-exec-am'.
> make[2]: Leaving directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
> make[1]: Leaving directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2/doc'
> make[1]: Entering directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2'
> make[2]: Entering directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2'
>  /bin/mkdir -p '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib'
>  /bin/bash ./libtool   --mode=install /usr/bin/install -c   src/libzmq.la '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib'
> libtool: install: /usr/bin/install -c src/.libs/libzmq.lai /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib/libzmq.la
> libtool: install: /usr/bin/install -c src/.libs/libzmq.a /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib/libzmq.a
> libtool: install: chmod 644 /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib/libzmq.a
> libtool: install: ranlib /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib/libzmq.a
> libtool: finish: PATH="/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/node_modules/.bin:/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/node_modules/.bin:/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin" ldconfig -n /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib
> ----------------------------------------------------------------------
> Libraries have been installed in:
>    /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib
> 
> If you ever happen to want to link against installed libraries
> in a given directory, LIBDIR, you must either use libtool, and
> specify the full pathname of the library, or use the `-LLIBDIR'
> flag during linking and do at least one of the following:
>    - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
>      during execution
>    - add LIBDIR to the `LD_RUN_PATH' environment variable
>      during linking
>    - use the `-Wl,-rpath -Wl,LIBDIR' linker flag
>    - have your system administrator add LIBDIR to `/etc/ld.so.conf'
> 
> See any operating system documentation about shared libraries for
> more information, such as the ld(1) and ld.so(8) manual pages.
> ----------------------------------------------------------------------
>  /bin/mkdir -p '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/bin'
>   /bin/bash ./libtool   --mode=install /usr/bin/install -c tools/curve_keygen '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/bin'
> libtool: install: /usr/bin/install -c tools/curve_keygen /home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/bin/curve_keygen
>  /bin/mkdir -p '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/include'
>  /usr/bin/install -c -m 644 include/zmq.h include/zmq_utils.h '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/include'
>  /bin/mkdir -p '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib/pkgconfig'
>  /usr/bin/install -c -m 644 src/libzmq.pc '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/scripts/../zmq/lib/pkgconfig'
> make[2]: Leaving directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2'
> make[1]: Leaving directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/zmq/zeromq-4.2.2'
> Succesfully build libzmq on Mon Jul 10 2017 13:10:37 GMT-0400 (EDT)
> make: Entering directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/build'
>   CXX(target) Release/obj.target/zmq/binding.o
>   SOLINK_MODULE(target) Release/obj.target/zmq.node
>   COPY Release/zmq.node
> make: Leaving directory '/home/tulip/Documents/hsl/module/sources/dell3000gpio/node_modules/zeromq/build'
> /home/tulip/Documents/hsl/module/sources/dell3000gpio
> └─┬ zeromq@4.5.0 
>   ├── nan@2.6.2 
>   └─┬ prebuild-install@2.2.0 
>     ├── expand-template@1.0.3 
>     ├── github-from-package@0.0.0 
>     ├── minimist@1.2.0 
>     ├─┬ mkdirp@0.5.1 
>     │ └── minimist@0.0.8 
>     ├── node-abi@2.0.3 
>     ├── noop-logger@0.1.1 
>     ├─┬ npmlog@4.1.2 
>     │ ├─┬ are-we-there-yet@1.1.4 
>     │ │ ├── delegates@1.0.0 
>     │ │ └─┬ readable-stream@2.3.3 
>     │ │   ├── core-util-is@1.0.2 
>     │ │   ├── inherits@2.0.3 
>     │ │   ├── isarray@1.0.0 
>     │ │   ├── process-nextick-args@1.0.7 
>     │ │   ├── string_decoder@1.0.3 
>     │ │   └── util-deprecate@1.0.2 
>     │ ├── console-control-strings@1.1.0 
>     │ ├─┬ gauge@2.7.4 
>     │ │ ├── aproba@1.1.2 
>     │ │ ├── has-unicode@2.0.1 
>     │ │ ├── object-assign@4.1.1 
>     │ │ ├── signal-exit@3.0.2 
>     │ │ ├─┬ string-width@1.0.2 
>     │ │ │ ├── code-point-at@1.1.0 
>     │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
>     │ │ │   └── number-is-nan@1.0.1 
>     │ │ ├─┬ strip-ansi@3.0.1 
>     │ │ │ └── ansi-regex@2.1.1 
>     │ │ └── wide-align@1.1.2 
>     │ └── set-blocking@2.0.0 
>     ├── os-homedir@1.0.2 
>     ├─┬ pump@1.0.2 
>     │ ├── end-of-stream@1.4.0 
>     │ └─┬ once@1.4.0 
>     │   └── wrappy@1.0.2 
>     ├─┬ rc@1.2.1 
>     │ ├── deep-extend@0.4.2 
>     │ ├── ini@1.3.4 
>     │ └── strip-json-comments@2.0.1 
>     ├─┬ simple-get@1.4.3 
>     │ └── unzip-response@1.0.2 
>     ├─┬ tar-fs@1.15.3 
>     │ ├── chownr@1.0.1 
>     │ └─┬ tar-stream@1.5.4 
>     │   └── bl@1.2.1 
>     ├─┬ tunnel-agent@0.6.0 
>     │ └── safe-buffer@5.1.1 
>     └── xtend@4.0.1 
> 
> npm WARN enoent ENOENT: no such file or directory, open '/home/tulip/Documents/hsl/module/sources/dell3000gpio/package.json'
> npm WARN dell3000gpio No description
> npm WARN dell3000gpio No repository field.
> npm WARN dell3000gpio No README data
> npm WARN dell3000gpio No license field.

**Comment by rgbkrk** [comment]
```
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
```

What kind of system is this?

**Comment by smeckels** [comment]
Embedded device running ubuntu 

> uname -a
Linux tulip-Embedded-Box 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rgbkrk** [comment]
You are now the best bet for solving it since no current maintainers have that hardware. How are other native modules for you? It's node's build setup that dictates the module version.

For [reference, ABI 46 is node 4.5 and ABI 48 is node 5.1](https://nodejs.org/en/download/releases/).

However, [if you're using electron it's a bit more complicated](https://github.com/lgeiger/node-abi/blob/master/index.js) and you need to instrument the build process yourself.

**Comment by smeckels** [comment]
Lovely, as a C++ guy this is 'fun' jumping into the JS world. I've had no issues using the FFI node.js library (which also builds native code). I've also used nan and sleep libraries without issue

**Comment by interpretor** [comment]
48 should be v6 and 46 should be v4.
Probably multiple node versions installed?

**Comment by smeckels** [comment]
I uninstalled npm and re-installed npm and things started working. I also did a npm init and added this as a proper dep, before i was just doing npm install zeromq. So something fixed the issues, but honestly idk what. This can be closed, totally an issue on my side.
