### ISSUE TITLE
after sub unsubscribes xpub, it still receive msg

### ISSUE THREAD

**Issue by zyf0330** [zeromq/zeromq.js#173]
After sub executes `unsubscribe(name)`, `sub.on('message')` still receives one message from that name.
Is this normal? I don't think, but I don't know zmq enoughly. So please examine it. Thanks.

**Comment by reqshark** [comment]
are you using xpub for proxying?

**Comment by zyf0330** [comment]
I don't understand what you mean proxy. I use zeromq  npm module.

**Comment by reqshark** [comment]
you mentioned `xpub` socket in issue title, we use that socket for binding a proxy endpoint

xpub and xsub is useful for subscriptions where publisher and subscribers are behind NAT local or for whatever other use case you want to relay message.  the local sub and local pub workflow is like: 

local pub connect --> xsub (remote bind) --> local sub

**Comment by zyf0330** [comment]
I know this. If you ask whether another side is xpub, I will say yes. My sub connects to a xpub.

**Comment by reqshark** [comment]
it's not quite related to your bug report, but there's a proxy method in our lib that does that for you: https://github.com/zeromq/zeromq.js/blob/master/lib/index.js#L786-L796

**Comment by reqshark** [comment]
my gut tells me calling unsubscribe on a sub when using `zmq_proxy()` will forward the call across the proxy socket. 

I think the correct way to do xpub/xsub is to use internal lib's `zmq_proxy`, but that's just my hunch

**Comment by zyf0330** [comment]
Actually, xpub/xsub is not wrote by node, maybe golang.

**Comment by reqshark** [comment]
not golang, but you're getting warmer: C/C++

when you call xpub/xsub in javascript, node binding forwards your JS function params (type converted and all) to the direct call in C/C++ via the mapped set of C/C++ calls we exposed

**Comment by zyf0330** [comment]
I mean, sub receives msg from xpub which is at another server wrote by golang.

**Comment by zyf0330** [comment]
I want to know, when I call `sub.unsubscribe(name)`, if `zeromq` will throw away following msg synchronously.

**Comment by reqshark** [comment]
> I mean, sub receives msg from xpub which is at another server wrote by golang.

protocol is language/platform agnostic so msg envelopes can be read from/written to by whatever

> I want to know, when I call sub.unsubscribe(name), if zeromq will throw away following msg synchronously.

whether thrown away sync or not is kinda beside your point. the more important question: 
* is it only one message you recv after unsubscribe, or do you get more than one message from pub after call to unsubscribe?

**Comment by reqshark** [comment]
one of zeromq's biggest innovations was doing subscription filtering on the publisher

(not on the subscriber)

you can see how other messaging systems, like RabbitMQ which filter subscriptions on the receiving end are ultimately inefficient. 

### Why send out a message to a subscriber when your sub doesn't care? 

Do your filter at the publisher. That's just good design

If your publisher has already sent a message your system kernel's TX buffer and then later receives an unsubscription notice (before TX buf flush), the kernel will still push any pending TX buffer out to the router. The way the kernel was designed and compiled (at least unix/linux), user space won't be able to stop that

**Comment by reqshark** [comment]
you want sub to drop all msgs after unsubscribe call when the msg filter is performed by pub

not a bad idea, but it sounds more like an upstream feature request to libzmq

**Comment by zyf0330** [comment]
> If your publisher has already sent a message your system kernel's TX buffer and then later receives an unsubscription notice (before TX buf flush), the kernel will still push any pending TX buffer out to the router. The way the kernel was designed and compiled (at least unix/linux), user space won't be able to stop that

This gets me, it is what I want to say. Of course there is more.
This is Sub behavior from https://rfc.zeromq.org/spec:29/PUBSUB
> For processing incoming messages:
> MAY, depending on the transport, filter messages according to subscriptions, using a prefix match algorithm.

So when sub `unsubscribe`, if xpub must confirm that unsubscribe msg, then sub won't receive more message. If so, after `unsubscribe` still receive message is acceptable.

**Comment by zyf0330** [comment]
After debug in lib/index.js, I found, after I call `unsubscribe(name)`,  callback of `this._zmq.onReadReady` 
 is called, then `self._flushReads()` and `this._emitMessage(message)` execute. And so I receive one message.

**Comment by interpretor** [comment]
Thanks for debugging!
Is this behavior intended or should we fix it?

**Comment by zyf0330** [comment]
Sorry, I don't understand what mean of your words

**Comment by zyf0330** [comment]
Hello, are you here?
