### ISSUE TITLE
replace js proxy method with lib's zmq_proxy

### ISSUE THREAD

**Issue by reqshark** [zeromq/zeromq.js#174]
something i've wanted to do for a while is remove the JS proxy method and call the library method

couple benefits of doing this right off the bat:

1. <strong>performance</strong>: remove the overhead of extra context switching between library and JS for messages relayed over proxied sockets

2. <strong>improved protocol handling</strong> of the msg envelope. proxy message envelopes sometimes differ from the simple msg envelope sent during normal (non-proxy) sockets

the biggest win here is performance, but the envelope handling in JavaScript is also [error prone](https://github.com/zeromq/zeromq.js/issues/173)

**Comment by rolftimmermans** [comment]
This is now also addressed by [zeromq-ng](https://github.com/rolftimmermans/zeromq-ng).

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release incorporates a proxy that uses the native libzmq implementation.
