### ISSUE TITLE
zmq.node: undefined symbol: node_module_register  --- Azure iot-edge nodejs binding

### ISSUE THREAD

**Issue by kmaheshbabu-ckpt** [zeromq/zeromq.js#187]
Currently we are using zeromq.js and works wonderfully with ZeroMQ using Node v6.9.5 or new LTS.

 We are trying to use IoT Edge (https://github.com/Azure/iot-edge) provided by Azure along with zeromq.js.  IoT Edge provides NodeJS binding which can run nodejs based programs. The below error occurs when zeromq.js is started up by iot-edge. Any suggestions on how to overcome the issue?

ERROR: Error: /home/pi/iot-edge-docker/simple/node_modules/zeromq/build/Release/zmq.node: undefined symbol: node_module_register
Error: Time:Mon Oct  2 15:49:36 2017 File:/vso/VSIoTGW/iot-edge/bindings/nodejs/src/nodejs.cpp Func:on_module_start Line:943 Expected registerModule to return 'true' but it returned 'false'
Error: Time:Mon Oct  2 15:49:36 2017 File:/vso/VSIoTGW/iot-edge/bindings/nodejs/src/nodejs.cpp Func:NODEJS_Create Line:135 Node process failed to start
Error: Time:Mon Oct  2 15:49:36 2017 File:/vso/VSIoTGW/iot-edge/core/src/gateway_internal.c Func:gateway_addmodule_internal Line:446 Module_Create failed.
Error: Time:Mon Oct  2 15:49:36 2017 File:/vso/VSIoTGW/iot-edge/core/src/gateway_createfromjson.c Func:Gateway_CreateFromJson Line:78 Failed to create gateway using lower level library.
Error: Time:Mon Oct  2 15:49:36 2017 File:/vso/VSIoTGW/src/gw/src/main.c Func:main Line:50 An error occurred while creating the gateway.

**Comment by kmaheshbabu-ckpt** [comment]
Appears to be a IoT Edge issue, https://github.com/Azure/iot-edge/issues/308. Can be closed.

**Comment by rgbkrk** [comment]
Awww, that's too bad. zeromq would be perfect for IoT Edge use cases.
