### ISSUE TITLE
[Question] REQ/REP send order

### ISSUE THREAD

**Issue by affanshahid** [zeromq/zeromq.js#191]
I'm using REQ/REP and trying to match the responses to requests, since there is just one `Socket.on('message', ...)` callback. 

Currently I am using a queue, as suggested in https://github.com/JustinTulloss/zeromq.node/issues/48:
```javascript
let responses = [];

socket.on('message', () => {
    const callback = responses.shift();
    callback.apply(null, arguments);
});

function performRequest(req, callback) {
    responses.push(callback);
    socket.send(req);
}
```
I'm happy with this solution but I am wondering something which might be related to the way Node.js/ZMQ handles sending messages:

Given that all I/O in node.js is async, is there a guarantee that the message I send first will be delivered first? i.e:
Lets say I do `socket.send(verylongmessage);` followed by `socket.send(tinymessage);` will the verylongmessage be delivered to the server FIRST everytime? because if it doesn't, the queue solution won't work. I did a small test for this and it seems to work fine but I'd appreciate some insight on this just to be sure.

**Comment by rolftimmermans** [comment]
Yes, the queue order should be respected by both this library & libzmq.
