### ISSUE TITLE
Cross compile for armv7 gnu linux

### ISSUE THREAD

**Issue by gitgkk** [zeromq/zeromq.js#192]
Hi,
I've an embedded project and I need zeromq for armv7 architecture with gnu linux. I tried to compile with the npm --arch=ARMv7 install zeromq but this fails. I need a 32 bit version as the processor is Cortex A9 but the build continues with defaults to generate a 64 bit linux zmq.node.

I get a warning: prebuild-install WARN install /home/dev/reportingsoftware-nodejs4.4.3/node_modules/zeromq/build/Release/zmq.node: wrong ELF class: ELFCLASS32

Here is the output of the file command: 
zmq.node: ELF 64-bit LSB  shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=145ab7c362dfbf1f4fb411db83774341b8e0c8d0, not stripped

I'm on Ubuntu 14.04 64 bit VirtualBox VM. The cross compiler tool chain exists as we compile other pograms for the project.

Can the author or somebody help me to cross compile properly?
Thanks in advance.

**Comment by gitgkk** [comment]
I used the prebuilt binary and some other help on the web to solve my problem. Nevertheless, it would have been interesting to know about the right command command.

**Comment by interpretor** [comment]
[Here](https://github.com/zeromq/zeromq.js/blob/master/scripts/cross_compile.sh) you can see how we cross compile our prebuilds for ARMv7 and 8.
