### ISSUE TITLE
ZMQ_XPUB_MANUAL option

### ISSUE THREAD

**Issue by alenpesikan** [zeromq/zeromq.js#193]
Is ZMQ_XPUB_MANUAL socket option supported on xpub?

**Comment by rolftimmermans** [comment]
The latest 6.0 beta supports this setting as `socket.manual`. It would be great if you could try it out! The new version has a new API that addresses some fundamental issues with the previous API, but it does include a compatibility layer that should make upgrading easier. See #189 for the reasoning behind the new API.

If you run into any problems feel free to report it here or in a new issue.
