### ISSUE TITLE
Communication between Node.js socket and external tcp socket

### ISSUE THREAD

**Issue by SergiuPalaxo** [zeromq/zeromq.js#204]
I'm trying communicate between a Node.js socket and an external tcp socket.

The external socket (```tcp://***.***.***.***:5555```) is a part of a C++ service, and he acts like a ```dealer```.

The Node.js server should act like a ```router```, which should monitor and pass messages to the available ```workers``` (that should be received from the external tcp socket).

The connection is successfully made between both services, but once I am connected to the tcp socket, I don't receive any ```message``` from the external service. 

    # Node.js server
    
    let zmq = require('zmq');
    socket = zmq.socket('router');
    
    // Successfully connected
    socket.on('connect', () => {console.log('Connected!')}); 

    // No message received from tcp
    socket.on('message', (message) => {console.log('Message: ', message)}); 

    socket.monitor(500, 0);
    socket.connect('tcp://***.***.***.***:5555');

Any thought will be very welcomed!

  [1]: https://github.com/JustinTulloss/zeromq.node
  [2]: http://zeromq.org/

**Comment by rolftimmermans** [comment]
A `req` socket type means that you have to send a message first, and only then will you be able to get a response. In your code I can only see you listening for messages – that will not work. 

You could try connecting another `dealer` from Node.js to your C++ `dealer` socket, but it depends on how you send messages in C++ whether or not you'll receive something, I guess.

**Comment by SergiuPalaxo** [comment]
@rolftimmermans I just updated my code, the Node.js socket should act like a ```router```, I do apologize.

**Comment by rolftimmermans** [comment]
This has been a while, have you managed to resolve it? The only thing I can think of is to replace the IP address with `0.0.0.0` so that the socket is bound on all interfaces. If that doesn't work please open a new issue, preferably with a complete example that demonstrates the problem you're encountering.

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
