### ISSUE TITLE
REQREP race condition in send

### ISSUE THREAD

**Issue by jgrnt** [zeromq/zeromq.js#207]
I discovered a race condition, where message fail to be send. I think my usage of the socket should be support. This error appears, when a REQ message should be send and meanwhile a reply is received. Then the outgoing message stays in the send queue.

# Minimal Example

The error can be easily produced by the following little programs:

A simple echo REP server, which immediately answers:

```var zmq = require('zeromq')
var rep = zmq.socket('rep')


rep.on('message', function(msg){
    console.log("got "+ msg);
    rep.send(msg);
});
rep.bind('tcp://127.0.0.1:5423', function (error) {
      if (error) throw error;
});
```

A test client, which sends two messages and is blocking the VM in between:

```var zmq = require('zeromq')

var req = zmq.socket('req');

req.on('message', function(msg){
    console.log("Got "+ msg);
})

req.connect('tcp://127.0.0.1:5423');
req.send('msg1');
console.log('sent msg1');

//Busy loop
var j=1;
for(var i=0;i<1000;i++){j=j*2;}

req.send('msg2'+j);
console.log('sent msg2'+j);
```

One has to run those to scripts in two different VMs and the expected output is that both messages are received on the server and echoed backed to the client.
What happens is that only one message is received.

# Error analysis

In the following code we check if the socket is still busy and notify the socket that a read can be performed.
https://github.com/zeromq/zeromq.js/blob/26eecdc43d5a67b35475795aeb59f2e19d165ec5/binding.cc#L1281-L1297

Subsequently `flushReads` is called and this signal should trigger a new `flushWrites`.
But this does not work as the message to be sent is not jet put back into the queue and the "locking" of `flushWrites` prevents subsequent calls.

**Comment by XeniaSiskaki** [comment]
Any news on merging this PR?

**Comment by rgbkrk** [comment]
The PR for this, #208 was merged. It's in both the 5.0.0 and 5.1.0 release.
