### ISSUE TITLE
High Page Faults and I/O Rate

### ISSUE THREAD

**Issue by shotwn** [zeromq/zeromq.js#211]
I am trying to implement a very basic RPC module using zeromq.js. It has a matching python module that works as expected when using it as python <-> python. I am trying to implement both modules on windows at the moment.
Receiving messages from python causes high amount of page faults and unexpectedly high i/o. It is especially noticeable in relatively high frequency situations. **I had tried Pair and Router - Dealer couples.** Both gave almost same results.

Requests: `["CALL",300,{"callback":0},"plsnogank",["report"],{"args":[false,true]}]`
Answers: `["RESULT", request_id, {callback: 0}, "result"]`

**~10 iterations per second, 300 iterations in total.**
`node -> python -> node :` **153.046** page faults, **8MB/s** avg total I/O during iterations.
`python -> python -> python:` **6.600** page faults, **20kB/s** avg total I/O during iterations.
`node -> python:` **55.289** page faults, **1.88kB/s** avg total I/O during iterations.

**~100 iterations per second, 300 iterations in total.**
`node -> python -> node :`  **151.445** page faults, **65MB/s** avg total I/O during iterations.
`python -> python -> python:` **6.070** page faults, **190kB/s** avg total I/O during iterations.
`node -> python :` **57.610** page faults, **19kB/s** avg total I/O during iterations.

**~100 iterations per second, 3000 iterations in total.**
`node -> python -> node :` **335.351** page faults, **62MB/s** avg total I/O during iterations.
`python -> python -> python:` **6.126** page faults, **190kB/s** avg total I/O during iterations.
`node -> python :` **27.294** page faults, **22kB/s** avg total I/O with 18kB/s to 800kB/s spikes.

I did my observations through Process Hacker and Windows Performance Monitor. When I don't send anything from python to node everything gets relatively calmer. 
I am pretty new in everything zmq but I/O rate, marked as "other bytes" is extremely high compared to everything else working in my system.

What is causing this ? **Is it a bug or is it about how I implement zmq to my code ?**

Here is my code.
[bridge.js](https://gist.github.com/shotwn/ea2fbc72cd8bb6192c9551aae231ccf7)
[test.bridge.js](https://gist.github.com/shotwn/8a46005d0e3cf83a1b38284da7954bc8)

It is maybe not very relevant but python part.
[bridge.py](https://gist.github.com/shotwn/1cbf82c9b417760d4d8c4f882ab4efd6)
[test.rpc.py](https://gist.github.com/shotwn/60ddb82684534c2dfdf63c01c04b9633)

**Comment by rolftimmermans** [comment]
Recently we have released 6.0 beta. It features a [new API](https://github.com/zeromq/zeromq.js#examples) that addresses some [fundamental issues](https://github.com/zeromq/zeromq.js/issues/189) with the previous API and also addresses a number of stability bugs. To make upgrading easier it includes a [compatibility layer](https://github.com/zeromq/zeromq.js#compatibility-layer-for-version-45) with versions 4.x/5.x. It would be great if you could give the latest version a spin to see if this solves this particular issue. If you run into any problems with it, feel free to report it here or in a new issue.
