### ISSUE TITLE
Monitoring doesn't report identity properly (I think)

### ISSUE THREAD

**Issue by ddibiase** [zeromq/zeromq.js#216]
I'm using the latest build and adding an event listening to 'accept' as such:

    socket.on('accept', function(...args) { console.log('accept, endpoint:', args);});

The event trigger this output:

    accept [ 37, 'tcp://0.0.0.0:5559', undefined ]

I'm using a DEALER -> ROUTER however the issue seems to be common amongst all socket types.

Shouldn't the first parameter be the specified identify of the socket since it's defined before .connect is called? ie.

    this.socket = zmq.socket('dealer');
    this.socket.identity = this.id;
    this.socket.connect(
      `tcp://${this.config.socket.host}:${this.config.socket.port}`
    );

`this.id` is a string such as `resolver-83749`

I need to manage my socket connections and reference them for forwarding control purposes. If a socket connects and disconnects I need to be able to map the connection.

Thanks and happy holidays everyone!

**Comment by rolftimmermans** [comment]
You probably want to use `ZMQ_PROBE_ROUTER` or `socket.probeRouter` in the new API (as of version 6.0). This will cause an empty message with the routing id prefixed when a new client is connected. That appears to be the recommended ZMQ-way to deal with this.
