### ISSUE TITLE
Question regarding sending a Uint8Array

### ISSUE THREAD

**Issue by xgdgsc** [zeromq/zeromq.js#219]
I' m trying to use zeromq.js to send a flatbuffers buffer to a python process, like the [tutorial](https://google.github.io/flatbuffers/flatbuffers_guide_tutorial.html) 
```
......
var buf = builder.asUint8Array()
this.pubSock.send(['ChannelName', buf])
```
I get error like:
```
struct.error: unpack_from requires a buffer of at least 4 bytes
```
when unpacking in Python. I' m not sure if it is the problem of the js side or python side. I want to ask would sending a Uint8Array like this work?

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release supports `Uint8Array` messages. It would be great if you could try it out! The new version has a new API that addresses some fundamental issues with the previous API, but it does include a compatibility layer that should make upgrading easier. See #189 for the reasoning behind the new API. If you run into any problems feel free to report it here or in a new issue.
