### ISSUE TITLE
Question: tracking socket identity

### ISSUE THREAD

**Issue by ddibiase** [zeromq/zeromq.js#220]
I'm wondering if there's a way to track a socket connect and disconnect. I need to manage the state of the socket connection and having trouble determining which value to depend on.

For example I see when monitoring is enabled the accept and disconnect events return an FD. However the identity of the socket isn't made available. Within the messages event there's no FD but there's an identity propagated.

Is there a way to lookup the FDs identity? That would be an ideal way of solving this problem.

The docs aren't super clear about this process or perhaps I've just misread them. Thanks in advance.

**Comment by rolftimmermans** [comment]
See #216 for the recommended way to deal with this. If you run into any problems please feel free to open a new issue!
