### ISSUE TITLE
Question: using RCVMORE - receiving multiple messages

### ISSUE THREAD

**Issue by lzkelley** [zeromq/zeromq.js#221]
I can't find any documentation on how to receive multiple messages in the asynchronous paradigm of zeromq.js.  In python, it's simple (using `pyzmq`):

```
more = True
while more:
    print(sock.recv())
    more = sock.getsockopt(zmq.RCVMORE)
```

But how would we get the same result in `zeromq.js`?  I.e. is there something analogous to:

```
sock.on('message', function(msg1){
  console.log("got message 1:", msg1)
  // But `msg1.RCV_MORE` isn't actually a thing...
  if (msg1.RCV_MORE) {
    sock.on('message', function(msg2){
      console.log("got message 2:", msg2)
    });
  }
});
```

----

I'm new to ZeroMQ[.js], javascript, and asynchronous programming in general: apologies if I'm missing something obvious!

**Comment by rgbkrk** [comment]
This is somewhat of a non-answer, so bear with me here. You're _already_ getting multiple messages. Every time a message comes in, your callback to `sock.on` is called.

```
sock.on('message', function(msg) {
  // both msg1 and msg2 will come through here, as will any other message
  // ...you also can't guarantee order 100% if this is a PUB/SUB socket
  if(someCheck(message)) {
    // do stuff
  } else {
    // do other stuff
  }
}
```

How you handle async is up to you (yes, I'll give more pointers if you want them). If you want a friendly book on this, check out [Node.js 8 the Right Way](https://pragprog.com/book/jwnode2/node-js-8-the-right-way). There's even a section on zeromq.js inside.

**Comment by lzkelley** [comment]
Interesting!  Thanks @rgbkrk (nice last-name spelling, btw).  So I guess I could piece together msg1 and msg2, then process them once I see that they're both there, and in the right order, etc.  So is there no use for the RCVMORE flag in `ZeroMQ.js`?  Or is there a *synchronous* alternative to the `sock.on()` paradigm?

**Comment by rgbkrk** [comment]
Based on a limited skimming of the C binding that zeromq.js uses, there is usage of `RCVMORE`, which appears to just keep requesting for more messages:

https://github.com/zeromq/zeromq.js/blob/9aed7a763cd9ef1f3848cbd4719bf79d11741521/binding.cc#L1219-L1222

So, perhaps this happens transparently in the background for each message. When do you end up using `RCV_MORE`?

**Comment by lzkelley** [comment]
I was using it (`RCVMORE`) on the python side (`pyzmq`) to get a sequence of separate messages, but my confusion was whether it could be used in the javascript (`zeromq.js`) --- it sounds like it can't.  I think I understand how to get around that [1], but it seems a little strange (if I understand correctly) that there *isn't a way* to perform *synchronous* messaging on the js side.

[1] For example, I could piece together a 'package' array, and just check to see when each piece has been received.  Or, alternatively, I can just shove everything I need into a single message (this is what I'll likely do---for now, at least) and parse it appropriately.

**Comment by lzkelley** [comment]
Gotcha.  Thanks @rgbkrk, this has been very helpful!

**Comment by minrk** [comment]
Greeting, fellow Kelleys!

This is some tricky stuff in zeromq, and why I've tried (mostly unsuccessfully) to separate the two things called 'messages' in zeromq. zmq messages are fundamentally multipart (even if sometimes the number of parts is 1). I prefer to call each segment of a message a **frame**, and each delivery unit a **message**. pyzmq zero-copy classes reflect this.  Using these terms, `zmq_send` doesn't send a *message*, it sends a *frame*. Same for `zmq_recv`. RCVMORE indicates whether the latest frame you received is the last part of a message. Because zmq messages are delivered atomically, if RCVMORE is True, you are guaranteed that the next frame is ready and waiting in memory to be received.

In pyzmq, I recommend *exclusively* using the `send/recv_multipart` methods, which ensure whole messages are always delivered as a unit (a list of frames). zeromq.js has elected to make this the *only* way to recv messages, which I think is the right call. You never want to recv part of a message without recving the rest immediately.

**Comment by lzkelley** [comment]
This officially qualifies as a kelley-fest.  @minrk thanks for your comments, I definitely follow the reasoning, but I don't entirely understand in practice.

If python performs a handful of `sock.send(..., RCVMORE)` then a `sock.send(...)`, are you saying that the javascript `sock.on('message', function(msg) { ... });` *will only be called* once `msg` is actually an array of all of the messages?

**Comment by minrk** [comment]
>  will only be called once msg is actually an array of all of the messages?

Close. The callback will only be called when all frames are available, but `msg` is always the first frame. If you are sending multipart messages, then the callback will be called with multiple arguments. Each frame is added as a positional argument, like so:

```javascript
sock.on('message', function (frame0, frame1, frame2, ...) {...});
```

So if you register a message callback that only takes one argument, you are saying that you are only interested in the first frame of any message, and all other frames should be discarded (they are still passed to your function, your callback just isn't using them).

An example that logs all multi-part messages, regardless of length via the `arguments` object:

```javascript
sock.on("message", function() {
  var frames = Array.prototype.map.call(arguments, frame => frame.toString());
  console.log("work:", frames);
});

**Comment by lzkelley** [comment]
Ah fantastic!  I see.  This should really be in the documentation somewhere... I'll try to put in a docs PR sometime soon.
