### ISSUE TITLE
Trouble with installing and understanding ZMQ 

### ISSUE THREAD

**Issue by truongdqse03303** [zeromq/zeromq.js#223]
Hi im newbie with ZeroMQ and network system. 
Case 1: 
Following the doc with fresh centos i did this step:
1. Install 'Development Tools' include Gcc 4.8.5
install python 2.7
nodejs 8.9.4
2. npm i zeromq (?)
- if i install outside the repository it's doing nothing.
- if i install inside the repo, i have 
> Refusing to install package with name "zeromq" under a package
> npm ERR! also called "zeromq". Did you name your project the same

so i skip this.
3. npm i 
i have 
> npm WARN lifecycle zeromq@4.6.0~install: cannot run in wd %s %s (wd=%s) zeromq@4.6.0 node 
> scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild) /root/zeromq.js
> added 406 packages in 9.272s

after that i run npm test and i have the error: 
> Error: Cannot find module '../build/Release/zmq.node'

Case 2: 
Without any install, set up ./configuration 
follow https://github.com/jimbojw/node-zmq-talk
i just run npm i zeromq and everything work fine 

so what am i doing wrong or miss understanding something ?
Please help me with this. Thanks!

**Comment by truongdqse03303** [comment]
Can anyone help me run this project ??
Thanks!!

**Comment by n-riesco** [comment]
I'm going to assume you want to create an `npm` package that uses `zeromq`.

Here's a quick example:
```
$ mkdir my-package
$ cd my-package
$ npm init
$ npm install --save zeromq
```

create a file named `index.js` with the contents:
```js
var zmq = require('zeromq');

var rep = zmq.socket('rep')
  , req = zmq.socket('req');

rep.on('message', function(msg){
    console.log(msg.toString());
    rep.send('world');
});

rep.bind('inproc://stuffreqrep', function (error) {
    if (error) throw error;
    req.connect('inproc://stuffreqrep');
    req.send('hello');
    req.on('message', function(msg){
        console.log(msg.toString());
        rep.close();
        req.close();
        process.exit(0);
    });
});
```

and run it:
```
$ node index.js
```

**Comment by truongdqse03303** [comment]
Hi @n-riesco 
It's exactly what i do in case 2. It's run ok but i want to run the npm test on this github repo. Thanks btw.

Problems solve, just run addition `prebuild --all --strip`

**Comment by n-riesco** [comment]
@truongdqse03303 

> Problems solve, just run addition prebuild --all --strip

If you make sure to request `zeromq`  (instead of `zmq`), you won't need to install `gcc `and `python 2.7`, and you won't need `prebuild`.

**Comment by truongdqse03303** [comment]
hi @n-riesco 
I do know that run `npm install zeromq` then create a js file with 'require('zeromq')' still run normal, follow the https://github.com/jimbojw/node-zmq-talk
But why the doc https://github.com/zeromq/zeromq.js#installation---from-source said i have to build from source.
What is the diffirent.
Thank you for reply me~

**Comment by n-riesco** [comment]
@truongdqse03303 

`zeromq` provides prebuilt binaries for `linux`, `mac` and `windows` 64-bits (so that most users don't need to install a compiler, python 2.7, and build from source).

If your computer is 32 bit, or is running another OS, then you need to build from source, and follow the instructions under https://github.com/zeromq/zeromq.js#installation---from-source .

**Comment by rgbkrk** [comment]
It looks like those slides / readme from Jimbo are out of date
