### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by asterx** [zeromq/zeromq.js#232]
I'd love to see these changes published:
https://github.com/zeromq/zeromq.js/blob/master/lib/index.js#L418-L420

Thanks :)

**Comment by asterx** [comment]
\cc @rgbkrk

**Comment by rgbkrk** [comment]
We'll work on getting a release out in the next couple days. I've been hoping for resolution to https://github.com/zeromq/zeromq.js/pull/218 first.

**Comment by asterx** [comment]
Thanks for info!

**Comment by asterx** [comment]
ping ?

**Comment by rgbkrk** [comment]
Since we haven't had resolution on #218 yet, do you want to tackle figuring out the memory leak?

**Comment by rolftimmermans** [comment]
Releases have been made!
