### ISSUE TITLE
ZMQ_RCVTIMEO - how to catch the error EAGAIN?

### ISSUE THREAD

**Issue by crholliday** [zeromq/zeromq.js#234]
If I set the following: `sock.setsockopt(zmq.ZMQ_RCVTIMEO, 5000)` I would expect to get an `EAGAIN` error when the receive timeout takes place. 

According to these docs:
```ZMQ_RCVTIMEO: Maximum time before a socket operation returns with EAGAIN
Retrieve the timeout for recv operation on the socket. If the value is 0, zmq_recv(3) will return immediately, with a EAGAIN error if there is no message to receive. If the value is -1, it will block until a message is available. For all other values, it will wait for a message ```

Any example or hints on how to catch that error? It does not appear to get caught in any of the standard zmq events... unless I don't know what I am doing.

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release addresses this problem (and many similar issues) with a new API that addresses some fundamental issues with the previous API. Receiving messages from a socket can now fail if a timeout is configured, for example. It would be great if you could try it out! See #189 for more background behind the new API. If you run into any problems feel free to report it here or in a new issue.
