### ISSUE TITLE
Install fails on OSX due to prebuild-install version

### ISSUE THREAD

**Issue by dmwelch** [zeromq/zeromq.js#237]
```sh
$ node --version
v8.6.0
$ npm --version
5.3.0
$ npm install -g zeromq
npm ERR! code ETARGET
npm ERR! notarget No matching version found for prebuild-install@^2.2.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'zeromq'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dwelc/.npm/_logs/2018-03-09T01_41_21_064Z-debug.log
```

Log file: 

> 0 info it worked if it ends with ok
1 verbose cli [ '/Users/dwelc/.nvm/versions/node/v8.6.0/bin/node',
1 verbose cli   '/Users/dwelc/.nvm/versions/node/v8.6.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'zeromq' ]
2 info using npm@5.3.0
3 info using node@v8.6.0
4 verbose npm-session 54752eeb9561afac
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://npm.platforms.engineering/zeromq 458ms
8 http fetch GET 200 https://npm.platforms.engineering/z/zeromq/_attachments/zeromq-4.6.0.tgz 11ms (from cache)
9 silly pacote tag manifest for zeromq@latest fetched in 535ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 silly install loadShrinkwrap
13 silly install loadAllDepsIntoIdealTree
14 silly resolveWithNewModule zeromq@4.6.0 checking installable status
15 http fetch GET 304 https://npm.platforms.engineering/nan 126ms (from cache)
16 silly pacote range manifest for nan@^2.6.2 fetched in 133ms
17 silly resolveWithNewModule nan@2.6.2 checking installable status
18 http fetch GET 304 https://npm.platforms.engineering/prebuild-install 190ms (from cache)
19 silly registry:manifest no matching version for prebuild-install@^2.2.2 in the cache. Forcing revalidation
20 http fetch GET 304 https://npm.platforms.engineering/prebuild-install 108ms (from cache)
21 silly fetchPackageMetaData error for prebuild-install@^2.2.2 No matching version found for prebuild-install@^2.2.2
22 verbose type range
23 verbose stack prebuild-install: No matching version found for prebuild-install@^2.2.2
23 verbose stack     at pickManifest (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:61:11)
23 verbose stack     at fetchPackument.then.packument (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:51:18)
23 verbose stack     at tryCatcher (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
23 verbose stack     at Promise._settlePromiseFromHandler (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
23 verbose stack     at Promise._settlePromise (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
23 verbose stack     at Promise._settlePromise0 (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
23 verbose stack     at Promise._settlePromises (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
23 verbose stack     at Async._drainQueue (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
23 verbose stack     at Async._drainQueues (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
23 verbose stack     at Immediate.Async.drainQueues (/Users/dwelc/.nvm/versions/node/v8.6.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
23 verbose stack     at runCallback (timers.js:781:20)
23 verbose stack     at tryOnImmediate (timers.js:743:5)
23 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
24 verbose cwd /Users/dwelc/src
25 verbose Darwin 16.7.0
26 verbose argv "/Users/dwelc/.nvm/versions/node/v8.6.0/bin/node" "/Users/dwelc/.nvm/versions/node/v8.6.0/bin/npm" "install" "-g" "zeromq"
27 verbose node v8.6.0
28 verbose npm  v5.3.0
29 error code ETARGET
30 error notarget No matching version found for prebuild-install@^2.2.2
31 error notarget In most cases you or one of your dependencies are requesting
31 error notarget a package version that doesn't exist.
31 error notarget
31 error notarget It was specified as a dependency of 'zeromq'
32 verbose exit [ 1, true ]

**Comment by dmwelch** [comment]
@lgeiger Any idea what's going on here?

**Comment by lgeiger** [comment]
Looks like npm was down. Does it work now?

**Comment by dmwelch** [comment]
Same failure this evening.  I can install other packages from npm...
