### ISSUE TITLE
setting and detecting connect timeout

### ISSUE THREAD

**Issue by fr6nco** [zeromq/zeromq.js#240]
Hi, I have no idea what I'm doing wrong, but no events get emitted at all no matter what I'm trying to do. I need to detect unsuccessful connect towards a server in PAIR mode.

Could you please take a quick peek on this snippet? If Im connecting to an existing endpoint I receive the helloworld message, but the event is not fired and I cant see the log. If Im connecting to a non existing endpoint I see no log messages at all. 

`
        
        console.log('Trying to establish zMQ connection to ' + 'tcp://${this.controllerIP}:${this.controllerPort}');

        this.zmq_sock = zeromq.socket('pair');

        this.zmq_sock.on('connect', (socket) => {
            console.log(`Succesfully connected to messaging intereface to controller on tcp://${this.controllerIP}:${this.controllerPort}`);
        });

        this.zmq_sock.on('connect_delay', (msg) => {
            console.log('delay');
            console.log(msg);
        });

        this.zmq_sock.on('connect_retry', (msg) => {
            console.log('connect retry');
            console.log(msg);
        });

        this.zmq_sock.on('error', (err) => {
            console.error("error occured with the ZMQ socket "+ err.toString());
        });

        this.zmq_sock.on('message', (msg) => {
            console.log('Message received on ZMQ sock ' + msg);
        });

        this.zmq_sock.connect(`tcp://${this.controllerIP}:${this.controllerPort}`);
        this.zmq_sock.send('helloworld');
`

**Comment by fr6nco** [comment]
Ok I could figure out the issue. 

        this.zmq_sock.monitor();

needs to be called before subscribing to events. This thing should be better documented imho.

**Comment by roccomuso** [comment]
And when disconnecting remember to call `socket.unmonitor()`
