### ISSUE TITLE
"zmq.node" is not a valid DLL or Win32 application on Windows with Electron

### ISSUE THREAD

**Issue by ndrantotiana** [zeromq/zeromq.js#242]
Hello.
I'm using [bozon](https://github.com/railsware/bozon) to scaffold an Electron project.
I tried to add zeromq@4.6.0 with the generated Electron project (Electron version is 1.8.4) and while launching (not yet packaging for now) it on OS X, it is working but on Windows, it won't works telling "**A dynamic link library (DLL) initialization routine failed**" for "**node_modules\zeromq\build\Release\zmq.node**".
I have already execute "**npm rebuild zeromq --runtime=electron --target=1.8.4**" before running the app but it's not working.
Any assistance would be welcome.

**Comment by ndrantotiana** [comment]
I tried using a basic electron app without any kind of scaffolding tools to create it, I still received the same error.
I think it is the fact that the build of zeromq on Windows for Electron 1.8.4 is not yet compatible. With Electron 1.7.x, I receive "The module '<path to zmq.node>' was compiled against a different Node.js version using NODE_MODULE_VERSION 54. This version of Node.js requires NODE_MODULE_VERSION 57. Please try re-compiling or re-installing the module...."

**Comment by ndrantotiana** [comment]
I re-created my project from scratch and now on Windows, I get this:

> App threw an error during load
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\test\node_modules\zeromq\build\Release\zmq.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\test\node_modules\zeromq\lib\index.js:6:11)
    at Object.<anonymous> (C:\test\node_modules\zeromq\lib\index.js:848:3)

and that even after rebuilding "zeromq" with `npm rebuild zeromq --runtime=electron --target=1.8.4`.
I noticed that when rebuilding it, I still hae some linking warnings:

> libzmq.lib(address.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(address.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(client.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(client.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(clock.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(clock.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(ctx.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(ctx.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(curve_client.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(curve_client.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(curve_server.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(curve_server.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(dealer.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(dealer.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(decoder_allocators.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(decoder_allocators.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(dgram.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(dgram.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(dish.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(dish.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(dist.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(dist.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(err.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(err.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(fq.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(fq.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(gather.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(gather.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(io_object.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(io_object.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(io_thread.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(io_thread.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(ip.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(ip.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(lb.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(lb.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(mailbox.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(mailbox.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(mailbox_safe.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(mailbox_safe.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(mechanism.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(mechanism.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(metadata.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(metadata.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(msg.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(msg.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(mtrie.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(mtrie.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(null_mechanism.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(null_mechanism.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(object.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(object.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(options.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(options.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(own.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(own.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(pair.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(pair.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(pipe.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(pipe.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(plain_client.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(plain_client.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(plain_server.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(plain_server.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(poller_base.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(poller_base.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(precompiled.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(precompiled.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(proxy.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(proxy.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(pub.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(pub.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(pull.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(pull.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(push.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(push.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(radio.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(radio.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(random.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(random.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(raw_decoder.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(raw_decoder.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(raw_encoder.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(raw_encoder.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(reaper.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(reaper.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(rep.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(rep.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(req.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(req.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(router.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(router.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(scatter.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(scatter.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(select.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(select.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(server.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(server.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(session_base.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(session_base.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(signaler.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(signaler.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(socket_base.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(socket_base.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(socket_poller.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(socket_poller.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(socks.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(socks.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(socks_connecter.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(socks_connecter.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(stream.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(stream.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(stream_engine.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(stream_engine.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(sub.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(sub.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(tcp.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(tcp.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(tcp_address.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(tcp_address.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(tcp_connecter.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(tcp_connecter.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(tcp_listener.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(tcp_listener.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(thread.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(thread.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(timers.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(timers.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(trie.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(trie.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(tweetnacl.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(tweetnacl.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(udp_address.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(udp_address.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(udp_engine.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(udp_engine.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(v1_decoder.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(v1_decoder.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(v1_encoder.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(v1_encoder.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(v2_decoder.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(v2_decoder.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(v2_encoder.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(v2_encoder.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(xpub.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(xpub.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(xsub.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(xsub.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(zmq.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(zmq.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]
libzmq.lib(zmq_utils.obj) : warning LNK4099: PDB 'libzmq.pdb' was not found with 'libzmq.lib(zmq_utils.obj)' or at 'C:\test\node_modules\zeromq\build\Release\libzmq.pdb'; linking object as if no debug info [C:\test\node_modules\zeromq\build\zmq.vcxproj]

Anyone could help me please?

Thank you in advance.

**Comment by ndrantotiana** [comment]
I found the main issue but I don't know how to solve it yet. It is the fact that **prebuild** module doesn't found a module in **zmq.node** file when trying to require it. I found that **prebuild** adds a "**\\\\?\\**" before the path where the "zmq.node" is.
I'm wondering if it is a bug of "prebuild" or a bug of the prebuilt/generated "zmq.node" file for electron 1.8.x. Note that there doesn't seem any issues with prebuilt version for electron 1.7.x

**Comment by ndrantotiana** [comment]
It is now fine with [prebuild-install 2.5.3](https://github.com/prebuild/prebuild-install/issues/72)

**Comment by n-riesco** [comment]
@ndrantotiana Thank you for reporting back here!

**Comment by crifan** [comment]
Seems is same error, so please refer my answer in this post:

[A dynamic link library (DLL) initialization routine failed](https://github.com/0rpc/zerorpc-node/issues/99#issuecomment-576198504)

And the solution is:

Change
`node\_modules\\zerorpc\\node\_modules\\zeromq\\lib\\index.js`
from
```js
var EventEmitter = require('events').EventEmitter
  , zmq = require('../build/Release/zmq.node')
  , util = require('util');
```
to:

```js
var EventEmitter = require('events').EventEmitter

let path = require('path')
let zmqNodePath = path.join("..", "build", "Release", "zmq.node")
var zmq = require(zmqNodePath)

var util = require('util')
```
