### ISSUE TITLE
Configure authorized keys

### ISSUE THREAD

**Issue by hueneburg** [zeromq/zeromq.js#244]
We are currently trying to use ZeroMQ with Java and Node.JS. We want to use the [Ironhouse Pattern](http://hintjens.com/blog:49#toc6). In Java I use a ZAuth object and apply it to a context. Furthermore, I add a directory path that contains the authorized public keys (`zauth.configureCurve(String)`). But is there a similar approach for this package?

**Comment by rolftimmermans** [comment]
While I'm not familiar with the Ironhouse pattern, it seems to be based on CURVE security, which you can use with this library. The tests are probably the clearest example how to use the API:
https://github.com/zeromq/zeromq.js/blob/master/test/unit/socket-curve-send-receive-test.ts for 6.x
https://github.com/zeromq/zeromq.js/blob/5.x/test/socket.zap.js for 4.x/5.x

Hope this helps! I'm closing this but please feel free to open a new issue if you run into any problems.
