### ISSUE TITLE
Problem with socket.subscribe()

### ISSUE THREAD

**Issue by stefsz** [zeromq/zeromq.js#248]
The 0MQ spec. says that the argument to ZMQ_SUBSCRIBE in zmq_setsockopt() is to be interpreted as "binary data", and not as "character string", as your binding does.

To exemplify, the following code

var zmq = require('zeromq'),
    sock = zmq.socket('sub'),
    url = 'tcp://127.0.0.1:8888';

var msg_prefix = new Uint8Array('M', 'S', 'G', 0, 1, 2, 3, 4);

sock.connect(url);
sock.subscribe(msg_prefix);
console.log('Subscriber connected to ' + url);

has the same effect as if the "subscribe" call was:

sock.subscribe("MSG");

and that's wrong! The garbage following the '\0' in the Uint8Array should also be passed to the zmq_setsockopt() call, and used for filtering out messages that do not contain it.

It causes me a lot of trouble having to redesign my stuff because of that...

**Comment by ronkorving** [comment]
I'm sorry to say that this is how subscribe is supposed to work. From the manual:

>  An empty option_value of length zero shall subscribe to all incoming messages. A non-empty option_value shall subscribe to all messages beginning with the specified prefix.

Source: http://api.zeromq.org/4-1:zmq-setsockopt

**Comment by stefsz** [comment]
I'm sorry to say this is how you interpret it. The 0MQ guys could have
definitely done a better job documenting it, but still (from the same
document):
Option value type binary data
Option value unit N/A
Default value N/A
Applicable socket types ZMQ_SUB
the option value type is "binary data", which I interpret as possibly
containing zeros, which should not be interpreted as prefix terminators.
There's also an option length for that! Conversely, the option type should
have read "character string".

Maybe this is not what the 0MQ guys have intended, but this is how I
interpret what they have written in the documentation.

Thank you for your answer,
Stefan Szabo

**Comment by stefsz** [comment]
I can also confirm that my assumption is correct after testing it with C
code.
HTH,
Stefan

**Comment by ronkorving** [comment]
Feel free to reopen, as I don't think this is settled yet. If what you describe is true, that would definitely be a bug. Could you perhaps add a test to https://github.com/zeromq/zeromq.js/blob/master/test/socket.pub-sub.js that proves the point and make a PR with that?

**Comment by xelinorg** [comment]
It looks like this one should be closed. 
The library works correctly and there is not any bug I can see at the moment around issues having to do with the arguments passed to the subscribe method of the sub socket.
I have added to more unit tests in socket.pub-sub to make clearer the way it expected to work.

@stefsz if you console log what is the msg_prefix you are talking about, you will see that is not what you wanted to do... I believe :)
The test might help you with your accomplishment or even understanding of binary data on js world as there a couple of things messed up here.

Hope it helps and I am going to look a bit more the test branch of the code as there are some not major issues with tcp ports not closing when tests are done. Could be an improvement for testing.

the pr is https://github.com/zeromq/zeromq.js/pull/258

**Comment by stefsz** [comment]
Hi,
If there's no fix as a result of that, then I'd say the problem still
exists. I have not yet the time to write myself the test to prove it, other
than what I have already submitted.
But please, do close it, and I will submit another one when the time comes.
Thanks,
Stefan

**Comment by xelinorg** [comment]
@stefsz to prove what?
I am telling you that what you are demonstrating is not standing. If you execute the line below you will understand what I am talking about. 

This is wrong relatively to the logic you expose with your example.
var msg_prefix = new Uint8Array('M', 'S', 'G', 0, 1, 2, 3, 4); 

To see what the msg_prefix is.
console.log(msg_prefix) 


the sock.subscribe(msg_prefix) call subscribes to an empty Uint8Array(8-bit unsigned integer array) and this is because 'M' is not an integer in the range. If you do this
var msg_prefix = new Uint8Array(3)
console.log(msg_prefix)

you will get an array with length of three, filled with zeros.

I hope you get my points

Thanks for coming back to this :)

ale3

**Comment by stefsz** [comment]
Oh! I see your point now. Thanks for taking your time with me. I'll
re-evaluate my code and post the results here.
Cheers,
SSz

**Comment by lgeiger** [comment]
Closed by #258
