### ISSUE TITLE
The ZMQ_CONFLATE option is missing

### ISSUE THREAD

**Issue by MaxAlex666** [zeromq/zeromq.js#254]
Why in the index.js file there is no definition of longOptions -> ZMQ_CONFLATE (54)?

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release supports this option. It would be great if you could try it out! The new version has a new API that addresses some fundamental issues with the previous API, but it does include a compatibility layer that should make upgrading easier. See #189 for the reasoning behind the new API. If you run into any problems feel free to report it here or in a new issue.
