### ISSUE TITLE
Problem installing zeromq.js behind proxy

### ISSUE THREAD

**Issue by krissdap** [zeromq/zeromq.js#260]
Dear ZeroMQ.js Maintainers,

I've tried to setup a new project using zeromq.js from behind a proxy and failed.
<code>
npm install zeromq
</code>

The error occurred during the "install" phase.
from <code>package.json</code>
<code>
"install": "node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)"
</code>

I'm aware of the issue #115 which you resolved by using <code>prebuild-install</code>.
This requires that my machine have <code>prebuild-install</code> installed globally, and working.

At least on my machine, fresh Ubuntu 18.04 + Node 8.10.0 + npm 3.5.2, the pbi does not work.
And switching to <code>scripts/preinstall.js</code> also failed because it does not support proxy.

**Comment by yanqd0** [comment]
I have the same issue.

My proxy is cntlm, and I have set `https_proxy` appropriately in the CLI environment and npm.
`export NODE_TLS_REJECT_UNAUTHORIZED=0` is also set to avoid the cert verification issue.

But not working yet.

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release includes all prebuilds within the NPM package, so this should no longer be an issue. It would be great if you could try it out! The new version has a new API that addresses some fundamental issues with the previous API, but it does include a compatibility layer that should make upgrading easier. See #189 for the reasoning behind the new API. If you run into any problems feel free to report it here or in a new issue.

**Comment by krissdap** [comment]
Thanks! I'll try it out and will update here when I have a change.
