### ISSUE TITLE
How to use zeromq.js in HTML page

### ISSUE THREAD

**Issue by jay11ca39** [zeromq/zeromq.js#264]
Hello All,

**It is not an issue, It is a query.** 
I am trying to create a web page [HTML] which will be creating the zeroMQ subscriber and will subscribe to a particular publisher. and will update the web page as and when it receive data from publisher.

Following is my code:

```
<html>
   <head>
      <title>Trying</title>
   </head>
   <body>
      <button type="button" id="button1">Start Subscriber!</button>
      <hr>
      <textarea style="width:500px;height: 400px" id="output"></textarea>

      <script> 
         var output = document.getElementById("output");
         var input = document.getElementById("button1");
         input.addEventListener("click", function () {
              var zmq = require('zeromq');
              var sock = zmq.socket('sub');
              sock.connect('tcp://127.0.0.1:3000');
              sock.subscribe('kitty cats');
              output.textContent = 'Actual subscriber connected to port 3000'  ---> it is not getting printing.
         });
        //callback     
        sock.on('message', function(topic, message) {
              var output = document.getElementById("output");
	      console.log('received a message related to:', topic.toString(), 'containing message:', message.toString());
              output.textContent = message.toString()
        }); 
      </script>

   </body>
</html>

```

As I am new to this. I am not sure whether i am going in right direction. 
Any help will be appreciable..

**Comment by rgbkrk** [comment]
You have to write a server side endpoint that will translate it to websockets, zeromq is a raw socket (TCP primarily). zeromq can not run directly in a web browser (unless it's in something like electron).

**Comment by ronkorving** [comment]
If you want something that will run in the browser, you're probably looking for something built on top of WebSockets. For example, https://www.npmjs.com/package/socket.io

**Comment by xemasiv** [comment]
You can also use plain WebSockets on the client-side and uWebSockets on the server-side, in-case you find socket.io quite bulky.

WebSockets @ MDN: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket
uWebSockets @ Github: https://github.com/uNetworking/uWebSockets
uWebSockets NodeJS bindings: https://github.com/uNetworking/uWebSockets-bindings/tree/master/nodejs

**Comment by yoelk** [comment]
@rgbkrk Can ZMQ be run directly on Electron? How come it can be done there and not in a browser?
Could you please share a link to information about how to ZMQ over electron? Thanks a lot!

**Comment by filips123** [comment]
@yoelk

Yes, it can. But you need to rebuild it as described in README file.

The reason it works in Electron is that TCP sockets are available in Node.js and Electron, but not in client-side JavaScript in the browser.

**Comment by rolftimmermans** [comment]
To add the the previous replies, there is support for [WebSockets transport](https://github.com/zeromq/libzmq/issues/3581) in progress. When it becomes available it will be supported in this library for server-side use. Usage in a browser will require [JS-based client](https://github.com/zeromq/jszmq).
