### ISSUE TITLE
Pass --zmq-external parameter in package.json

### ISSUE THREAD

**Issue by meisterlampe** [zeromq/zeromq.js#272]
Hi,

does anyone know how to add zmq as a dependency to package.json including the "zmq-external"-parameter?
When I install this bindings using ```npm install zeromq --zmq-external --save```, the parameter is not used in case someone else clones my repo and executes just ```npm i```.
(and unfortunately this fails on my ARM-Board)

Any help appreciated.
Thanks in advance :)

**Comment by meisterlampe** [comment]
Any ideas?

**Comment by meisterlampe** [comment]
Please help :)

**Comment by abhassaroha** [comment]
@meisterlampe  You can set the environment variable
npm_config_zmq_external="true"

When you do npm install, as usual, this package will be built with external zmq library.

**Comment by meisterlampe** [comment]
@abhassaroha Thanks for your response. I'll test that option.

**Comment by bxt** [comment]
Instead of setting the environment variable, you can also set it in a `.npmrc` file e.g. like this:

    echo "zmq_external=true" >> ~/.npmrc

to fix it for your user. Replace `~/.npmrc` with the path to the `.npmrc` in your project to set it for all users of your project.

**Comment by rolftimmermans** [comment]
> Instead of setting the environment variable, you can also set it in a `.npmrc` file e.g. like this:

This seems to me to be the appropriate solution for this problem.
