### ISSUE TITLE
Closing zeromq socket doesn't fire 'close' event

### ISSUE THREAD

**Issue by TitaneBoy** [zeromq/zeromq.js#273]
Hi..I'm trying to catch the 'close' event when we close the zeromq socket. But it seems that this event is never fired.

```
let socket = zeromq.socket(`pull`);
socket.on(`close`, (eventId) => {
  console.log('Closed successfully');
});

socket.bind('tcp://127.0.0.1:3000', (error) => {
  if (error) {
    console.log(error);
  }

  setTimeout(() => {
    socket.close();
  }, 5000);
});

```
I can catch 'message', 'accept', and 'listen' event properly, but I just can't catch the 'close' and (I guess) the 'close_error' event

Here is my package.json file:
```
{
  "name": "zero_mq",
  "version": "1.0.0",
  "description": "Test for ZeroMQ on NodeJS",
  "main": "index.js",
  "author": "Philou",
  "license": "MIT",
  "dependencies": {
    "@types/flatbuffers": "^1.9.0",
    "@types/zeromq": "^4.6.0",
    "flatbuffers": "^1.9.0",
    "zeromq": "^4.6.0"
  },
  "devDependencies": {
    "nodemon": "^1.14.12",
    "tslint": "^5.9.1",
    "tslint-eslint-rules": "^4.1.1",
    "typescript": "^2.7.1",
    "vrsource-tslint-rules": "^5.8.0"
  }
}

```

So technically, we can't know if the socket was closed successfully or not....

Thank you for your help;

**Comment by roccomuso** [comment]
having same issue and zmq prevent the node process from exiting.

**Comment by roccomuso** [comment]
Possible workaround:
```javascript
socket.close()
if (socket.closed) socket.emit('close')
```

**Comment by TitaneBoy** [comment]
@roccomuso 
Can you please explain me where you find the member "closed" in socket ? Cannot find him in the socket class..

Thanks

**Comment by roccomuso** [comment]
look in code.

btw there's also a unit test wrote for this:

```javascript

it('should close', function(){
 sock.closed.should.equal(false);
 sock.close();
 sock.closed.should.equal(true);
});
```

**Comment by rolftimmermans** [comment]
The close event (or `"end"` event in 6.x) can only be observed if the process is still running after the socket was closed. Here is an example with the new API in version 6.0 that demonstrates this:

```
import {Dealer} from "zeromq"

async function main() {
  const sock = new Dealer

  const logEvents = async () => {
    for await (const event of sock.events) {
      console.log(event)
    }
  }

  logEvents()
  sock.close()

  /* Required, or the socket will be closed just before process exit. */
  await new Promise(resolve => setTimeout(resolve, 1000))
}

main()
```

Please open a new issue if you run into any problems!
