### ISSUE TITLE
prebuild-install WARN install getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by ctlkkc** [zeromq/zeromq.js#287]
I am an organizational user, whose organization does not allow the machine to connect directly external address. My organization has an internal npm registry.

After installed prebuild, I tried to npm install -g zeromq but got the following error related to address not found, and it looked like an external address:

```
$ npm install -g zeromq

> zeromq@5.1.0 install /home/xxxxx/install/npm/node-linux-x64/lib/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443

{ Error: getaddrinfo ENOTFOUND github.com github.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'github.com',
  host: 'github.com',
  port: 443 }

...
[rolling back packages]
...

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


```
can you let me know how resolve this based on my organization's restriction?

Thanks

**Comment by pifpafpof-thomasL** [comment]
Edit your .npmrc and add:
proxy=http://your.ip.adress.proxy.:port/
https-proxy=http://your.ip.adress.proxy:8080

**Comment by ctlkkc** [comment]
> Edit your .npmrc and add:
> proxy=http://your.ip.adress.proxy.:port/
> https-proxy=http://your.ip.adress.proxy:8080

thanks for the reply. It seems not possible for my machine to get a proxy neither. 
Is there any other way to complete the installation?

**Comment by codebling** [comment]
How are you able to install NPM packages if you have no internet access? You should check with your organization's IT department. Zeromq.js needs to download and compile the Zeromq source using node-gyp in order to run. This is part of the `npm install` procedure and is a common thing for packages to do. You're having issues because of your organizational firewall, so again you should check with your IT department or ask on Stackoverflow. This is not an issue with zeromq.js

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release includes all prebuilds in the NPM package itself and no longer needs to downoad any files during install. It would be great if you could try it out! The new version has a new API that addresses some fundamental issues with the previous API, but it does include a compatibility layer that should make upgrading easier. See #189 for the reasoning behind the new API. If you run into any problems feel free to report it here or in a new issue.
