### ISSUE TITLE
Majordomo pattern

### ISSUE THREAD

**Issue by jarodium** [zeromq/zeromq.js#292]
Hello, I am building a ZMQ application with Majordomo pattern ( with slight changes ).
The client and broker are built in PHP but my worker is built in node and he is providing a "pseudoservice" on a webpage ( since majordomo is  about service discovery because of the broker )

I can pass jobs from the client to the broker and the broker passes it to the worker and it is working great.

The problem lies in the "topic" or "service" I want to pass to the worker.

script1.php issues the following $session->send("coffee", $request);
script2.php issues the following $session->send("tea", $request);

But on the zeromq.js side, I don't how to get "coffee" or "tea". I can only get the request in the 
```
function responder.on('message', function(request) {
...
}
```
I can solve this by sending the "coffee" or "tea" in the request, but I would like to keep as clean as possible.

Thank you
Pedro

**Comment by marekjaskot** [comment]
Hej,
you'r worker is a subcriber? check the example.. maybe this will work in on your issue

https://github.com/zeromq/zeromq.js/blob/master/examples/subber.js

**Comment by jarodium** [comment]
Hello,
No. The worker is a "service" provider. At best, it could be a pubber according to the examples.
The MDP is here http://zguide.zeromq.org/page:all#Service-Oriented-Reliable-Queuing-Majordomo-Pattern.

**Comment by pjanuario** [comment]
@jarodium have a look at this, it might be helpfull.
http://micro-toolkit.github.io/info/

**Comment by jarodium** [comment]
@pjanuario thanks. I will take a look at it

**Comment by rolftimmermans** [comment]
An (simplified) example majordomo service is now also included in the examples directory. Maybe it helps. https://github.com/zeromq/zeromq.js/tree/master/examples/majordomo

If you run into any specific problems, feel free to open a new issue!
