### ISSUE TITLE
zbeacon in nodejs?

### ISSUE THREAD

**Issue by eeyang92** [zeromq/zeromq.js#294]
Hi,

I'm wondering if there is an equivalent to the high-level c method [zbeacon](http://czmq.zeromq.org/czmq4-0:zbeacon)? I would like to use automatic node discovery in my project.

Understandably, it looks like this project is mainly focused on implementing the ZMQ Core API - are there efforts to bind the [high-level API](http://czmq.zeromq.org/czmq4-0:_start)?

**Comment by rgbkrk** [comment]
> are there efforts to bind the high-level API?

None that I'm aware of.

**Comment by eeyang92** [comment]
Okay thanks! I've never created JS bindings before, but I'll probably play around with it a bit.
