### ISSUE TITLE
npm install fails with win_delay_load_hook.cc on Windows 10

### ISSUE THREAD

**Issue by yashgt** [zeromq/zeromq.js#295]
[2019-01-04T06_51_56_041Z-debug.log](https://github.com/zeromq/zeromq.js/files/2726211/2019-01-04T06_51_56_041Z-debug.log)

Hi invoked E:\Projects>npm install zeromq@4.6.0
I get an error as:
c1xx : fatal error C1083: Cannot open source file: 'Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc': No such file or directory [E:\Projects\node_modules\zeromq\build\zmq.vcxproj]
cl : Command line warning D9027: source file 'NODE_TLS_REJECT_UNAUTHORIZED=0' ignored [E:\Projects\node_modules\zeromq\build\zmq.vcxproj]
cl : Command line warning D9024: unrecognized source file type '..\nan /I..\windows\include /Z7 /nologo /W3 /WX- /MP /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=zmq /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V
pdb /Gd /TP /wd4351 /wd4355 /wd4800 /wd4251 /wd4275 /wd4244 /wd4267 /errorReport:queue ..\binding.cc C:\Program', object file assumed [E:\Projects\node_modules\zeromq\build\zmq.vcxproj]
cl : Command line warning D9027: source file '..\nan /I..\windows\include /Z7 /nologo /W3 /WX- /MP /Ox /Ob2 /Oi /Ot /Oy /GL /D NODE_GYP_MODULE_NAME=zmq /D USING_UV_SHARED=1 /D USING_V8_SHARED=1 /D V8_DEPRECATION_WARN
1 /wd4355 /wd4800 /wd4251 /wd4275 /wd4244 /wd4267 /errorReport:queue ..\binding.cc C:\Program' ignored [E:\Projects\node_modules\zeromq\build\zmq.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Projects\node_modules\zeromq

**Comment by rgbkrk** [comment]
What version of node?

**Comment by yashgt** [comment]
node 10.14.1.

If this is not supported, please let me know which version is supported

**Comment by rgbkrk** [comment]
node 8 has prebuilds, I'm not sure how the support is for node 10

What do you think @lgeiger?

**Comment by yashgt** [comment]
Similar error with node 8.15.0. Attached the log.

**Comment by yashgt** [comment]
[2019-01-04T18_00_33_934Z-debug.log](https://github.com/zeromq/zeromq.js/files/2732674/2019-01-04T18_00_33_934Z-debug.log)
Attaching the error log with node 8.x.

**Comment by rgbkrk** [comment]
> 7 warn registry Using stale data from https://registry.npmjs.org/ because the host is inaccessible -- are you offline?
> 8 warn registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

Are you behind a proxy or something?

**Comment by 2livebrew** [comment]
@yashgt Have you solved your issue yet? I've been having the same issue with Node 10.13 on Windows 10. Every npm module with native code gives the same installation error. I've been having to compile and manually link modules as a workaround.

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release now includes all prebuilds in the NPM package so no download step is required, which might make this issue go away. It would be great if you could try it out! The new version has a [new API](https://github.com/zeromq/zeromq.js#examples) that addresses some fundamental issues with the previous API, but it does include a [compatibility layer](https://github.com/zeromq/zeromq.js#compatibility-layer-for-version-45) that should make upgrading easier. See #189 for the reasoning behind the new API.

If you run into any problems feel free to report it here or in a new issue.

**Comment by LegolasTai** [comment]
I have met this error due to cmd code page changed.
