### ISSUE TITLE
The specified module could not be found, with electron v4.0.0.

### ISSUE THREAD

**Issue by Agaspher20** [zeromq/zeromq.js#297]
Hi!
I have an issue with the latest release of zeroMQ.
When I try to run electron application I get the following error: "Error: The specified module could not be found."
I created a simple repository which [reproduces this issue](https://github.com/Agaspher20/electron-quick-start). This is a clone of electron-quick-start repository with two changes:
* zeromq added as a dependency and required in main.js
* electron-rebuild used to rebuild native node.js modules

This application successfully starts if you revert to electron 3.1.0 and fails in electron 4.0.1
If you remove the following string: `const {Socket, createSocket} = require('zeromq');` application will start in electron 4.

Best regards, Michael Naumenko

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
