### ISSUE TITLE
can't install zeromq on mac

### ISSUE THREAD

**Issue by MacGuffinLife** [zeromq/zeromq.js#307]
when I execute `npm install zeromq`I  got this : 
```
> zeromq@5.1.0 install /Users/macguffin/Usr/eletron_test/node_modules/zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install unexpected end of file
```
And it will stuck here forever until I press <C-c>

system: OSX 10.14.3
node: 10.15.1
npm:6.4.1

**Comment by willingc** [comment]
@MacGuffinLife I tried this with the same system version and node 11.6 and it seems to install. Perhaps try a different version of node and see if the same thing happens.

**Comment by MacGuffinLife** [comment]
I used to use node 11.6 but I got that "install no prebuilt binaries found ".I found the solution and I reinstall the node 10.15.and sometimes I will get some error.next time when I see the error I will paste here.

**Comment by willingc** [comment]
Thanks @MacGuffinLife. Please do paste the error and / or process to replicate.

**Comment by Petrie65** [comment]
I had the same problem - seems to be network related. I got on a different connection and it worked.

**Comment by willingc** [comment]
Thanks @Petrie65 for the additional information.

Closing the issue.
