### ISSUE TITLE
pull socket bind only working on localhost

### ISSUE THREAD

**Issue by awb99** [zeromq/zeromq.js#308]
I have found a very trivial bug. I am binding a push socket. Now When I connect a pull socket on localhost, then it works. However, if I connect to a remote machine, then it does not work. My remote server has an external ip address that is different to its local ip; but I dont think this is the issue, because when I have the same setup for binding pub sockets on the server it works, irrespecitve if all is localhost or if it is across the network. Any ideas?  I am running on Linux (Arch and debian).

**Comment by reqshark** [comment]
> My remote server has an external ip address that is different to its local ip

sounds like AWS.  i recommend using blissful ignorance, install the ip module and just do:

```js
require('ip').address() // this is your public bind ip
```

then connect to the "external ip address" even if what your binding to is different.

i like `require('ip').address()` so i dont have to consciously think about different internal ips for doing stuff on networks like that

**Comment by awb99** [comment]
You are right I am hosting on aws.
I tried binding to the public ip in the server.. But this fails.. Because
the server does not have that ip onnits network interface list.

So what you suggest is to bind on the local ip and then connecting from the
server the same socket to the public ip?
I didnt know that this is possible.

Many thanks!!

**Comment by reqshark** [comment]
hey no prob, yeah that's what i do on aws when the connection point is outside the aws zone/network

**Comment by rolftimmermans** [comment]
You probably need to bind to `0.0.0.0`, like this: `"tcp://0.0.0.0:12345"`. This should accept connections on any interface/IP and generally is recommended for public servers. Hope this helps! If you run into any problems feel free to report here or open a new issue.
