### ISSUE TITLE
Precompiled binaries for electron@4.1.0

### ISSUE THREAD

**Issue by sla89** [zeromq/zeromq.js#310]
Hello together! :)

Because the guys from electron changed their ABI version to 69 (https://github.com/electron/electron/pull/16687) and created a new electron release (4.1.0 - https://github.com/electron/electron/releases/tag/v4.1.0) there are no precompiled binaries for the latest stable zeromq.js version.

Is it possible to get precompiled binaries for zeromq.js v5.1.0? :)

Thank you in advance.

**Comment by sla89** [comment]
Any update on this or at least a comment from you about my question please? :/

**Comment by daniel0076** [comment]
@sla89 

I think this can be done by re-compiling it using [electron-rebuild](https://github.com/electron/electron-rebuild)

I installed the latest Electron, and run `./node_modules/.bin/electron-rebuild`
And it is compiled against my electron
Success on Electron 5.0.6 ABI 70

**Comment by lgeiger** [comment]
Sorry for the long wait.
I just re-triggered the release builds and [v5.1.0](https://github.com/zeromq/zeromq.js/releases/tag/v5.1.0) should now include prebuilts for the latest Electron and Node versions.
Feel free to reopen if you still have issues.
