### ISSUE TITLE
Subscriber and publisher send a lot of empty tcp packets

### ISSUE THREAD

**Issue by ilya-edrets** [zeromq/zeromq.js#312]
OS: Windows 10 Enterprise Version 1709
NodeJS version: 8.12.0
ZeroMQ: 5.1.0

I have simple pub\sub snippet:
```
var zmq = require("zeromq");

var sub = zmq.socket("sub");
var pub = zmq.socket("pub");

pub.bindSync("tcp://127.0.0.1:45678");
sub.connect("tcp://127.0.0.1:45678");
sub.subscribe("");

sub.on("message", () => {
});

pub.send("testMessage");
```
This pair produces ~250 empty tcp packets on each message from unknown ports.
This is a network activity from Sysinternals Process Monitor:
![Untitled](https://user-images.githubusercontent.com/7524899/54542597-2296f880-49ad-11e9-967c-86a54675514e.png)

**Comment by Zagidziran** [comment]
Hi dude, 
i had the same issue but its gone when i switched to zmq npm. Test it https://www.npmjs.com/package/zmq

**Comment by rolftimmermans** [comment]
I'm not sure how to interpret the screenshot, but this might better be posted in the [libzmq repo](https://github.com/zeromq/libzmq), given that this library does not do any I/O itself.

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0

**Comment by aminya** [comment]
No problem. I'll close the issue for now
