### ISSUE TITLE
Where is the list of precompiled binaries for electron?

### ISSUE THREAD

**Issue by cschar** [zeromq/zeromq.js#317]
In the README instructions we have:

`npm rebuild zeromq --runtime=electron --target=1.4.5`

Is there a list of available targets?
Currently electron is at 5.0.0

I'd like to know the most recent version of electron I can run zeromq with.

Thanks

**Comment by muhammad-saleh** [comment]
@cschar Could you please share where did you find it?

**Comment by cschar** [comment]
I couldn’t find it and decided to use python socketio and javascript socketio instead of zero mq as my message passing solution
