### ISSUE TITLE
Prebuilt binaries for electron@5.0.1

### ISSUE THREAD

**Issue by muhammad-saleh** [zeromq/zeromq.js#319]
Similar to #310 

Could we please get a prebuilt binaries for electron v5.0.1 ?

**Comment by lgeiger** [comment]
Sorry for the long wait.
I just re-triggered the release builds and [v5.1.0](https://github.com/zeromq/zeromq.js/releases/tag/v5.1.0) should now include prebuilts for the latest Electron and Node versions.
Feel free to reopen if you still have issues.

**Comment by muhammad-saleh** [comment]
@lgeiger I've tried now and this still doesn't work, Could you please check this when you have time?
I get version mismatch error in `NODE_MODULE_VERSION`
Thanks a lot.
