### ISSUE TITLE
electron: "npm install" builds for the wrong ABI version, electron-builder must be run afterwards

### ISSUE THREAD

**Issue by JPGygax68** [zeromq/zeromq.js#322]
I'm using the following command to install the bindings:
```
$ npm install --save zeromq --runtime=electron --target=5.0.0
```

This produces the following output (beginning only):
```
> zeromq@5.1.0 install D:\Projects\locsim\siemens\test-tool\node_modules\zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install No prebuilt binaries found (target=5.0.0 runtime=electron arch=x64 platform=win32)

Downloading libzmq for Windows
Download finished

D:\Projects\locsim\siemens\test-tool\node_modules\zeromq>if not defined npm_config_node_gyp (node "C:\Users\gygax\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\gygax\AppData\Roaming\nvm\v10.15.3\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
```

When I try to run my electron app with that, the Developer console shows: 
```
The module [...] was compiled against a different Node.js version using
NODE_MODULE_VERSION 47. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
To make it work, I need to do: `npx electron-rebuild`, after which my app runs as it should.

The docs do mention `electron-rebuild` as the way to go when using electron, but shouldn't the zeromq install script be able to handle this situation by itself? (Also, I had a superficial look at the source of electron-builder, but couldn't determine what exactly it does differently.)

Incidentally, the ABI version 47 that the `npm install` produces is listed in `node-abi` as the very first entry, corresponding to version 5.0.0 BUT OF of *node*, not electron. There may be a subtle bug there.

**Comment by rolftimmermans** [comment]
Could this be related to #338?

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
