### ISSUE TITLE
Is this supposed to work?

### ISSUE THREAD

**Issue by TanninOne** [zeromq/zeromq.js#325]
I apologize for the title but I'm not really sure how else to phrase this.

Following the examples I'm able to open a tcp socket on a fixed port, connect to it and exchange messages but I can't get anything beyond the trivial example to work or I can't figure out how to do it:
- None of the other events fire, .on("connect" / "listen" / "close" / "disconnect" or "..._error") never gets called.
- I can't seem to use ipc:// protocol (on windows)
- I don't see a way to use a non-fixed port. I tried to bind to "tcp://127.0.0.1:0" which seems to be a standard for "let the OS figure out a free port" but then I don't see a way to figure out which port it used. If it was a regular socket I would use getsockname but this is not wrapped by zeromq  and to call it directly I'd need a filedescriptor and when I call "sock._fd" - or any of the other properties - what I get back is "socket is busy" - which - why is that relevant for accessing socket properties?

Combined these last two make the use of this library quite limited to a "single server, many clients" scenario whereas zeromq is advertised as the universal "all your connection needs" solution.

So I guess apart from "are these supposed to work and if so, how?" I guess my question is: What's the status of this library in general? It has a version of 5.something so I would expect it to be stable and ready for productive use but it doesn't feel like it.

**Comment by reqshark** [comment]
> I don't see a way to use a non-fixed port

dont do that, there's no support for that. the connection string is very specific. try a known open port.

**Comment by TanninOne** [comment]
Not an option, I have to be able to open a variable/unknown number of connections so I'd either have to manually search for an unused port or not use this library.
Since the OS already supports binding to an unused port automatically (probably a _lot_ quicker and more reliable than if I did it manually) I don't see a valid reason to not support that basic functionality.

**Comment by rolftimmermans** [comment]
It is actually possible to use an OS-assigned port for TCP transports. You can use the following:

```
socket.bind("tcp://127.0.0.1:*")
```

Then retrieve the last endpoint of the socket (with `ZMQ_LAST_ENDPOINT` in 5.x or `socket.lastEndpoint` in 6.x). It should be a string such as `"tcp://0.0.0.0:52347"`

**Comment by rolftimmermans** [comment]
Regarding your other questions:
- IPC on Windows was added [only recently](https://github.com/zeromq/libzmq/pull/3717) in libzmq and I'm unsure what requirements there are to make it work. If it is included in a new release we'll try to make it work in ZeroMQ.js too.
- If you think there are any bugs regarding event triggering then it helps to have code that demonstrates the issue so we can reproduce and attempt to fix it. A lot is in flux right now so you might want to try again with the new 6.x beta release.

**Comment by rolftimmermans** [comment]
Closing this, please open a new issue for any problems you might encounter!
