### ISSUE TITLE
Adding support for using libzmq with ZMQ_BUILD_DRAFT_API enabled

### ISSUE THREAD

**Issue by evansmal** [zeromq/zeromq.js#326]
I was looking to add the libzmq ZMQ_CLIENT and ZMQ_SERVER socket types that are currently only availible if building with the draft API. 

The first step could be to build the bindings with support for the draft APIs by using the ZMQ_BUILD_DRAFT_API flag provided by `zmq.h`. It would then be possible to use these features when using the system headers with `--zmq-external`.  I don't think that enabling draft APIs will cause any backwards compatibility issues. 

How do the maintainers feel about this change?

**Comment by rolftimmermans** [comment]
As of 6.0.0-beta.1 the DRAFT APIs can be included by building with `--zmq-draft`.

For example: `npm install zeromq --build-from-source --zmq-draft`. Then you can import the draft sockets from `"zeromq/draft"`. Hope this helps! Please let us know how it's working out for you.
