### ISSUE TITLE
how to install/rebuilt zeromq for Electron-5.0.0 ?

### ISSUE THREAD

**Issue by dwasyluk** [zeromq/zeromq.js#330]
I am trying to use zmq with Electron 5.0.3. I've looked at #279 and #302. When i try the solution there I get the following error:

`npm rebuild zeromq --runtime=electron --target=5.0.3`

```
prebuild-install WARN install No prebuilt binaries found (target=5.0.3 runtime=electron arch=x64 platform=darwin)

Libzmq found, skipping rebuild.
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v5.0.3/node-v5.0.3-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/dwasyluk/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
gyp ERR! stack     at Request.emit (events.js:164:20)
gyp ERR! stack     at Request.onRequestResponse (/Users/dwasyluk/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/request/request.js:1068:10)
gyp ERR! stack     at ClientRequest.emit (events.js:159:13)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:550:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:439:20)
gyp ERR! stack     at TLSSocket.emit (events.js:159:13)
gyp ERR! stack     at addChunk (_stream_readable.js:265:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:252:11)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/Users/dwasyluk/.nvm/versions/node/v9.3.0/bin/node" "/Users/dwasyluk/.nvm/versions/node/v9.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

Is there a way to get prebuilt binaries for windows on Electron 5? Please let me know if more info is needed.

**Comment by dwasyluk** [comment]
I stepped back versions until rebuild worked:

`npm rebuild zeromq --runtime=electron --target=5.0.0`

Unfortunately it doesn't seem this addresses the issue as I still get this on Windows:

```
Uncaught Error: \\?\C:\Users\User\AppData\Local\Programs\Spark\resources\app.asar.unpacked\node_modules\zmqsocket\node_modules\zeromq\build\Release\zmq.node is not a valid Win32 application.
```

**Comment by dwasyluk** [comment]
We ended up downgraded to electron 3.1.11 to remediate this issue in the short term. Its not the ideal solution but it works. There may be higher versions that work as well but the prebuilt binaries for 3.1.11 work on both windows and mac.

`npm rebuild zeromq --runtime=electron --target=3.1.11`

**Comment by daniel0076** [comment]
I installed Electron 4.2.6 and use `electron-rebuild` to rebuild zeromq and it works

**Comment by daniel0076** [comment]
Hi @dwasyluk

I solved this by using [electron rebuild](https://github.com/electron/electron-rebuild)

Install `electron-rebuild` and install the latest Electron
Then run `./node_modules/.bin/electron-rebuild`, it will scan through the dependency tree and recompile the packages against the electron installed.

Successful with Electron 5.0.6

**Comment by axfelix** [comment]
`electron-build` and `npm rebuild zeromq` both run without errors, but on Electron 4+, I always get 

```
App threw an error during load
Error: The specified module could not be found.
\\?\C:\...\node_modules\zerorpc\node_modules\zeromq\build\Release\zmq.node
```

When trying to run an app with zeromq under Windows. If I move the actual zmq.node library I get a different error, which suggests it's not failing to find it...

**Comment by lgeiger** [comment]
Sorry for the long wait.
I just re-triggered the release builds and [v5.1.0](https://github.com/zeromq/zeromq.js/releases/tag/v5.1.0) should now include prebuilts for the latest Electron and Node versions.
Feel free to reopen if you still have issues.

**Comment by axfelix** [comment]
Thanks! I'm getting this from one of the builds that's supposed to be from 73:

```
Error: The module '/Users/axfelix/Documents/builds/radiam-agent/tray/node_modules/zerorpc/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by AlexSemenovIRL** [comment]
Im looking to solve this also
electron: 6.0.10
node:10.16.3
zeromq:5.1.0

**Comment by bfan1256** [comment]
Has anyone had any luck with more recent versions? Trying to get it to work with electron v20
