### ISSUE TITLE
Undefined symbol:  __asan_option_detect_stack_use_after_return

### ISSUE THREAD

**Issue by mateuszlewko** [zeromq/zeromq.js#331]
Hi All, 

I'm fighting with following issue for a few days and I have no idea what is causing this and how to fix that.
Basically I get following stack trace as soon as I start simple node app:
> internal/modules/cjs/loader.js:805
>  return process.dlopen(module, path.toNamespacedPath(filename));
>                          ^
> Error: /home/\<redacted>/node_modules/zeromq/build/Release/zmq.node: undefined symbol: __asan_option_detect_stack_use_after_return
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/\<redacted>/node_modules/zeromq/lib/index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

This happens on fresh project with only single dependency `"zeromq": "^5.1.0"`
I've tried with multiple nodejs versions (both v10, v11 & latest v12) but error is still present.
I'm on Arch linux. I have following packages installed `lib32-zeromq-4.3.1-1  zeromq-4.3.1-2`. Uninstalling them doesn't help. I've also tried `npm install zeromq --zmq-external` in order to link against installed libraries but the error is the same. I also have `node-gyp v5.0.0` installed. 
This zeromq library worked for me in the past on the same system, I have no idea what has changed since then (I definitely did npm upgrade a couple times). 

Just so it's clear, my `index.js`:
```
const zmq = require("zeromq");
console.log(`hello`);
```
Without `require` script runs fine.

My `package.json`:
```
{
  "name": "zeromq-test-proj",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "zeromq": "^5.1.0"
  }
}
```

Please help.

**Comment by mateuszlewko** [comment]
I found what was causing this problem. I had `-fsanitize=...` in my `CXXFLAGS` env variable. Doing just `unset CXXFLAGS` and then `npm i zeromq` fixed the issue!

**Comment by naveedkhan8067** [comment]
Hey, I am having the same issue with address sanitizer enabled. Was you able to resolve the issue by removing all CXXFLAGES? 
I don't want to disable address sanitizer as i need to run it with tests
