### ISSUE TITLE
rebuild issues on Mac

### ISSUE THREAD

**Issue by axfelix** [zeromq/zeromq.js#334]
# Issue description

I can't seem to rebuild this module properly. Running `npm rebuild libzmq` finishes immediately and doesn't appear to do anything (as I still get the `NODE_VERSION` mismatches afterward), and trying to do `electron-rebuild -v 5.0.8` throws

```
clang: error: no such file or directory: './Release/../../zmq/lib/libzmq.a'
```

# Environment

macOS 10.14.5

**Comment by PatrykMiszczak** [comment]
I've got this problem with node@14 and 16. On `v12.22.3` everything works fine

**Comment by AustEcon** [comment]
Ah! I am at least glad to find someone with the same issue as me. Anyone had any luck with node 14.17.x ? - I am also needing it for electron-rebuild

**Comment by AustEcon** [comment]
I have no idea why I was getting that error but it works when I bung zmq in with all of my other non-native downloads and use `electron-builder` in the postinstall script so I'm happy :)

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
