### ISSUE TITLE
Sending buffer object with bytes over >= 128 causes data to be corrupted.

### ISSUE THREAD

**Issue by frank-palmasani** [zeromq/zeromq.js#335]
Seems it has to do with the conversion to a string and then utf-8 encoding. 

A buffer, for example with the following data:

`<48 128 1>`

is changed to something like

`<48 262 191>`

The code in question is in node_modules/zeromq/lib/index.js:

```
OutBatch.prototype.append = function (buf, flags, cb) {

  // commented this out. causes errors in protobuf data. need to message 'npm zeromq' guys about this.
  // if (!Buffer.isBuffer(buf)) {
  //   buf = Buffer.from(String(buf), 'utf8');
  // }

  this.content.push(buf, flags);

  if (cb) {
    this.cbs.push(cb);
  }

  if ((flags & zmq.ZMQ_SNDMORE) === 0) {
    this.isClosed = true;
  }
};
```

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release should support sending buffers as well as strings, no matter in which encoding. It would be great if you could try it out! The new version has a new API that addresses some fundamental issues with the previous API, but it does include a compatibility layer that should make upgrading easier. See #189 for the reasoning behind the new API. If you run into any problems feel free to report it here or in a new issue.
