### ISSUE TITLE
Are the prebuilds working?

### ISSUE THREAD

**Issue by prawnsalad** [zeromq/zeromq.js#337]
On linux and macos it has never found any prebuilt binaries. End users using my app shouldn't need to install an entire build environment.

How are these updated? Is it something the community can help with?

**Comment by jaron-l** [comment]
I can confirm that no prebuilt binaries are found on windows either.

**Comment by lgeiger** [comment]
Sorry for the long wait.
I just re-triggered the release builds and [v5.1.0](https://github.com/zeromq/zeromq.js/releases/tag/v5.1.0) should now include prebuilts for the latest Electron and Node versions.
Feel free to reopen if you still have issues.

**Comment by kbkk** [comment]
@lgeiger Hi, would you mind adding a prebuild 5.1.0/5.1.1 for alpine musl?

`(target=10.16.0 runtime=node arch=x64 libc=musl platform=linux)`

Thanks!
