### ISSUE TITLE
Wrong binaries in prebuild versions for electron v70/v73

### ISSUE THREAD

**Issue by qwe313** [zeromq/zeromq.js#338]
It seems that binaries that are labeled by `zeromq-v5.1.0-electron-v70-X` and `zeromq-v5.1.0-electron-v73-X` are actually built against NODE_MODULE_VERSION  47 and 48 respectively. 

```
Error: The module `...\node_modules\zeromq\build\Release\zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 47. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing

```

```
Error: The module `...\node_modules\zeromq\build\Release\zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing

```

**Comment by qwe313** [comment]
@lgeiger Can you take a look please?

**Comment by andsav** [comment]
Indeed, these binaries are wrong will not work with Electron 6 . You need to rebuild manually:

`cd node_modules/zeromq/`

`HOME=~/.electron-gyp node-gyp rebuild --target=6.0.0 --arch=x64 --dist-url=https://electronjs.org/headers`

**Comment by qwe313** [comment]
@andsav can you please confirm that manual build works? I've tried it either but surprisingly got the same result, for `--target=6.0.0` it was node_module_version 48 and for `--target=5.0.0` it was 47. Probably a did something wrong

**Comment by crnbarr93** [comment]
@andsav Attempting to run this command produces an error for me:

Command: `node-gyp rebuild --target=6.0.0 --arch=x64 --dist-url=https://electronjs.org/headers`

Error:
`LINK : fatal error LNK1104: cannot open file 'C:\Users\...\node_modules\zeromq\build\Release\..\..\windows\lib\libzmq.lib' [C:\Users\...\node_modules\zeromq\build\zmq.vcxproj]`

This is using Visual Studio 2017 on Windows 10.

**Comment by andsav** [comment]
@qwe313 manual build works for me with the command above (not `npm rebuild` since that will try to download the binaries from github first which are wrong)

@crnbarr93 for windows, try downloading the libzmq-4.2.0-x64.lib here: https://github.com/nteract/libzmq-win/tree/master/v140 and copy it to `node_modules/zeromq/windows/lib/libzmq.lib` then run the command again

**Comment by crnbarr93** [comment]
@andsav that worked! Thanks!

**Comment by kyleerik** [comment]
Any idea when the precompiled binaries will be corrected? I wasted the better part of a day looking for this solution. It'd be great to save others the grief.

@andsav and @crnbarr93  you maybe interested to know that the zeromq package.json already includes a script named _build:libzmq_ which downloads the appropriate libzmq.lib for you.

My solution was to create a script in my package.json specifically for rebuilding zeromq manually. It looks like this:

`"rebuild:zeromq": "cd node_modules\\zeromq && npm run build:libzmq && node-gyp rebuild --target=6.0.12 --arch=ia32 --dist-url=https://electronjs.org/headers"`

Obviously the target value will have to be updated anytime I change the version of Electron, but it matches the version I've specified in the devDependencies section of my package.json and I can give this file to another developer and it'll work for them, which was my first concern.

Note: my devenv is Windows 10 and I'm using currently latest Electron, 6.0.12

**Comment by lgeiger** [comment]
Could you check if the issue is still present in the v5.1.1 release?

**Comment by muhammad-saleh** [comment]
Can confirm it works fine:

ZeroMQ: 5.1.1
Node 12.11.1
Electron 6.0.11

![image](https://user-images.githubusercontent.com/1510608/67294495-2f9d3c80-f4e6-11e9-8f1c-7ed351087a9c.png)



Thanks a lot @lgeiger

**Comment by lgeiger** [comment]
Great! This was due to a bug in `prebuild` that mixed Node and Electron versions due to a caching bug: #344

**Comment by axfelix** [comment]
Hi,

Can this issue be reopened? The prebuilt zeromq binaries still aren't declaring compatibility with a supported Electron version, and attempting to rebuild this library on Windows has never worked for me (lots of MSVC compiler errors and I'm not sure if there's a way I can tell it to use mingw gcc to build instead like you can with Windows Python).
