### ISSUE TITLE
Crash EBADF with intense use of ZMQ sockets

### ISSUE THREAD

**Issue by JojoRebondy** [zeromq/zeromq.js#340]
I'm working on several applications in Node.js that communicate to each other with zeromq sockets. I developed a charge test in order to see if the applications were scalable. One of those charge test sends 10 message every 10 ms for 15 minutes to one of those applications.

I've been having a EBADF error that causes the program to abort with this charge test. It seems like it is coming from zeromq. Here is the stack trace from gdb after retrieving a core dump file after a crash.

(gdb) bt
#0  0x00007f15c3cfd067 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f15c3cfe523 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000000ad365a in uv__async_send (loop=<optimized out>, loop=<optimized out>) at ../deps/uv/src/unix/async.c:153
#3  uv_async_send (handle=<optimized out>) at ../deps/uv/src/unix/async.c:65
#4  0x00007f15c0210a5d in zmq::Socket::OutgoingMessage::BufferReference::FreeCallback(void*, void*) ()
   from /media/project/node_modules/zeromq/build/Release/zmq.node
#5  0x00007f15c022ae14 in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#6  0x00007f15c0279c1e in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#7  0x00007f15c026d8c2 in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#8  0x00007f15c026dadf in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#9  0x00007f15c0268a99 in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#10 0x00007f15c0232f66 in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#11 0x00007f15c022bd96 in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#12 0x00007f15c0228655 in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#13 0x00007f15c02275b2 in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#14 0x00007f15c02276ca in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#15 0x00007f15c0248030 in ?? () from /media/project/node_modules/zeromq/build/Release/zmq.node
#16 0x00007f15c407b064 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#17 0x00007f15c3db062d in clone () from /lib/x86_64-linux-gnu/libc.so.6

After realising that the crash was happening in async.c, I added some printf and recompiled node in order to have some results from those lines in /deps/uv/src/unix/async.c:153.

`static void uv__async_send(uv_loop_t* loop) {
  const void* buf;
  ssize_t len;
  int fd;
  int r;

  buf = "";
  len = 1;
  fd = loop->async_wfd;

#if defined(__linux__)
  if (fd == -1) {
    static const uint64_t val = 1;
    buf = &val;
    len = sizeof(val);
    fd = loop->async_io_watcher.fd;  /* eventfd */
  }
#endif

  do
    r = write(fd, buf, len);
  while (r == -1 && errno == EINTR);

  if (r == len)
    return;

  if (r == -1)
    if (errno == EAGAIN || errno == EWOULDBLOCK)
      return;

  abort();
}`

So whenever a crash happens I have 
r = -1
fd = a very high int (last one was for instance = 945893432)
errno = 9 (EBADF which stands for "bad file descriptor").

I might be wrong but I have the impression that the bug comes from a high usage of zeromq sockets in a short time. It seems like this bug does not happen if I make the charge test less challenging for my app.

Any help / advice would be greatly appreciated.

**Comment by rolftimmermans** [comment]
Do you have any code that reproduces this issue? Which OS are you using?

**Comment by abhassaroha** [comment]
This is similar to an earlier reported issue #296 . @JojoRebondy which version are you using? You can try 4.6.0 and see if it resolves the issue. Seems to be an issue in releasing memory in js bindings which got introduced after this version.

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
