### ISSUE TITLE
Use in worker_threads

### ISSUE THREAD

**Issue by broose-goose** [zeromq/zeromq.js#342]
I'm trying to use the worker_thread node feature to allow for a worker pool of pushers that are pre-connected to a sink. I keep getting the error "Module did not self-register" wherever I try to require zeromq in a worker thread context.

Has anyone been able to successfully use zeromq in a worker thread? I read here that it might be as easy as changing a line in the binding.cc file, but had no luck. Link below

https://github.com/nodejs/node/issues/21783#issuecomment-429637117

**Comment by rolftimmermans** [comment]
Interesting. I don't think it is easily possible. Can you elaborate on your use case?

**Comment by rolftimmermans** [comment]
I've published a version of [zeromq-ng](https://github.com/rolftimmermans/zeromq-ng) that works across threads (beta 27) and would like to encourage you to try it out to see if it solves your use case. Would love to hear more.
