### ISSUE TITLE
Unable to build for Electron v5 or v6, but can build fine for Electron v3 or v4

### ISSUE THREAD

**Issue by trusktr** [zeromq/zeromq.js#349]
Hello! I'm not having any luck using `zeromq` with Electron v5 or v6. I'm having this issue: https://github.com/electron/electron/issues/20641

Not sure which repo this belongs in.

**Comment by lgeiger** [comment]
Have you tried with `zeromq@v5.1.1`? See #338 for more info.

**Comment by trusktr** [comment]
Ah, thanks! I'll give that a go soon..

**Comment by slnovak** [comment]
Hello! I have a similar issue where I tried to add zmq to an Electron Forge app (using Electron v7). See electron-userland/electron-forge#1424 for details.

I found that downgrading from 6.0.0-beta.6 to 5.1.1 fixed the issue.

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
