### ISSUE TITLE
Python to Nodejs PUSH and PULL not happenning 

### ISSUE THREAD

**Issue by arunsybex** [zeromq/zeromq.js#354]
**NodeJs**
const zmq = require("zeromq")
 
async function run() {
  const sock = new zmq.Pull
 
  sock.connect("tcp://127.0.0.1:3000")
  
  console.log("Worker connected to port 3000")
 
  for await (const [msg] of sock) {
    console.log("work: %s", msg.toString())
  }
}
 
run()

**Python**

context = zmq.Context()
socket = context.socket(zmq.PUSH)
socket.connect("tcp://127.0.0.1:3000")

socket.send(b"Hello")

**Comment by rolftimmermans** [comment]
From the looks of it, you're going to have to use `bind()` instead of `connect()` on either the Node or Python side.

**Comment by arunsybex** [comment]
Thanks @rolftimmermans  !!! It's working

**Comment by arunsybex** [comment]
@rolftimmermans   Please update this document https://zeromq.org/

**Comment by rolftimmermans** [comment]
> @rolftimmermans Please update this document https://zeromq.org/

If you have any suggestions for improvements feel free to open a PR at https://github.com/zeromq/zeromq.org.
