### ISSUE TITLE
Cannot read property close of undefined

### ISSUE THREAD

**Issue by jarodium** [zeromq/zeromq.js#361]
**Describe the bug**
When exiting the node process with process.exit(0) i get: 'TypeError: Cannot read property 'close' of undefined' when trying to call this.requester.close()

**Reproducing**
Have a rep socket listening and use class declaration below:

```
// person.js
'use strict';

class TheClass {
    constructor(stats) {        
        this.zmq = require('zeromq');
        this.requester;
    }
    __connect() {                        
        this.requester = this.zmq.socket('req');         
        
        this.requester.on("message", function(reply) {
            var MSG = reply.toString();
            MSG = MSG.slice(MSG.indexOf("{"),MSG.lastIndexOf("}")+1);
            MSG = JSON.parse(MSG);
            
            console.log(MSG);

            if (MSG == "server-shutdown") { 
                console.log("process exiting");                
                this.requester.close();
                process.exit(0);
            }
            
        });
    
        this.requester.connect("tcp://localhost:6666");            

        let payload = {
            'cmd' : 'process-spawn',
            'stats' : this.stats
        }
        
        this.requester.send(JSON.stringify(payload));

       
        process.on('SIGINT', function() {                   
            this.requester.close();
            process.exit(0);
        });
        process.on('SIGTERM', function() {                        
            this.requester.close();
            process.exit(0);
        });
    }     
}

class Class extends TheClass {
    constructor(stats) {        
        super(stats);                
    }       
}

module.exports = {
    Class    
};
```

**Expected behavior**
The socket should close as expected without errors.
When declaring zmq and requester variables outside of class scope, requester.close() works with no issues. 

The line below also works as expected
```
this.requester.send(JSON.stringify(payload));
```
**Tested on**
 - OS:Linux Solus 5.3.10-134
 - ZeroMQ.js version: 5.1.1

Is my approach incorrect and I should use the global scope instead of creating the requester object inside the class? If the process ends, will the socket automatically close, even if I don't call it directly? I would like to do a clean shutdown when the app exists or receives a command to shutdown.

**Comment by rolftimmermans** [comment]
You should probably not attach `process.on(...)` handlers for each object that is being constructed. The handlers will never be unregistered. You'll get a new handler for each object instance. The handlers won't be able to call `close()` on an object if it no longer exists.

In any case, this is not needed. Sockets will be closed automatically on process exit, there is nothing you need to do.

If the exit is a clean one (no interrupt), the context may still be sending messages in the background I/O thread. If you want to disable this you can set the `linger` option on the socket to `0`. (See [ZMQ_LINGER](http://api.zeromq.org/4-3:zmq-setsockopt#toc28)).

**Comment by jarodium** [comment]
Hello @rolftimmermans thank you for the advice. Will check on ZMQ linger.

Actually that process.on() is attached to a forked process I call from the main script. Since that script will work in tandem with the main script ( ie they are continuosly talking to each other ), I rigged both of them so that I can exit both of them at the same time, hence the process.on to make a cleaner exit.
