### ISSUE TITLE
 stupid questions

### ISSUE THREAD

**Issue by IDONTSUDO** [zeromq/zeromq.js#374]
I have a few stupid questions that I decided to clarify.

Do I understand correctly that I can only use String type to send messages?

Under which operating system will I achieve maximum ZeroMq performance?

**Comment by rolftimmermans** [comment]
You can use strings or buffers, or an array of strings of buffers to send [multipart messages](http://zguide.zeromq.org/page:all#Multipart-Messages). Anything else will be converted to strings first.

ZeroMQ, and by extension, ZeroMQ.js is highly tuned for performance.  I doubt your choice of OS matters significantly; it will mostly depend on your application. If you want to know more about the OS differences you might get better answers on the [mailing lists](http://wiki.zeromq.org/docs:mailing-lists).

**Comment by IDONTSUDO** [comment]
I was just confused a little, here is this question https://github.com/zeromq/zeromq.js/issues/276.
Thank you for the answer. And you couldn’t add a little code to your examples, namely to supplement of them with methods.

`
JSON.stringify and JSON.parse 
`

Could you supplement some of the examples with methods.

I believe this will improve the documentation.
sorry for my bad english

**Comment by rolftimmermans** [comment]
Thanks for your suggestion. The examples assume the reader is familiar with ZeroMQ semantics. I have updated the README.

Using JSON is one way to serialize application data.  According to the [ZeroMQ documentation](https://zeromq.org/messages/):

> On the wire, ZeroMQ messages are blobs of any size from zero upwards that fit in memory. You do your own serialization using protocol buffers, msgpack, JSON, or whatever else your applications need to speak. It’s wise to choose a data representation that is portable, but you can make your own decisions about trade-offs.

**Comment by IDONTSUDO** [comment]
thx!1
