### ISSUE TITLE
How to Install without Internet Access?

### ISSUE THREAD

**Issue by JamesYYang** [zeromq/zeromq.js#380]
I need install this package in our server which is no internet access. 

NPM registry we have private one which is a proxy of official.

It seems the install script will download zip package from github. So is there any other way to install it?

**Comment by rolftimmermans** [comment]
As of version 6.0.0-beta the prebuilt binaries are included in the NPM package. Hope that helps!

**Comment by JamesYYang** [comment]
6.0.0-beta can be used in production now?

**Comment by rolftimmermans** [comment]
Definitely, and I don't think a release candidate is very far away.
