### ISSUE TITLE
Error: Socket is busy writing

### ISSUE THREAD

**Issue by JamesYYang** [zeromq/zeromq.js#381]
Everything works fine when I use 4.x version.
After upgrade to 6.x, I get this error: **Error: Socket is busy writing; only one send operation may be in progress at any time**. 
My code block like below:
```js
const socket = new zmq.Push; 
socket.sendHighWaterMark = 1000;
socket.sendTimeout = 0;
socket.connect(address);
socket.send(msg)
```
The reason I set ```sendTimeout``` to 0 is that the message is huge at publisher side, any block will be exhaust the memory.
So do I use zeromq in wrong way?

**Comment by rolftimmermans** [comment]
Based on your code sample, it's important to use `await socket.send(...)`, so your code should look like this:

```
const socket = new zmq.Push; 
socket.sendHighWaterMark = 1000;
socket.sendTimeout = 0;
socket.connect(address);
await socket.send(msg);
```

Does that help?

**Comment by mikolaj6r** [comment]
@rolftimmermans could You explain what would `await` add ? Assuming that @JamesYYang sends only one message.

I'm having that error, too. I'm sending many messages and all of them are received by second side. However, after trying to send N-th message, I get this error.

**Comment by JamesYYang** [comment]
@rolftimmermans Thanks for quick reply.
I will provide more fake code to explain my program.

```js
const express = require('express');
const app = express();
const http = require("http");
const zmq = require('zeromq');

const socket = new zmq.Push; 
socket.sendHighWaterMark = 1000;
socket.sendTimeout = 0;
socket.connect(address);

let sendMsg = (log) => {
  socket.send(msg)
}

app.all('/do-something', (req, res) => {
  //do something
  res.send(response);
  sendMsg(requestLog);
});

let server = http.createServer(app);
server.listen(8000);

```

**Comment by normano** [comment]
I ran into this too and used [p-queue](https://www.npmjs.com/package/p-queue) in front of the socket.

**Comment by reedipher** [comment]
I am also running into this problem... Adding a p-queue did not seem to help. When using an await, the publisher hangs after 512 sends which is suspicious.

**Comment by agirorn** [comment]
@reedipher it seems you are able to get await with sending around 512 messages until zeromq must do some housekeeping and then it is blocked and throws the "Socket is busy writing;" Error. You can test it with these scripts.

```js
// Puller.js
const zmq = require("zeromq")
const address = 'tcp://127.0.0.1:3000';

async function run() {
  const socket = new zmq.Pull
  socket.connect(address);
  while(!socket.closed) {
    const result = await socket.receive()
    console.log('result: ', result.map(i => i.toString()));
  }
}

run().then(
  () => { console.log('DONE OK')},
  (error) => { console.log('DONE ERROR', error)})
```

```js
// Pusher.js
const zmq = require('zeromq');
const {default: PQueue} = require('p-queue');

const socket = new zmq.Push;
const address = 'tcp://127.0.0.1:3000';

const run = async () => {
  socket.bind(address);
  const queue = new PQueue({concurrency: 1});
  socket.events.on('accept', async () => {
    console.log('BIND')
    let i = 0;
    while(i < 1000) {
      i++
      try {
        socket.send(i); // Fails on message 514
        // await queue.add(() => socket.send(i)) // Will send all 1000 messages
      } catch(error) {
        console.log(`Failed sending message ${i}`, error);
      }
    }
  });
};

run().then(
  () => { console.log('DONE OK')},
  (error) => { console.log('DONE ERROR', error)})
```

**Comment by reedipher** [comment]
@agirorn thanks for the help!

Your example does indeed work if the await is used and if the data is pumped out as fast as possible. I'm relatively new to javascript, so maybe I'm missing something very obvious so forgive me, but if I try to slow down the send speed then I go back to having the same error as before.

For example, if I want to send the data via zmq at roughly 100Hz, I add a 10 ms delay which seems to break the code. 

```
function sleep (ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

const run = async () => {
  socket.bind(address);
  const queue = new PQueue({concurrency: 1});
  socket.events.on('accept', async () => {
    console.log('BIND')
    let i = 0;
    while(i < 1000) {
      i++
      try {
        await queue.add(() => socket.send(i)) // Will send all 1000 messages
        await sleep(10); // <-- adding this seems to break the code
      } catch(error) {
        console.log(`Failed sending message ${i}`, error);
      }
    }
  });
};
```

I have some C++ code that is receiving the data, parsing it and making use of it, so I'd rather not just saturate the zmq socket if I can find some way to either slow down the send events or make them more interrupt driven. Thanks again for the help.

**Comment by agirorn** [comment]
That does not break when I run it. I'm using zeromq@6.0.0-beta.6. Are you using the same version?

**Comment by reedipher** [comment]
I am. I wonder if it has something to do with using Electron?

**Comment by rolftimmermans** [comment]
This was caused by a fix for #356, which yields to the Node.js event loop every 512 messages.

This is surprising behaviour if the timeout is explicitly set to `0`. I have changed the logic to never yield if the timeout is 0, forcing the method call to `send()` or `receive()` to be synchronous.

If the timeout is 0 the starvation check will still be done.

**Comment by nodesocket** [comment]
@rolftimmermans just came across this. Can you explain what could be causing?

```
Error: Socket is busy writing; only one send operation may be in progress at any time
    at Publisher.send (<anonymous>)
    at WebsocketClient.<anonymous> (/home/node/macd/crypto-ingestd/lib/CoinbaseProStreams.js:76:23)
    at WebsocketClient.emit (events.js:315:20)
    at WebsocketClient.onMessage (/home/node/macd/node_modules/coinbase-pro/lib/clients/websocket.js:94:12)
    at WebSocket.emit (events.js:315:20)
    at Receiver._receiver.onmessage (/home/node/macd/node_modules/ws/lib/websocket.js:137:47)
    at Receiver.dataMessage (/home/node/macd/node_modules/ws/lib/receiver.js:409:14)
    at Receiver.getData (/home/node/macd/node_modules/ws/lib/receiver.js:347:12)
    at Receiver.startLoop (/home/node/macd/node_modules/ws/lib/receiver.js:143:16)
    at Receiver.add (/home/node/macd/node_modules/ws/lib/receiver.js:117:10) {
  errno: 16,
  code: 'EBUSY'
}
```

Code example:

```javascript
const publisher = new zmq.Publisher({
    sendHighWaterMark: 1,
    sendTimeout: 0,
    heartbeatInterval: 10000,
});

publisher.bind('tcp://127.0.0.1:3030');

publisher.send(['eth-ticks', doc])
    .catch(Log.error);

```

**Comment by 8secz-johndpope** [comment]
chiming in here - 

I have a killZmq.sh script that looks like this
where 28333/ 38333 ports are potentially blocked

```shell

#!/bin/bash
echo '🏗 freeing up node on port 28333/38333'
pid=$(lsof -t -i:28333,38333);set -f;a=(${pid})
for e in ${a[@]}
do
    echo $e
    kill -9 $e
done

```

**Comment by notedit** [comment]
@rolftimmermans  `6.0.0-beta.6` still have this error.
