### ISSUE TITLE
Does the node client has bind_to_random_port like function?

### ISSUE THREAD

**Issue by metalshan** [zeromq/zeromq.js#382]
I want to randomly bind an available port within a range to the publisher.
Very similar to the `socket.bind_to_random_port()` function of the python library.

Does the node library has any such thing?

**Comment by rolftimmermans** [comment]
Yes, you can use a `*` as the port to assign a random port, and you can use [`lastEndpoint`](http://zeromq.github.io/zeromq.js/classes/socket.html#lastendpoint) to retrieve the endpoint that was used to bind to:

```
const sock = new zmq.Dealer()
await sock.bind("tcp://127.0.0.1:*")
console.log(sock.lastEndpoint)
```

This should print something like:
```tcp://127.0.0.1:56114```

**Comment by rolftimmermans** [comment]
I updated the documentation in f847c80.

**Comment by metalshan** [comment]
Thanks for the update @rolftimmermans ... but generally we will want it to pick a port from a given range; not a complete wildcard. Is there any such api?

**Comment by rolftimmermans** [comment]
That's not supported by the OS (which provides this feature to ZeroMQ); you'll have to provide your own logic, in the same way as PyZMQ does. Example:

```
function getRandomPort(min = 49152, max = 65536) {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

async function bindToRandomPort(sock, maxAttempts = 100) {
  let attempt = 0
  while (true) {
    try {
      const port = getRandomPort()
      await sock.bind(`tcp://127.0.0.1:${port}`)
      return port
    } catch (err) {
      if (err.code === "EADDRINUSE") {
        attempt++
        if (attempt < maxAttempts) continue
      }

      throw err
    }
  }
}

const sock = new zmq.Dealer()
const port = await bindToRandomPort(sock)
```

**Comment by metalshan** [comment]
@rolftimmermans got it. Thank you!
