### ISSUE TITLE
Producer and Worker with kubernetes

### ISSUE THREAD

**Issue by AguGriguol** [zeromq/zeromq.js#383]
HI!

I have a cluster in kubernetes with two worker nodes and one master. I've two deployments, one is a producer and the second a worker. After a time, the worker suddenly stop receiving data but if I redeploy the worker work fine again. I'm using 5.1.0 version of zeromq with push and pull arch.

I decided to add more logs and callbacks to the worker connection, for instance:

```const worker = zmq.socket('pull');

worker.monitor();
        
await worker.connect(`tcp://${process.env.ZMQ_HOST_NAME}:${process.env.ZMQ_PORT}`);

console.log(`${new Date().toISOString()} events worker ready!`);
        
worker.on('message', onMessage);

worker.on(`connect_delay`, (eventId) => {
        console.log(`${new Date().toISOString()} Req socket (${eventId}) connect request is pending`);
    });

    worker.on('connect', (socket) => {
        console.log(`${new Date().toISOString()} Succesfully connected to messaging intereface to controller ${socket}`);
    });

    worker.on(`connect_retry`, (eventId) => {
        console.log(`${new Date().toISOString()} Req socket (${eventId}) connect request failed, and is now being retried`);
    });

    worker.on(`bind_error`, (eventId) => {
        console.log(`${new Date().toISOString()} Req socket (${eventId}) could not bind to a given interface`);
    });

    worker.on(`accept`, (eventId) => {
        console.log(`${new Date().toISOString()} Req socket (${eventId}) has accepted successfully a connection from a remote peer`);
    });

    worker.on(`error`, (err) => {
        console.error(`${new Date().toISOString()} error occured with the ZMQ socket ${err.toString()}`);
    });

    worker.on(`close`, (eventId) => {
        console.log(`${new Date().toISOString()} Req socket (${eventId}) closed successfully`);
    });

    worker.on(`close_error`, (eventId) => {
        console.log(`${new Date().toISOString()} Req socket (${eventId}) failed to close`);
    });

    worker.on(`disconnect`, (eventId) => {
        console.log(`${new Date().toISOString()} Req socket (${eventId}) disconnected unexpectedly`);
    });
```

Are this callbacks fine? Or can I add others?
What things can I debug?

When can we have the 6x version in release?

Thanks

**Comment by rolftimmermans** [comment]
I would suggest using a tool like `tcpdump` to inspect your network traffic.

It's impossible to say what is causing this without more information. Is the pod of the "producer" application restarted when this happens? Which socket types do you use?

**Comment by AguGriguol** [comment]
HI @rolftimmermans!

The producer send the message without problems, but the worker or consumer never receive the message. I'm using push and pull TCP.
When this happends, I've restarted the worker and everything work fine.

The callbacks never fire any event. I've tested the network and everything work fine.

Thanks for your help

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
