### ISSUE TITLE
sub/pub how listen event？thanks！

### ISSUE THREAD

**Issue by blogwy** [zeromq/zeromq.js#395]
how listen event on client? "message" event is worked,but "connect" and "disconnect" event no respond When I disconnect the server

this is code:

`var zmq = require('zeromq')
  , sock = zmq.socket('sub');

sock.on('message', function(topic, message) {
  console.log('received a message related to:', Buffer.from(topic, 'utf-8').toString(), 'containing message:', Buffer.from(message, 'utf-8').toString());
});

sock.connect('tcp://127.0.0.1:3000');
sock.subscribe('');
console.log('Subscriber connected to port 3000');

sock.on('connect', function () {
  console.log('connect success')
})

sock.on('disconnect', function (err) {
  console.log(err)
})`

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
