### ISSUE TITLE
electron 8.1.1 can not build with zeromq

### ISSUE THREAD

**Issue by bindy** [zeromq/zeromq.js#396]
http 404 https://github.com/zeromq/zeromq.js/releases/download/v5.2.0/zeromq-v5.2.0-electron-v76-win32-x64.tar.gz

**Comment by hangon1234** [comment]
Having exactly same issue. Problem seems like the newer version of electron does not support  old zeromq version. I tried to change version ^6.x.x-beta. But it seems build script is only for linux environment, which will cause build to crash.
When I try to build zeromq, I get message "sh not recognized...." so the build script only written in .sh extension and doesn't have .bat version.
I am very new to write build script.
Can anyone look into it and make PR? I don't want to use old version of electron

**Comment by hangon1234** [comment]
what i did in last few hours
npm install zerorpc
(electron-root)/node_modules/.bin/electron-rebuild
produces error message : syntax error, bla bla...
I guess because old version of zeromq or python script makes problem. (not sure :( )
than i modify (electroy-root)/node-modules/zerorpc/package.json and zeromq ^6.x.x than save it
and then cd to (electron-root)/node-modules/zerorpc than run "npm install" without any problem.
now go to (electron-root) again and try to build again
./(electron-root)/node_modules/electron-build
and then after while I get error message: sh is not recognized~....
not sure if it builds correctly in linux/mac environment.
any suggestion?

**Comment by hangon1234** [comment]
solved the problem. don't need wsl (windows subsystem linux)
you can use git bash for windows. 
I guess it comes with Git for Windows by default.
then go to your project root, simply run electron-rebuild again.
You might get error message like cmake doesn't exist, just search google and install it.
After that I can finally run npm start!
Will test if it really can import zerorpc and connect to local zerorpc server.
Just want anybody find it helpful. Git bash solved the problem. Nice!

**Comment by hangon1234** [comment]
before run electron-rebuild , make sure you change zerorpc's package.json and set the version of zeromq to 6.x.x and save it.
than run "npm install" in the zerorpc directory
than go back to project root and try to build.

**Comment by mikelyndersOKCC** [comment]
@hangon1234  I am running into the following issue on windows 10. I followed you instructions, ran `electron-rebuild` in git-bash and it seems I have an issue with cmake. I installed Visual Studio 2019 and restarted my computer. Did you have any issue here?

 ```
 build_libzmq
  Downloading libzmq source...
  Building libzmq...
  CMake Error at CMakeLists.txt:2 (project):
    Generator

      Visual Studio 15 2017 Win64

    could not find any instance of Visual Studio.
```

**Comment by hangon1234** [comment]
> @hangon1234 I am running into the following issue on windows 10. I followed you instructions, ran `electron-rebuild` in git-bash and it seems I have an issue with cmake. I installed Visual Studio 2019 and restarted my computer. Did you have any issue here?
> 
> ```
> build_libzmq
>  Downloading libzmq source...
>  Building libzmq...
>  CMake Error at CMakeLists.txt:2 (project):
>    Generator
> 
>      Visual Studio 15 2017 Win64
> 
>    could not find any instance of Visual Studio.
> ```
> 
> **Edit**: I uninstalled Visual Studio 2019 and replaced with 2017. Make sure to include the C++ tools for desktop development. `electron-rebuild` succeeded but still getting error `Error: No native build was found for platform=browser arch=javascript runtime=electron abi=undefined uv= libc=glibc node=undefined webpack=true` in console

Hi, I finally decided not use zeromq.
Instead, use python-nodejs libary which uses simple stdout/stdin
Python-shell which I used (https://www.npmjs.com/package/python-shell)
Hope this can help you.
