### ISSUE TITLE
How to do polling?

### ISSUE THREAD

**Issue by mrakgr** [zeromq/zeromq.js#400]
I've studied the ZeroMQ guide for a few weeks, and translated around half of the examples to NetMQ, so I know how to do it there. But it does not seem like the new library has `on("message")` kinds of events that I see in the guide anymore.

Should I use `Promise.race` together with socket operations in a loop here? That seems to me like the closest thing to what I am looking for.

**Comment by mrakgr** [comment]
```ts
import * as zmq from "zeromq";

const uri_server = "tcp://*:13805";
const uri_client = "tcp://localhost:13805";

const server = async () => {
    const sock = new zmq.Router();
    sock.events.on("bind", async x => {
        console.log(`server bound to ${uri_server}`);
        while (true) {
            console.log("server waiting...");
            const msg = await sock.receive();
            msg.pop();
            msg.push(Buffer.from("World"));
            await sock.send(msg);
        };
    })
    sock.bind(uri_server);
};

const client = async (text : string) => {
    const sock = new zmq.Request();
    sock.connect(uri_client);
    console.log(`client connected to ${uri_client}`);
    await sock.send(text);
    const [msg] = await sock.receive();
    return msg.toString();
};

server();
// client("Hello").then(x => console.log(x));
```

I am really having trouble getting the router to run, as I keep getting the...

```
E:\Webdev\Typescript\zeromq-example>node src/index
server bound to tcp://*:13805
server waiting...
(node:9488) UnhandledPromiseRejectionWarning: Error: Socket is blocked by a bind or unbind operation
```

Any idea of what I am doing wrong here? I waited for the `bind` event specifically to prevent this situation, but it does not seem to be doing anything.

**Comment by rolftimmermans** [comment]
The guide is not accurate for 6.x-beta.x. For examples how to use this library with the latest published version please look at README.md.

We hope to release the latest version as a new stable release and then we'll have to update the existing guides that correspond to the 4.x/5.x versions.
