### ISSUE TITLE
Event based message reception

### ISSUE THREAD

**Issue by nitrixx** [zeromq/zeromq.js#410]
Hello,
is there a way to receive messages from a socket event based, like it was possible with prior versions?

I am trying to mimic the functionality of the official NodeJS examples and it was really convenient to just do something like:
```
var zmq = require('zmq')

// Connect to task ventilator
var receiver = zmq.socket('pull')

receiver.on('message', function(msg) {
  console.log("From Task Ventilator:", msg.toString())
})
```
(taken from http://zguide.zeromq.org/js:mspoller)

This is especially useful when all you want to do is to react to incoming messages *from multiple sockets*

**Comment by JamesRamm** [comment]
@nitrixx any reason why this was closed (if you found the solution can you share?). I am also interested in this - specifically I want to mix zeromq with a standard HTTP API using express. 
The `for await ... of` syntax is its' own event loop so I cannot use the standard nodejs `server.listen` to set up a HTTP server...

**Comment by nitrixx** [comment]
@JamesRamm 
unfortunately I did not find a solution to my question. Since I was unable to implement any useful ZeroMQ pattern proposed in the ZeroMQ guide without knowing how to properly deal with multiple sockets (like PPP or Majordomo you mentioned), I decided to not use this libary. There were no replies to this issue, so I just closed it.

**Comment by agirorn** [comment]
@JamesRamm `for await ... of` is not running in a separate event loop but it is blocking the function it is in so you either have to first start the server listen and then read the messages from the socket or register the reading from the socket as a separate function running in the event loop with [process.nextTick()](https://nodejs.org/api/process.html#process_process_nexttick_callback_args)
```js
server.listen(calback);
for await (const [msg] of sock) {
  console.log("work: %s", msg.toString())
}
```

or 

```js
process.nextTick(() => {
  for await (const [msg] of sock) {
    console.log("work: %s", msg.toString())
  }
})
server.listen(calback);
```
