### ISSUE TITLE
How to compile v6.0.0 using VS 2015 build tools (v140)?

### ISSUE THREAD

**Issue by humatic** [zeromq/zeromq.js#419]
This isn't a bug, nor a feature request. Rather, I'm wondering how hard it would be to build `v6.0.0` for Windows using the `v140` toolset. I see that older versions of zeromq.js used the `v140` toolset, but now you're at `v141`. Is there any easy way to accomplish this?

I attempted to edit the binding.gyp so that it had `'msbuild_toolset': 'v140'`, but that produced vague build errors that I don't know how to interpret.

I need this because the Windows devices that I need to deploy on do not have the `v141` runtime DLLs. I also tried downgrading to zeromq.js `v5.2.0`, but it turns out that my verson of Electron (`v9.0.5`) isn't in the list of prebuilt binaries. If I'm going to go through the trouble of building these binaries from scratch (and it's a LOT of trouble), then I'd prefer to have the latest zeromq.js.

Thanks for any feedback!

**Comment by androllen** [comment]
I get this build error about zeromq.js [build error](https://github.com/nodejs/node-gyp/issues/2228)
