### ISSUE TITLE
[question] any updates about 6.0.0 release? 

### ISSUE THREAD

**Issue by smitalm** [zeromq/zeromq.js#436]
Hello,

We have been waiting for 6.0.0 release with anticipation. 
However, I see that it has now been more than a year now since last beta update.

So i'd like to ask, if there are any updates about the possible release? Are the main contributors still working/planning to work on 6.0.0, or are they busy with other projects?

**Comment by JamesRamm** [comment]
Also have this question. 
With the changes in the C++ API for Node v14+, it is more or less mandatory to now update to ZMQ v6, though the fact that it is still marked as in 'beta' raises questions about its' production-readiness.
Even if no more changes are planned and the latest beta can be deemed production-worthy, a release just to remove the 'beta' tag and make it official would be great.

**Comment by JamesRamm** [comment]
@aminya - seems you now have access to make releases. Any news on this issue? 
Are there any barriers to making an official v6 release (non-beta)?

**Comment by aminya** [comment]
We are tracking the road to v6 in #466. Thanks!
