### ISSUE TITLE
Question : How to contribute to repo with prebuilds for Mac M1

### ISSUE THREAD

**Issue by DonJayamanne** [zeromq/zeromq.js#441]
Sorry for not using the right template.
Not sure this is the place to ask this, but I'm trying to find out how we can contribute the prebuilds for Mac m1

**Comment by JamesHenry** [comment]
I'm here for the same reason. When installing my repo on a new Mac Mini for the first time, the zeromq piece generated a large output and ultimately exited with a `make` error.

I'm definitely out of my comfort zone when inspecting these types of logs, but It seems the _building_ piece did actually succeed, but the `node-gyp` command did not. 

In my case zeromq is in my dependencies because of a dependency on `sawtooth-sdk` which brings it in (and sadly that's v4 of `zeromq.js` although I don't _think_ that was relevant here).

**Comment by aminya** [comment]
We managed to build Zadeh, one of my native libraries, for macOS by adding the following flags. But there are no CI services or official Node for Arm64 to prebuild and test it. I requested one of my friends who has M1 to build it locally and send me the arm64 prebuild.

https://github.com/atom-community/zadeh/blob/0a5ca9a129fdfd947fa4c697dfdbbdc36dbd721f/binding.gyp#L27-L34
```py
            'OTHER_CFLAGS': [
              '-arch x86_64',
              '-arch arm64'
            ],
            'OTHER_LDFLAGS': [
              '-arch x86_64',
              '-arch arm64'
            ]
```

**Comment by DonJayamanne** [comment]
@aminya any update on this? Thanks for looking into this.
I could send the executable as well (though, I'm not sure that's the right thing to do, i could easily add any malicious code into that).
I guess we'll wait for the official release.

**Comment by aminya** [comment]
We can add the compiler flags for the source builds, but we cannot provide prebuilds and promise anything about the functionality. We are in a situation where a company has released a new product with a new architecture with no way to test software on it. I don't think we can add official support for that product.

https://github.com/actions/virtual-environments/issues/2187

**Comment by ni-mkrieg** [comment]
@aminya, I have similar problems when cross-compiling for arm64 on x64 MacOs using electron-builder; keytar e.g. works great by providing a pre-build for arm64. Even re-compiling externals on x64 does not work, it always ends up just with x64 support even when using your binding.gyp flags proposed above.

I can work around this for separate OS builds by pre-building on arm64 and staging the pre-build but that does not work well in the combined universal build. So it would be great to either have a branch that compiles arm64 on x64 correctly or even better a prebuilt binary for arm64.
