### ISSUE TITLE
Typescript support for 5.x

### ISSUE THREAD

**Issue by overflowz** [zeromq/zeromq.js#460]
**Is your feature request related to a problem? Please describe.**
There are currently no proper types available for the 5.x version, while on DefinitelyTyped, the latest type definitions are for 4.x.

**Describe the solution you'd like**
To be able to have types when using in a typescript project.

**Describe alternatives you've considered**
Update types on DefinitelyTyped to support 5.x as well.

**Comment by aminya** [comment]
Pull requests are wellcome!

**Comment by overflowz** [comment]
created one: https://github.com/zeromq/zeromq.js/pull/461

please do keep in mind that these are minimal types. It would be nice to have proper values for example for the `setsockopt` (right now, I made all of them of type `unknown`).

**Comment by overflowz** [comment]
UPDATE: opened a PR on DefinitelyTyped instead https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52566

**Comment by overflowz** [comment]
cc @aminya sorry for pinging, would you mind to re-approve it again? I added a missing type definition (`close` getter) and it requires re-review (the request review button does not work for some reason).

Thank you.

**Comment by aminya** [comment]
No worries! Reapproved. Sometimes, I lose the notifications as there are many of them.

**Comment by overflowz** [comment]
No worries too 😅 Thank you!

**Comment by aminya** [comment]
Closing this as `@types/zeromq` v5 is released
