### ISSUE TITLE
Question: Roadmap, Project Status, Things in General.

### ISSUE THREAD

**Issue by overflowz** [zeromq/zeromq.js#464]
I'm sure this question was asked previously quite a lot, but it's hard to track everything together, so I'm asking them here:

1) What is the status of the project? Are there any plans to actively maintain the library or it's being abandoned(ish)?
2) What is the roadmap of v6? What needs to be done to make it stable?
3) There were reported quite issues before (memory leaks, crashes, etc). Is v5 (or v6) actually stable (by stable I mean is it recommended to use in a production project)?

Thank you.

**Comment by aminya** [comment]
v5 is stable and is already in use in production. See [Hydrogen](https://github.com/nteract/hydrogen/) as an example.

There are a couple of issues with ZeroMQ 6:
- Access violation that happens after [this test](https://github.com/aminya/zeromq.js/blob/8cdcef739abd56a97c2af5e91c56400b9eb94f83/test/unit/socket-send-receive-test.ts#L123):
https://github.com/nodejs/node-addon-api/issues/965

- Memory leaks (GC failures). The tests for these fail:
```js
  1) socket with inproc close
       in gc finalizer
         should release reference to context:
      AssertionError: expected false to equal true
      + expected - actual
      -false
      +true
      
      at Context.<anonymous> (test/unit/socket-close-test.ts:156:16)
  2) socket with tcp close
       in gc finalizer
         should release reference to context:
      AssertionError: expected false to equal true
      + expected - actual
      -false
      +true
      
      at Context.<anonymous> (test/unit/socket-close-test.ts:156:16)
  3) socket with ipc close
       in gc finalizer
         should release reference to context:
      AssertionError: expected false to equal true
      + expected - actual
      -false
      +true
      
      at Context.<anonymous> (test/unit/socket-close-test.ts:156:16)

```

**Comment by overflowz** [comment]
Thank you. I'll try to have a look into the memory leak issue whenever I can (NB: haven't used C++ for ages, could take time).

**Comment by gastmeier** [comment]
@aminya In the example you postet they import `import { Message, Socket } from "@aminya/jmp";`. What is this? My imports look like this: `import * as zeromq from 'zeromq'`. Why is this totally different?

**Comment by aminya** [comment]
> @aminya In the example you postet they import `import { Message, Socket } from "@aminya/jmp";`. What is this? My imports look like this: `import * as zeromq from 'zeromq'`. Why is this totally different?

You should check our general examples in the readme or the examples folder.
v5:
https://github.com/zeromq/zeromq.js/tree/5.x
v6:
https://github.com/zeromq/zeromq.js

Regarding Hydrogen, that's an implementation detail for `Hydrogen`. It uses `zeromq` through `jmp` (for Jupyter kernel communication). You shouldn't write your code based on that.

**Comment by gastmeier** [comment]
@aminya I checked every example. Here they are:

```typescript
sock.bindSync('tcp://127.0.0.1:3000');
console.log('Producer bound to port 3000');

setInterval(function(){
  console.log('sending work');
  sock.send('some work');
}, 500);
```

```typescript
sock.bindSync('tcp://127.0.0.1:3000');
console.log('Publisher bound to port 3000');

setInterval(function(){
  console.log('sending a multipart message envelope');
  sock.send(['kitty cats', 'meow!']);
}, 500);
```

```typescript
var s = new zmq.socket('pub');
s.bind('tcp://127.0.0.1:0');
s.send('test');
setTimeout(function () {
    s.close();
}, 1000);
```

```typescript
sock.connect('tcp://127.0.0.1:3000');
sock.subscribe('kitty cats');
console.log('Subscriber connected to port 3000');

sock.on('message', function(topic, message) {
  console.log('received a message related to:', topic.toString(), 'containing message:', message.toString());
});
```

```typescript
sock.connect('tcp://127.0.0.1:3000');
console.log('Worker connected to port 3000');

sock.on('message', function(msg){
  console.log('work: %s', msg.toString());
});
```

How do i know from these examples, if i have to use `bind` or `connect`? How do i know which events exist? (`connect`, `connect_delay`, `connect_retry`, `listen`, `bind`, `bind_error`, `accept`, `accept_error`, `close`, `close_error`, `disconnect`, `message` <- took me hours to find that out...) How do i know that i have to call `monitor` so that these events are even distributed? Which of the examples show me how to handle errors?

**Comment by gastmeier** [comment]
@aminya ?

**Comment by aminya** [comment]
Check out our documentation to learn the differences:
https://zeromq.github.io/zeromq.js/classes/socket.html
connect:
https://zeromq.github.io/zeromq.js/classes/socket.html#connect
bind:
https://zeromq.github.io/zeromq.js/classes/socket.html#bind

If you need even more examples, check the test folder.

**Comment by gastmeier** [comment]
@aminya Thank you for giving me some links to the documentation.

Is the difference that with `bind` i can use await while with `connect` i can not? And how do i catch errors? The error object is always undefined.

**Comment by gastmeier** [comment]
@aminya Isn't the documentation for version 6.x? Is there a documentation for version 5.x?

**Comment by overflowz** [comment]
@aminya re memory leaks: tried my best, but I have no idea why it is leaking (either because of my C++ knowledge or the NAPI). I'll just provide what I tried and maybe it will be useful for you.

Something interesting I found here: https://github.com/zeromq/zeromq.js/blob/master/src/socket.cc#L79 which creates a strong reference to the context that was passed and when the socket is garbage collected, it unrefs the context, but the context destructor itself is being called after a few seconds (this, I don't understand why). Even if I don't reset the ref, it has the same behavior.

When I set the weak reference, it worked, but it's not the correct behavior, because if context will be garbage collected, `socket.context` will be also garbage collected.

Here's the sample code that reproduces it:
```js
const weak = require("weak-napi")
const zmq = require("./lib")

const task = async () => {
  let context = new zmq.Context()
  new zmq.Dealer({context})

  weak(context, () => {
    console.info("memory freed")
  })

  context = undefined
  global.gc()
}

async function run() {
  await task()
  global.gc()

  /*
  * but if I run setImmediate(() => global.gc())
  * then it works.
  */

  // if I remove this, I get SIGSEGV
  setInterval(() => {}, 1000) // keep the event loop busy
}

run()
```

logs I get from SIGSEGV (if I won't keep event loop busy & call gc in the main loop)
```
* thread #1, name = 'node', stop reason = signal SIGSEGV: invalid address (fault address: 0x61)
  * frame #0: 0x0000000000000061
    frame #1: 0x00000000009b8de7 node`v8impl::(anonymous namespace)::RefBase::Finalize(bool) + 231
    frame #2: 0x00000000009d85cf node`node_napi_env__::~node_napi_env__() + 95
    frame #3: 0x00000000009a9fdb node`node::Environment::RunCleanup() + 619
    frame #4: 0x000000000096d547 node`node::FreeEnvironment(node::Environment*) + 71
    frame #5: 0x0000000000a4483f node`node::NodeMainInstance::Run() + 271
    frame #6: 0x00000000009d1e15 node`node::Start(int, char**) + 277
    frame #7: 0x00007ffff7a810b3 libc.so.6`__libc_start_main + 243
    frame #8: 0x00000000009694cc node`_start + 41
```

**Comment by willingc** [comment]
@aminya Let's move the memory leak troubleshooting to its own issue.

**Comment by willingc** [comment]
@aminya and @overflowz Let's move the memory leak discussion here: https://github.com/zeromq/zeromq.js/issues/466

**Comment by aminya** [comment]
That's a good idea. I will close this in favor of #466
