### ISSUE TITLE
random install failure

### ISSUE THREAD

**Issue by mrtnlrsn** [zeromq/zeromq.js#467]
**Describe the bug**
pnpm install fails randomly 1 in 5-10 times when using version 5.2.8. Does not happen with 5.2.4

Output:
.../zeromq@5.2.8/node_modules/zeromq install: Building libzmq for linux
.../zeromq@5.2.8/node_modules/zeromq install: build_libzmq.sh: Building version 4.2.2 for architecture x64
.../zeromq@5.2.8/node_modules/zeromq install: gzip: stdin: unexpected end of file
.../zeromq@5.2.8/node_modules/zeromq install: tar: Unexpected EOF in archive
.../zeromq@5.2.8/node_modules/zeromq install: tar: Unexpected EOF in archive
.../zeromq@5.2.8/node_modules/zeromq install: tar: Error is not recoverable: exiting now
.../zeromq@5.2.8/node_modules/zeromq install:   TOUCH Release/obj.target/libzmq.stamp
.../zeromq@5.2.8/node_modules/zeromq install:   CXX(target) Release/obj.target/zmq/binding.o
.../zeromq@5.2.8/node_modules/zeromq install: ../binding.cc:28:10: fatal error: zmq.h: No such file or directory
.../zeromq@5.2.8/node_modules/zeromq install:  #include <zmq.h>
.../zeromq@5.2.8/node_modules/zeromq install:           ^~~~~~~
.../zeromq@5.2.8/node_modules/zeromq install: compilation terminated.

**Reproducing**
Seen with

    pnpm install

**Expected behavior**
Work every time.

**Tested on**
 - OS: Ubuntu 20.04
- pnpm 5.8.0
- zeromq 5.2.8 (OK with 5.2.4)

**Comment by aminya** [comment]
Seems like a connection issue or a file system error in the build script. I don't think we can do much here other than retrying.

**Comment by mrtnlrsn** [comment]
node v12.18.0
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

Seen many times with zeromq 5.2.8. Never problem with other npm modules, or zeromq 5.2.4.

**Comment by overflowz** [comment]
for me, it looks like the tar file is not downloaded completely and when trying to extract content from it, it fails to do so (i.e., can extract some files but break somewhere).

whenever you face the same issue again, can you try to unpack it with tar and check if you'll get the same error? if so, can you check the tar file is actually a complete download or failed due to some network errors?

**Comment by n-riesco** [comment]
@mrtnlrsn, are you also using `pnpm` to install `zeromq`?

**Comment by mrtnlrsn** [comment]
> @mrtnlrsn, are you also using `pnpm` to install `zeromq`?

Yes

**Comment by mrtnlrsn** [comment]
> for me, it looks like the tar file is not downloaded completely and when trying to extract content from it, it fails to do so (i.e., can extract some files but break somewhere).
> 
> whenever you face the same issue again, can you try to unpack it with tar and check if you'll get the same error? if so, can you check the tar file is actually a complete download or failed due to some network errors?

I am back on 5.2.4, so don't expect it to happen again.

**Comment by n-riesco** [comment]
Sorry @mrtnlrsn, I meant to ping @overflowz to confirm they are also using `pnpm`.

**Comment by overflowz** [comment]
Sorry, I'm not. I tried using npm & yarn.

**Comment by mrtnlrsn** [comment]
FYI: I accidentally upgraded to 5.2.8, and got build failures again, one in 5-10 times on our build server.
Will go back to 5.2.4 again...

**Comment by sdepuy** [comment]
I experienced the same issue and had to downgrade to 5.2.4 in order for our builds to work. Now, there is a vulnerability issue using 5.2.4 with a simple-get dependency (via prebuild-install). Looks like the only way to fix this vulnerability is to upgrade again to 5.2.8. Has this "random install failure" issue been resolved (or even been looked at)?

**Comment by vliubezny** [comment]
The issue persists for 5.3.0. I was able to reproduce it several times. Archive `zeromq-4.2.2.tar.gz` appeared valid every time. It had the correct checksum. I assume that unarchiving started before all data had been flushed to the file system.

I have prepared PR #521. Installation was completed successfully 20 times in a row.

**Comment by overflowz** [comment]
I actually cannot reproduce it with pnpm on Arch linux using pnpm version 7.16.0, have you tried it first?

**Comment by vliubezny** [comment]
Nope, I have to use npm.

**Comment by overflowz** [comment]
Approved the PR, although I'm not sure if "finish" event is supported on older node versions, can you confirm that?

**Comment by aminya** [comment]
Fixed by #521
