### ISSUE TITLE
npm install fails on CentOS

### ISSUE THREAD

**Issue by swateek** [zeromq/zeromq.js#471]
**Describe the bug**
I tried installing zeromq using the two commands below and I still get the same error.

`npm i zeromq`

**ENOENT: no such file or directory, open '/home/apps/webapp/node_modules/zeromq/node_modules/nan/package.json.2214050187'**

`npm i zeromq@5.1.0`

**ENOENT: no such file or directory, open '/home/apps/webapp/node_modules/prebuild-install/node_modules/minimist/package.json.620347472'**

`npm ci`

```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! zeromq@5.1.0 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the zeromq@5.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Reproducing**
Always

**Expected behavior**
Installation should be smooth
**Tested on**
 - OS: CentOS 7.6 (a Vagrant VM Box)
 - ZeroMQ.js version: 5.1.0
 - NodeJS : 12

I am unsure what I am missing

**Comment by aminya** [comment]
Please install the latest version: 
```
npm install zeromq@5
```

**Comment by swateek** [comment]
I tried that as well.

```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! zeromq@5.2.8 install: `node-gyp-build || npm run build:libzmq`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the zeromq@5.2.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by aminya** [comment]
What libc does CentOS use?

**Comment by swateek** [comment]
I ran `yum list glibc`

```
Installed Packages
glibc.x86_64                                                                              2.17-324.el7_9
```

My CentOS version is **CentOS Linux release 7.6.1810 (Core)**

**Comment by swateek** [comment]
I was finally able to make this work.

I had installed node via npm as root user, when that changed my original zeromq of version 5.1.0 got installed.

Thank you for the help, and your time.
