### ISSUE TITLE
zeromq v6.0.0-beta.6 fails to start with create-react-app

### ISSUE THREAD

**Issue by wwschneider** [zeromq/zeromq.js#480]
**Describe the bug**
When starting from a new project with create-react-app and using zeromq v6.0.0-beta.6, the app fails to load with "ReferenceError: require is not defined".

The app starts fine if zeromq is not imported and a Request object is not instantiated. Once an attempt to instantiate a Request is made, the above exception occurs.

**Reproducing**

- `npx create-react-app myapp --template typescript`
- modify the generated myapp/App.tsx to include `import { Request } from "zeromq"` and `new Request();`
- `npm start`

Full contents of App.tsx:
```
import React, { useEffect, useRef } from 'react';
import logo from './logo.svg';
import { Request } from "zeromq"
import './App.css';

const SERVER_HOST = '192.168.86.100';
const SERVER_PORT = '5555';

function App() {
  const requestSocket = useRef<Request | null>(null);

  useEffect(() => {
    if (requestSocket.current === null) {
      requestSocket.current = new Request();
      requestSocket.current.connect(`tcp://:${SERVER_HOST}:${SERVER_PORT}`);
    }

    return (): void => {
      requestSocket.current?.close();
    };
  }, []);

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}

export default App;

```

**Expected behavior**
The react app should compile and start successfully.

**Tested on**
 - OS: MacOS 11.4
 - ZeroMQ.js version: v6.0.0-beta.6

**Comment by overflowz** [comment]
I cannot tell for sure, but this package is only for the nodejs (backend), not for the frontend. You'll have to add @types/node for it to work I believe, but I'm not sure what you're trying to achieve, this package won't work on the frontend (please correct if I'm wrong).

**Comment by wwschneider** [comment]
I'm not sure I understand; there are plenty of nodejs packages out there that are compatible with frontend frameworks like React - and I had assumed all nodejs packages in general were if a bundler can handle them. Are you suggesting `@types/node` for Typescript compatibility? If there are simply nodejs packages out there that aren't compatible with frontend frameworks, I'd be curious to hear more.

What I'm trying to achieve with including zeromq in a React project is displaying a video stream in a UI in a performant manner. I'm using imagezmq (https://github.com/jeffbass/imagezmq) in a server application to stream video from a camera to the server, and would like to use zeromq.js to receive video from the server to a UI.

I have an alternative method that I'm using currently - hosting a FastAPI endpoint that provides a video stream for the UI to display in an `img` element, but I was curious whether using zeromq for that step would provide better streaming performance.

**Comment by overflowz** [comment]
The reason for that is, this package needs a native module to be built and it cannot be included in the browser (well, unless it's compiled in WASM, but can't tell if that is possible with this library). If you want to use something that works in the browser, I think this is the package you're looking for https://github.com/zeromq/jszmq but again, I haven't tested nor tried it so it's up to you to play around.

**Comment by wwschneider** [comment]
Oh sweet, thanks for the explanation and the package recommendation! It does look like what I need; I'll give it a try. I think this addresses my issue if zeromq.js isn't meant for use in the browser.
