### ISSUE TITLE
Is @types/zeromq intended to use on Typescript project?

### ISSUE THREAD

**Issue by dendrik-l** [zeromq/zeromq.js#481]
I know this is not the best place but
What is the point of the @types/zeromq? It seems glaringly lacking of type definitions compared to the API definitions at https://zeromq.github.io/zeromq.js/globals.html, it doesn't even have a 'receive' method defined on sockets.
How should I use zeromq on Typescript? 

I am running Debian wsl2.0 on Windows
Node 16.6.2
Typescript 4.4.2

Edit:
Even running that simple example code from Readme in JavaScript doesn't work

const zmq = require("zeromq")
async function run() {
  const sock = new zmq.Reply
  await sock.bind("tcp://127.0.0.1:3000")
  for await (const [msg] of sock) {
    await sock.send(2 * parseInt(msg, 10))
  }
}
run()

Now, by documentation Reply is a class so the sample code is wrong from the start.
Changed the line to 'new zmq.Reply()' and I'm informed that zmq.Reply is not a constructor

Changed the whole bit to 

const zmq = require("zeromq")
async function run() {
    const sock = zmq.createSocket('rep')
    await sock.bind("tcp://127.0.0.1:3000")

    for await (const [msg] of sock) {
        await sock.send(2 * parseInt(msg, 10))
    }
}
run()

and I'm told that sock is not async iterable.

Did I do something wrong or is this project just no longer maintained?

**Comment by marc-slingshot** [comment]
I would also love to have correct types for zeromq.  Seems they are out of sync.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/zeromq/index.d.ts

When people who make modules don't care for producing typescript types that project takes contributions for other people to update external types for the module....

**Comment by overflowz** [comment]
it depends on what version you use. Version 6 is already written in typescript, as the @types/zeromq is only for version 5.

To use the typescript version (which is still in beta for a long time) you can install it by: `npm install zeromq@6.0.0-beta.6`, otherwise by default it installs version 5 and it has a different API.

documentation for version 5: https://github.com/zeromq/zeromq.js/tree/5.x

**Comment by marc-slingshot** [comment]
I do see version 6 has typescript, but it's worrying that it's in beta still and the last release was Dec 2019.

**Comment by overflowz** [comment]
I know, I feel the same to be honest. I was just pointing out that those types are not really outdated, it's for version 5 :) Also, the example used in this thread was for version 6, but more likely it was version 5 installed.

**Comment by aminya** [comment]
It seems this issue is already fixed. As @overflowz explained, the types for version 5 are different from version 6.
