### ISSUE TITLE
Build fail for electron and macOS M1 + Homebrew

### ISSUE THREAD

**Issue by correnson** [zeromq/zeromq.js#489]
**Describe the bug**
Can not rebuild zeromq with electron on mac M1, although using exactly the same configuration on mac x64 does work.

**Reproducing**
```
yarn add/rebuild zeromq
```

Detailed log can be found in discussion.

**Tested on**
 - macOS M1 (arm64)
 - homebrew/zeromq 4.3.4 for arm64
 - electron 15.3.0 and many others
 - node 16.12.0 and many others
 - ZeroMQ.js versions 5.x and 6.x

**Comment by correnson** [comment]
Detailed log message: [build.log](https://github.com/zeromq/zeromq.js/files/7502905/build.log)

**Comment by YanDevDe** [comment]
I'm also having this issue on M1 Max, with the exactly same error and similar specs

**Comment by Bartel-C8** [comment]
That exact error message I find here:
https://github.com/nodejs/node-gyp/issues/2144#issuecomment-877512560

They suggest resolving it with this guideline:
https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md

Does the "acid test" work for you?
`curl -sL https://github.com/nodejs/node-gyp/raw/master/macOS_Catalina_acid_test.sh | bash`
