### ISSUE TITLE
cannot build zeromq@6.0.0-beta.6 for Platform=linux arch=x64 runtime=node abi=83

### ISSUE THREAD

**Issue by CharithFIT** [zeromq/zeromq.js#507]
when I try to use  zeromq@6.0.0-beta.6 I got following error 

"Error: No native build was found for platform=linux arch=x64 runtime=node abi=83 uv=1 libc=glibc node=14.19.3 webpack=true"

Event I tried to build the package with above option, it was not working could you please help on this?

**Comment by thomasnal** [comment]
npm compiles it by default when native build not found. you will need to install build dependencies such as cmake.

**Comment by mehiatt** [comment]
I am also seeing this on windows: No native build was found for platform=win32...
I am trying to use it with nodejs pgk module, to make it an exe. 
Would I have to exclude zmq somehow for this to work?

**Comment by OMY-onlymissyou** [comment]
> npm compiles it by default when native build not found. you will need to install build dependencies such as cmake.

Could you explain this method in more detail
