### ISSUE TITLE
'zmq.version' mismatch on 'npm list'

### ISSUE THREAD

**Issue by GKSONG** [zeromq/zeromq.js#509]
Why zeromq version is different between 'zmq.version' and 'npm list' result ?

o. Test enivornment
   -- CentOS 8.4
   -- Ubuntu 22.04

o. 'npm list' output
   └── zeromq@5.2.8

o. Simple Request (node.js -- nodejs v12.22.9, npm v8.5.1) program output
var zmq = require('zeromq');
console.log(' Client zeromq version : ', zmq.version);
 --> Client zeromq version :  4.2.2

**Comment by Bartel-C8** [comment]
There is a difference between the npm `zeromq(.js)` package (which is in your case 5.2.8, which is using `libzmq`, in your case 4.2.2 . Definitely not a bug, but could be clearer maybe indeed...
