### ISSUE TITLE
can't build in windows 10 x86

### ISSUE THREAD

**Issue by BrookZhao** [zeromq/zeromq.js#556]
**Describe the bug**

**Reproducing**
$ node-gyp rebuild
Debugger attached.
gyp info it worked if it ends with ok    
gyp info using node-gyp@9.3.1
gyp info using node@14.21.2 | win32 | x64
gyp info find Python using Python version 3.11.0 found at "C:\Python311\python.exe"
gyp info find VS using VS2017 (15.9.33027.88) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python311\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\zhaoshanwei\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\workspace\\chibi-face\\node_modules\\zeromq\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zhaoshanwei\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\zhaoshanwei\\AppData\\Local\\node-gyp\\Cache\\14.21.2\\include\\node\\common.gypi',gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\zhaoshanwei\\AppData\\Local\\node-gyp\\Cache\\14.21.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\zhaoshanwei\\AppData\\Roaming\\npm\\node_modules\\node-gyp',        
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\zhaoshanwei\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.21.2\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\workspace\\chibi-face\\node_modules\\zeromq',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\workspace\\chibi-face\\node_modules\\zeromq\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Debugger attached.
Waiting for the debugger to disconnect...
Warning: unrecognized setting VCLinkerTool/BasicRuntimeChecks while converting to MSBuild.
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\M
SBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  build_libzmq
  Debugger attached.
  Downloading libzmq source from https://cdn.npmmirror.com/packages/zeromq/6.0.0-beta.16/zeromq-6.0.0-beta.16.tgz
  Debugger attached.
  Waiting for the debugger to disconnect...
  Debugger attached.
  Waiting for the debugger to disconnect...
  Building libzmq Release
  cmake -S "libzmq-20de92ac0a2b2b9a1869782a429df68f93c3625e" -B ./build  -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedD
  LL -DCMAKE_GENERATOR_PLATFORM=X64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="C:\workspace\chibi-face\node_
  modules\zeromq/build/libzmq" -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_STATIC=ON -DBUILD_TESTS=OFF -DBUILD_SHARED=OFF -DW 
  ITH_DOCS=OFF -DWITH_LIBSODIUM=ON -DWITH_LIBSODIUM_STATIC=ON
  Debugger attached.
  'cmake' 锟斤拷锟斤拷锟节诧拷锟斤拷锟解部锟斤拷锟筋，也锟斤拷锟角匡拷锟斤拷锟叫的筹拷锟斤拷
  锟斤拷锟斤拷锟斤拷锟斤拷锟侥硷拷锟斤拷
  Waiting for the debugger to disconnect...
  cmake --build ./build --config Release --target install
  Debugger attached.
  'cmake' 锟斤拷锟斤拷锟节诧拷锟斤拷锟解部锟斤拷锟筋，也锟斤拷锟角匡拷锟斤拷锟叫的筹拷锟斤拷
  锟斤拷锟斤拷锟斤拷锟斤拷锟侥硷拷锟斤拷
  Waiting for the debugger to disconnect...
  find: no such file or directory: C:/workspace/chibi-face/node_modules/zeromq/build/libzmq/lib/*.lib
  mv: invalid arguments
  Waiting for the debugger to disconnect...
  context.cc
c:\workspace\chibi-face\node_modules\zeromq\src\prefix.h(8): fatal error C1083: 无法打开包括文件: “zmq.h”: No such file or d
irectory [C:\workspace\chibi-face\node_modules\zeromq\build\zeromq.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\20
17\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\zhaoshanwei\AppData\
Roaming\npm\node_modules\node-gyp\lib\build.js:203:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chil
d_process.js:285:12)
gyp ERR! stack     at Process.callbackTrampoline (internal/async_hooks.j
s:130:17)
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\zhaos
hanwei\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\workspace\chibi-face\node_modules\zeromq
gyp ERR! node -v v14.21.2
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
Waiting for the debugger to disconnect...

**Expected behavior**
can build in windows 10 x86

**Tested on**
 - OS: [e.g. Windows 10]
 - ZeroMQ.js version: [e.g. 6.0.0-beta.16]

**Comment by aminya** [comment]
The library provides prebuilds for X86 Windows. There is no need to build.

The build command is `ARCH=x86 npm run build`

**Comment by BrookZhao** [comment]
thanks
