### ISSUE TITLE
What is the break changes from zmq?

### ISSUE THREAD

**Issue by zydjohnHotmail** [zeromq/zeromq.js#566]
Hello:
I want to run install bitcore and run some tests. I can install bitcore via npm, but when I tried to run bitcored, I got the following errors:
D:\nodejs\bitcore\node_modules\bitcore\bin>node bitcored conf=bitcore.conf
D:\nodejs\bitcore\node_modules\zmq\node_modules\bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → D:\nodejs\bitcore\node_modules\zmq\build\zmq.node
 → D:\nodejs\bitcore\node_modules\zmq\build\Debug\zmq.node
 → D:\nodejs\bitcore\node_modules\zmq\build\Release\zmq.node
 → D:\nodejs\bitcore\node_modules\zmq\out\Debug\zmq.node
 → D:\nodejs\bitcore\node_modules\zmq\Debug\zmq.node
 → D:\nodejs\bitcore\node_modules\zmq\out\Release\zmq.node
 → D:\nodejs\bitcore\node_modules\zmq\Release\zmq.node
 → D:\nodejs\bitcore\node_modules\zmq\build\default\zmq.node
 → D:\nodejs\bitcore\node_modules\zmq\compiled\18.14.2\win32\x64\zmq.node
    at bindings (D:\nodejs\bitcore\node_modules\zmq\node_modules\bindings\bindings.js:88:9)
    at Object.<anonymous> (D:\nodejs\bitcore\node_modules\zmq\lib\index.js:6:30)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\nodejs\bitcore\node_modules\zmq\index.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  tries: [
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\build\\zmq.node',
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\build\\Debug\\zmq.node',
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\build\\Release\\zmq.node',
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\out\\Debug\\zmq.node',
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\Debug\\zmq.node',
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\out\\Release\\zmq.node',
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\Release\\zmq.node',
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\build\\default\\zmq.node',
    'D:\\nodejs\\bitcore\\node_modules\\zmq\\compiled\\18.14.2\\win32\\x64\\zmq.node'
  ]
}

Node.js v18.14.2

D:\nodejs\bitcore\node_modules\bitcore\bin>dir d:\nodejs\Bitcore\node_modules\zmq\
 Volume in drive D is SATABackup
 Volume Serial Number is 4425-E62C

 Directory of d:\nodejs\Bitcore\node_modules\zmq

04/18/2023  10:48 PM    <DIR>          .
04/18/2023  10:48 PM    <DIR>          ..
04/18/2023  10:48 PM               173 .editorconfig
04/18/2023  10:47 PM               168 .npmignore
04/18/2023  10:48 PM             1,615 .travis.yml
04/18/2023  10:48 PM               356 appveyor.yml
04/18/2023  10:48 PM            47,648 binding.cc
04/18/2023  10:47 PM             2,203 binding.gyp
04/18/2023  10:48 PM    <DIR>          examples
04/18/2023  10:48 PM             5,820 History.md
04/18/2023  10:47 PM                35 index.js
04/18/2023  10:48 PM    <DIR>          lib
04/18/2023  10:47 PM             1,098 LICENSE
04/18/2023  10:48 PM               405 Makefile
04/18/2023  10:47 PM    <DIR>          node_modules
04/18/2023  10:47 PM             2,284 package.json
04/18/2023  10:48 PM    <DIR>          perf
04/18/2023  10:47 PM             7,929 README.md
04/18/2023  10:48 PM    <DIR>          test
04/18/2023  10:48 PM    <DIR>          windows
              12 File(s)         69,734 bytes
               8 Dir(s)  385,752,739,840 bytes free

I tried to install/uninstall zmq, but later on, I found zmq is out of support now, it is becoming zeromq now.
I found there is only one JavaScript file require('zmq'), I want to know if I can simply change require('zmq') to require('zeromq') can do the job or not.
The file which require('zmq') is this one:
dir node_modules\bitcore\node_modules\bitcore-node\lib\services\bitcoind.js
    Directory: D:\nodejs\bitcore\node_modules\bitcore\node_modules\bitcore-node\lib\services

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         4/18/2023  10:53 PM          62237 bitcoind.js

This file is rather big: 60KB in size, but I want to know if there is any break change from zmq to zeromq.
Please advise on which part I should pay more attention if I want to migrate from zmq to zeromq in JavaScript.
My current enviroment: OS: Windows 10 (22H2); Node.js: v18.14.2; Npm: 9.5.0; the zmq version used in bitcore package: 2.15.3.
And which zeromq has the least break change or if any version of zeromq has no break change from zmq version 2.15.3, please advise,
Thanks

**Comment by martindale** [comment]
Wow, crazy to see Bitcore here!  I too am using this package, but for the project I started after Bitcore, [Fabric](https://fabric.pub).  I'm starting work on a 6.0 branch now!

**Comment by aminya** [comment]
Please try with the latest version. The build issues have been fixed
