### ISSUE TITLE
Cannot install ZeroMq 5 on Node 14

### ISSUE THREAD

**Issue by Elderkly** [zeromq/zeromq.js#583]
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > routing-controllers@0.9.0" has incorrect peer dependency "class-transformer@^0.3.1".
warning " > routing-controllers@0.9.0" has incorrect peer dependency "class-validator@^0.12.2".
warning " > typeorm-typedi-extensions@0.4.1" has incorrect peer dependency "typedi@>=0.10.0".
[4/4] Building fresh packages...
error /var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq: Command failed.
Exit code: 1
Command: node-gyp-build || npm run build:libzmq
Arguments: 
Directory: /var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.19.3 | linux | x64
gyp info find Python using Python version 2.7.5 found at "/bin/python"
gyp info spawn /bin/python
gyp info spawn args [
gyp info spawn args   '/data/node-v14.19.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/data/node-v14.19.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/lib/jenkins/.cache/node-gyp/14.19.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/var/lib/jenkins/.cache/node-gyp/14.19.3',
gyp info spawn args   '-Dnode_gyp_dir=/data/node-v14.19.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/var/lib/jenkins/.cache/node-gyp/14.19.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq/build'
  ACTION binding_gyp_libzmq_target_prepare_build zmq/BUILD_SUCCESS
Error: socket hang up
    at connResetException (internal/errors.js:639:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}

** Your connection was reset. **

** Are you behind a proxy or a firewall that is preventing a connection? **
make: *** [zmq/BUILD_SUCCESS] Error 1
gyp ERR! build error 
make: Leaving directory `/var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq/build'
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/node-v14.19.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 3.10.0-957.10.1.el7.x86_64
gyp ERR! command "/data/node-v14.19.3-linux-x64/bin/node" "/data/node-v14.19.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq
gyp ERR! node -v v14.19.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1692067296572-0.7034593312264041/node but npm is using /data/node-v14.19.3-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> zeromq@5.2.8 build:libzmq /var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq
> node-gyp rebuild

make: Entering directory `/var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq/build'
  ACTION binding_gyp_libzmq_target_prepare_build zmq/BUILD_SUCCESS
Error: connect ETIMEDOUT 140.82.114.4:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '140.82.114.4',
  port: 443
}
make: *** [zmq/BUILD_SUCCESS] Error 1
make: Leaving directory `/var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/node-v14.19.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 3.10.0-957.10.1.el7.x86_64
gyp ERR! command "/data/node-v14.19.3-linux-x64/bin/node" "/data/node-v14.19.3-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/lib/jenkins/workspace/coinfun-test/node_modules/zeromq
gyp ERR! node -v v14.19.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zeromq@5.2.8 build:libzmq: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.2.8 build:libzmq script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/jenkins/.npm/_logs/2023-08-15T02_45_46_757Z-debug.log
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Build step 'Execute shell' marked build as failure
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
Finished: FAILURE

**Comment by Alireza17224** [comment]
Same issue here

**Comment by aminya** [comment]
v6 has been released. Please upgrade to the latest version.
