### ISSUE TITLE
No native build was found for Docker Alpine

### ISSUE THREAD

**Issue by zmeecer** [zeromq/zeromq.js#597]
**Describe the bug**

I'm trying to use the library in next.js application, locally on Mac everything works smoothly.
Packaging the app into a docker image provokes an error:

```
No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=musl node=18.19.0
```

In docker, the `prebuilds` folders in empty in node_modules/zeromq/prebuilds, but locally it's full or options

**Reproducing**

- generate a [next.js application](https://nextjs.org/docs/getting-started/installation)
- wrap into the [default Docker image](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile) 

**Expected behavior**

- Prebuilt files are existing in the prebuild
- The zmq lib can be used

**Tested on**
 - [node:18-alpine](https://github.com/nodejs/docker-node/blob/5bb305299145aa996bd3e0a701e5a3c3d587ad82/18/alpine3.19/Dockerfile)
 - ZeroMQ.js version: 6.0.0-beta.19

**Comment by zmeecer** [comment]
The issue was in building process: multi-stage build of next.js is not copying prebuilds to the `runner` stage, although creating a minimal node_modules. After adding a copy instruction to dockerfile - works.

**Comment by eulersson** [comment]
Hello @zmeecer would you be so kind to share the Dockerfile or what steps did you take? I am using Next.js 14 and there's no feasable way I found to make it work... I created this issue for it: https://github.com/zeromq/zeromq.js/issues/600

Thank you.

**Comment by eulersson** [comment]
@zmeecer I am trying with a simple dockerfile like:

```
# FROM node:20.11.0-bookworm-slim
FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json ./

RUN npm install

COPY . .

CMD ["npm", "run", "dev"]
```

and same errors...

```
⨯ node_modules/@aminya/node-gyp-build/index.js (60:8) @ load.path
⨯ Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=musl node=18.19.0 webpack=true
```

Those are my only deps in the package json.

```
"dependencies": {
    "next": "14.1.0",
    "react": "^18",
    "react-dom": "^18",
    "zeromq": "6.0.0-beta.19"
  }
```

I have the full example at https://github.com/eulersson/zeromq.js-next.js-errors

**Comment by eulersson** [comment]
@zmeecer You mention

> After adding a copy instruction to dockerfile - works

I'm guessing you are copying the prebuilds, but where to? 

```
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodej ??? ???
```

**Comment by zmeecer** [comment]
Hey @eulersson
Inside the runner stage I have the following line:
```
COPY --from=deps /app/node_modules/zeromq ./node_modules/zeromq
```

Although I also for more supported architecture using node:18-bookworm (debian) instead of alpine linux

**Comment by eulersson** [comment]
@zmeecer Thanks for replying and sorry about the rush :) Can I ask what `next` version you have on your `packages.json`? Can you run `npm run dev` or `yarn dev` and have it compile the page that uses ZeroMQ?

**Comment by eulersson** [comment]
Cloning this https://github.com/eulersson/zeromq.js-next.js-errors and running `npm install` and `npm run dev` on my mac (Sonoma 14.1.1) does not work. Could you give me a hand and tell me if it compiles well when visiting http://localhost:3000 on the browser?

**Comment by eulersson** [comment]
I think I'm getting somewhere... I can see the files from `./node_modules/zeromq/prebuilds` are not being copied to `.next/server`, therefore the standalone next server fails to find them because it's looking for a `prebuilds` directory at `.next/server` instead of `./node_modules/zeromq`. The `prebuilds` folder therefore needs to exist under `.next/server`. If I copy it and then run `npm run dev` again it's absurd because it seems to clean everything and rebuild it from scratch, therefore not bringint the `prebuilds` folder.

**Comment by eulersson** [comment]
Quoting from https://nextjs.org/docs/app/api-reference/next-config-js/output#caveats

> There are some cases in which Next.js might fail to include required files, [...] In those cases, you can leverage [...] `experimental.outputFileTracingIncludes` respectively in next.config.js

I will give `outputFileTracingIncludes` a go... STRANGE because at some point I managed to have it working without having to touch anything in next.config.js.

**Comment by eulersson** [comment]
Not working. I guess this is intended for later stages, not for build stage...
