### ISSUE TITLE
electron+node+react "require is not defined'.

### ISSUE THREAD

**Issue by FrenchFries53** [zeromq/zeromq.js#598]
**Describe the bug**
require is not defined
Call Stack
 eval
  node_modules/@aminya/node-gyp-build/index.js:7:23
 ../../node_modules/@aminya/node-gyp-build/index.js
  main.js:18:1
 options.factory
  main.js:30429:31
 __webpack_require__
  main.js:29810:33
 fn
  main.js:30086:21
 eval
  node_modules/zeromq/lib/native.js:7:18
 ../../node_modules/zeromq/lib/native.js
  main.js:21007:1
 options.factory
  main.js:30429:31
 __webpack_require__
  main.js:29810:33
 fn
  main.js:30086:21
------------------------------------------------------
use version:
  electron:25.3.1
  @types/node: 18.13.0
  @types/react: 17.0.53
zeromq:5.3.1 or lastet 
Has anyone encountered an error message that has been continuously reported since its introduction?

**Comment by aminya** [comment]
You are trying to bundle this backend code in your front-end that doesn't support require.

**Comment by FrenchFries53** [comment]
May I ask what I should do? This is an error reported in the dependency and it is the front-end code.
