### ISSUE TITLE
NPM install failed for zeromq dependency while installing device farmer STF. NPM logs available in the description.

### ISSUE THREAD

**Issue by namanthapliyal** [zeromq/zeromq.js#601]
OS:
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"

Attaching the npm error logs in npm install command. I have already installed the libzmq using configure, make, install. And exported the library path using command: export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
[zeromq npm logs.txt](https://github.com/zeromq/zeromq.js/files/14233995/zeromq.npm.logs.txt)

**Comment by 029A-h** [comment]
Same bug for me

**Comment by aminya** [comment]
v4 is no longer supported. v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
