### ISSUE TITLE
Bump into same issue as #514 which should be fixed using v5.3.1

### ISSUE THREAD

**Issue by marcong95** [zeromq/zeromq.js#604]
**Describe the bug**
Same issue as #514, Fatal error in V8: v8_ArrayBuffer_NewBackingStore

According to the issue #514 and PR #532, fatal error when using Electron v21+ should be fixed. But I still bump into the same issue when using Electron v23.3.2 and ZeroMQ v5.3.1. 

I am using ZeroMQ with zerorpc-node, but I forked zerorpc-node because it's outdated. And change its dependency to zeromq@5.3.1

After some debugging, I found the app crashed at zeromq/lib/index.js:655.

```javascript
var message = this._zmq.readv(); // can throw
```

Could anyone please tell me some idea to solve this problem? Thanks

**Reproducing**
Client written in JavaScript (tested ok on Node.js but crashed on Electron)
```javascript
const { Client } = require('zerorpc')
const client = new Client()
client.connect('tcp://127.0.0.1:4242')
client.invoke('add', 1, 2, (err, resp, extra) => {
  console.log(err, resp, extra)
})
```

Server written in Python 3.10:
```python
import zerorpc

class RPCServer():
    def add(self, a, b):
        return a + b

if __name__ == '__main__':
    server = zerorpc.Server(RPCServer())
    server.bind('tcp://127.0.0.1:4242')
    server.run()
```

**Expected behavior**
No more crash and receive response from the server.

**Tested on**
 - OS: Windows 10
 - ZeroMQ.js version: 5.3.1
 - Electron: 23.3.2
 - zerorpc-node: https://github.com/marcong95/zerorpc-node

**Comment by Yackob234** [comment]
I'm having a similar issue using
- OS: Windows 11
- ZeroMQ.js version: 5.3.1
- Electron: 21.3.2
but without any fork.

`[21036:0321/132855.727:ERROR:node_bindings.cc(146)] Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.`
`[21036:0321/132855.727:ERROR:crashpad_client_win.cc(844)] not connected`

My code crashes on the first `socket.send();` that appears.

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
