### ISSUE TITLE
Architecture error caused by Mac CI tests

### ISSUE THREAD

**Issue by rotu** [zeromq/zeromq.js#626]
CI is reporting an incompatible architecture problem on macOS:

> ```
>   1) Uncaught error outside test suite:
>      Uncaught Error: dlopen(/Users/runner/work/zeromq.js/zeromq.js/build/Release/zeromq.node, 0x0001): tried: '/Users/runner/work/zeromq.js/zeromq.js/build/Release/zeromq.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/zeromq.js/zeromq.js/build/Release/zeromq.node' (no such file), '/Users/runner/work/zeromq.js/zeromq.js/build/Release/zeromq.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
>       at Object.Module._extensions..node (node:internal/modules/cjs/loader:1460:18)
>       at Module.load (node:internal/modules/cjs/loader:1203:32)
>       at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
>       at Module.require (node:internal/modules/cjs/loader:1231:19)
>       at require (node:internal/modules/helpers:177:18)
>       at load (node_modules/.pnpm/@aminya+node-gyp-build@4.8.1-aminya.1/node_modules/@aminya/node-gyp-build/node-gyp-build.js:22:10)
>       at Object.<anonymous> (src/native.ts:5:51)
>       at Module._compile (node:internal/modules/cjs/loader:1364:14)
>       at Module.m._compile (node_modules/.pnpm/ts-node@10.9.2_@types+node@18.19.34_typescript@4.9.5/node_modules/ts-node/src/index.ts:1618:23)
>       at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
> ```
https://github.com/zeromq/zeromq.js/actions/runs/9551631841/job/26326410348#step:16:143
[logs_24997356421.zip](https://github.com/user-attachments/files/15875295/logs_24997356421.zip)

**Comment by aminya** [comment]
That's because we didn't have ARM64 runners to test things back in the day when I added this variant. We could only cross-compile for ARM64, but not test it.
