### ISSUE TITLE
Draft support not enabled by default

### ISSUE THREAD

**Issue by antoniaelsen** [zeromq/zeromq.js#638]
**Describe the bug** A clear and concise description of what the bug is.

ZMQ Draft support is not enabled by default in builds, despite the suggestion in the [README](https://github.com/zeromq/zeromq.js/blob/f9ee2a3e2c39f63874da29b4ed10df460a33e500/README.md?plain=1#L98)

Quick ref:
https://github.com/zeromq/zeromq.js/blob/f9ee2a3e2c39f63874da29b4ed10df460a33e500/.github/workflows/CI.yml#L64
https://github.com/zeromq/zeromq.js/blob/f9ee2a3e2c39f63874da29b4ed10df460a33e500/binding.gyp#L4

Is the README technically incorrect or should the build scripts & config be updated? Can submit a PR to correct either way.

**Comment by aminya** [comment]
The draft is not enabled in the latest release yet. I plan to enable it in the upcoming release. The readme shows the dev status.

**Comment by antoniaelsen** [comment]
@aminya are the cli / .npmrc --zmq-draft and --build-from-source flags expected to work? I'm not convinced the zmq lib is being rebuilt when I'm using them, and when trying to use draft features (RADIO/DISH), I get
```
Error: ZeroMQ draft features are not enabled in this build. To enable support, (re)compile this library with --zmq-draft.
```

**Comment by aminya** [comment]
Building from the source first checks for the binaries. So, it doesn't build from the source in reality if the binaries already exist. You can work around this by removing the prebuilds folder. We should fix this though.

**Comment by aminya** [comment]
I have migrated the build to CMake/vcpkg. Now you can enable the `Draft` support through `npmrc` by building from the source.
https://github.com/zeromq/zeromq.js#draft-support
