### ISSUE TITLE
Curve not enabled by default

### ISSUE THREAD

**Issue by muscleman** [zeromq/zeromq.js#640]
following some examples of implementing curve on a pub/sub i get cannot set public, secret or server public keys

setting socket.curveserver = true throws exceptions too.

- OS: [Ubuntu 22.04]
- ZeroMQ.js version: [6.0.0-beta.20]

**Comment by aminya** [comment]
Curve is not included in the prebuilt binaries anymore following the upstream approach. You should build the binaries from the source if that is desired.

**Comment by muscleman** [comment]
so adding 
`
# Zmq settings
build_from_source=true
zmq_draft=true
`

and setting -DWITH_LIBSODIUM=ON 

is enough to get curve?

**Comment by muscleman** [comment]
would be super helpful if someone could do a little documentation on how to turn on curve

**Comment by aminya** [comment]
I have migrated the build to CMake/vcpkg. Now you can enable the `Curve` support through `npmrc`.
https://github.com/zeromq/zeromq.js#curve-support

**Comment by aminya** [comment]
It should have worked, if it doesn't that's an issue we need to look into. Did it rebuild Zeromq from the source once you did this?

**Comment by antoncxx** [comment]
> It should have worked, if it doesn't that's an issue we need to look into. Did it rebuild Zeromq from the source once you did this?

I think so. At least the first time I attempted to do `npm install zeromq` it failed, because I didn't have cmake installed.
Once I installed all the required dependencies, the installation succeeded.

**Comment by ctataryn** [comment]
@aminya  I can confirm that adding:

```
build_from_source=true
zmq_curve="true"
```

to `.npmrc` doesn't seem to add Curve.

Here's my scenario:

We were using `"zeromq": "^6.0.0-beta.6"` and the following code works at runtime:

```typescript
  wsiZmqDealerSock = new Dealer({
    routingId: ZMQ_ROUTING_ID,
    sendTimeout: 0,
    reconnectInterval: 2000,
    curveServer: false,
    curveServerKey: spk,
    curvePublicKey: cpk,
    curveSecretKey: csk
  })
```

However, we removed and re-generated our `package-lock.json` file and it upgraded zeromq as follows (in `package-lock.json`):

```
    "node_modules/zeromq": {
      "version": "6.1.2",
      "resolved": "https://registry.npmjs.org/zeromq/-/zeromq-6.1.2.tgz",
      "integrity": "sha512-5lqsW2UXnKhFhBbIm0wzrRnZmWaGI2b2bm4E03rYMK1c1jBMN0wbPnuyqqhGg7QkzBUmpqf+LyjLhg2TRJmvow==",
      "hasInstallScript": true,
      "license": "MIT AND MPL-2.0",
      "dependencies": {
        "@aminya/cmake-ts": "^0.3.0-aminya.7",
        "node-addon-api": "^8.2.1"
      },
      "engines": {
        "node": ">= 10",
        "pnpm": ">= 9"
      }
    }
```

After this, the Dealer code above would not work. After investigating, I found the documentation for enabling curve via `.npmrc`.  I then removed the zeromq folder from `node_modules` then ran `npm install` again, but the above code still wouldn't run (I get the error: _Cannot add property curveServer, object is not extensible_).

Tried a few things, for instance I edited `node_modules/zeromq/CMakeLists.txt` and changed the following:

```diff
- set_option_from_env(ZMQ_CURVE)
+ set("ZMQ_CURVE" ON)
```
Then I ran:

```
npm explore zeromq --prefix "$(pwd)" -- npm run install --verbose
```

However, my code still failed with the same error.

Not sure if the above information helps, I hope it will, but admittedly I'm not that familiar with CMake so I'm not even sure if what I did was right.

**Comment by ctataryn** [comment]
Update:

By adding the following line to `node_modules/zeromq/CMakeLists.txt`:

```
set(VCPKG_MANIFEST_FEATURES, "${VCPKG_MANIFEST_FEATURES}" CACHE STRING "Features to enable for vcpkg manifest mode")
```

I was able to confirm that the curve feature was now included in  `./node_modules/zeromq/staging/linux/x64/node/127/CMakeCache.txt`:

```
//Features to enable for vcpkg manifest mode
VCPKG_MANIFEST_FEATURES,:STRING=curve
```

This is only after I force `ZMQ_CURVE` to `ON` as mentioned in my previous comment though...

However, my Dealer instantiation still errors out with `Cannot add property curveServer, object is not extensible`

Full install log file attached.
[zeromq-curve-install.log](https://github.com/user-attachments/files/18082674/zeromq-curve-install.log)

**Comment by ctataryn** [comment]
@aminya I sponsored and I'm hoping you have some time to take a 👀

**Comment by aminya** [comment]
> @aminya I sponsored and I'm hoping you have some time to take a 👀 

Thanks very much! I'll have a look soon.

**Comment by ctataryn** [comment]
@aminya 👋 Just wanted to check if you've had time to look at this, if not would you be able to advise an approximate time to check back in?

**Comment by aminya** [comment]
@ctataryn I've been very busy this week, but I'll work on Curve this weekend! Thanks for waiting.

**Comment by ctataryn** [comment]
@aminya Thanks for the update, I appreciate it!

**Comment by aminya** [comment]
libzmq no longer provides curve support without enabling libsodium. This was introduced in 4.3.5.
[v4.3.4](https://github.com/zeromq/libzmq/blob/4097855ddaaa65ed7b5e8cb86d143842a594eebd/CMakeLists.txt#L281) vs [v4.3.5](https://github.com/zeromq/libzmq/blob/622fc6dde99ee172ebaa9c8628d85a7a1995a21d/CMakeLists.txt#L282)

So, in #682, I have updated the readme to reflect that accordingly. You have to enable both in the `.npmrc`.

```ini
zmq_curve="true"
zmq_sodium="true"
```

You can try to build this locally, while I make #682 working for all platforms.

**Comment by ctataryn** [comment]
Thank you @aminya, I will give this a try and report back. I really appreciate your help 🙏

**Comment by aminya** [comment]
v6.2.0 was released and it includes secure Curve support with Libsodium by default

**Comment by ctataryn** [comment]
@aminya confirmed, adding the following to `.npmrc` worked like a charm with `v6.2.0`.

```
zmq_curve="true"
zmq_sodium="true"
```

**Question**: would it make sense to only have to specify `zmq_curve="true"` and have it auto-add the sodium flag since it is a required dependcy?

**Comment by aminya** [comment]
For 6.2.0 you don't need to specify any options. It works out of the box! That was before I provided the prebuilds for the common platforms.

**Comment by ctataryn** [comment]
Ohh, nice! Ok. So really you'd only need those options if you were to enable `build_from_source=true`?

**Comment by aminya** [comment]
Yes, now that Curve is enabled by default you don't need to build from the source. I'll enable the draft API for the next release as well.
