### ISSUE TITLE
Double free memory bug in binding.cc

### ISSUE THREAD

**Issue by sminux** [zeromq/zeromq.js#642]
One of my static analyzer shows this warning:
Pointer 'this->bufref_' is passed to a function free at binding.cc:
https://github.com/zeromq/zeromq.js/blob/17a1a3d7089b45c7b4ff24bd0e64bd78217692e6/binding.cc#L1033
by calling function 'operator delete' after the referenced memory was deallocated at binding.cc:
https://github.com/zeromq/zeromq.js/blob/17a1a3d7089b45c7b4ff24bd0e64bd78217692e6/binding.cc#L1054 
by passing as 1st parameter to function 'zmq::Socket::OutgoingMessage::BufferReference::BufferReference' at binding.cc:
https://github.com/zeromq/zeromq.js/blob/17a1a3d7089b45c7b4ff24bd0e64bd78217692e6/binding.cc#L1030

Do we need to check bufref_ before delete? It can cause undefined behaviour

- OS: Debian 10/11
- ZeroMQ.js version: 5.3.1

**Comment by aminya** [comment]
v6 was released. Please try again with the latest version, and report back if the issue still persists.
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0
