### ISSUE TITLE
Guide for NodeJS at https://zeromq.org/languages/nodejs not updated for v6.0.0

### ISSUE THREAD

**Issue by theonlyklas** [zeromq/zeromq.js#645]
**Describe the bug** A clear and concise description of what the bug is.

Guide for NodeJS at https://zeromq.org/languages/nodejs not updated for v6.0.0

**Reproducing** If possible, provide a list of commands or a code sample that
reproduces the bug that you are observing. Otherwise please describe as much as
possible in which circumstances the bug can be observed.

Visit https://zeromq.org/languages/nodejs and view the page

**Expected behavior** A clear and concise description of what you expected to
happen.

Guide for NodeJS at https://zeromq.org/languages/nodejs is updated for v6.0.0 with a migration guide for going from v5.x.y to v6.0.0

**Tested on**

- OS: Windows 10
- ZeroMQ.js version: 6.0.0

**Comment by irdkwmnsb** [comment]
Is there a migration guide for transitioning to v6?
