### ISSUE TITLE
npm install zeromq hangs

### ISSUE THREAD

**Issue by pwcushman** [zeromq/zeromq.js#647]
**Describe the bug** A clear and concise description of what the bug is.
trying to use the 6.0.0 (latest) version of zeromq.  Running "npm install zeromq" hangs

**Reproducing** If possible, provide a list of commands or a code sample that
reproduces the bug that you are observing. Otherwise please describe as much as
possible in which circumstances the bug can be observed.

**Expected behavior** A clear and concise description of what you expected to
happen.

**Tested on**
Tested on Ubuntu 20.04, Mac 

Zeromq version 6.0.0

**Comment by pwcushman** [comment]
output from ubuntu:
ubuntu@ip-172-31-27-136:~/test$ npm install zeromq
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
(##################) ⠴ reify:zeromq: http fetch GET 200 https://registry.npmjs.org/zeromq/-/zeromq-6.0.0.tgz 968ms (cache miss)

**Comment by pwcushman** [comment]
attach log file from mac
[2024-08-22T20_50_15_484Z-debug-0.log](https://github.com/user-attachments/files/16719077/2024-08-22T20_50_15_484Z-debug-0.log)

**Comment by aminya** [comment]
Duplicate of #646

**Comment by aminya** [comment]
Please try `6.0.1` and see if you still see the issue.

**Comment by pwcushman** [comment]
I get this error:

bash-3.2$ npm install ***@***.***

npm warn deprecated ***@***.***: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

npm warn deprecated ***@***.***: Glob versions prior to v9 are no longer supported

npm error code 127

npm error path /Users/paulcus/temp/node_modules/zeromq

npm error command failed

npm error command sh -c (npm run build.js || echo ok) && cross-env npm_config_build_from_source=true aminya-node-gyp-build

npm error > ***@***.*** build.js

npm error > run-p build.script build.library

npm error

npm error ok

npm error sh: run-p: command not found

npm error sh: cross-env: command not found

npm error A complete log of this run can be found in: /Users/paulcus/.npm/_logs/2024-08-23T00_34_06_988Z-debug-0.log

bash-3.2$


From: Amin Yahyaabadi ***@***.***>
Reply-To: "zeromq/zeromq.js" ***@***.***>
Date: Thursday, August 22, 2024 at 6:52 PM
To: "zeromq/zeromq.js" ***@***.***>
Cc: "Cushman, Paul" ***@***.***>, Author ***@***.***>
Subject: Re: [zeromq/zeromq.js] npm install zeromq hangs (Issue #647)


Please try 6.0.1 and see if you still see the issue.

**Comment by pwcushman** [comment]
I see a version 6.0.2 is up.  Looks like that may be installing successfully.  Will have to try it out more.

From: Amin Yahyaabadi ***@***.***>
Reply-To: "zeromq/zeromq.js" ***@***.***>
Date: Thursday, August 22, 2024 at 6:52 PM
To: "zeromq/zeromq.js" ***@***.***>
Cc: "Cushman, Paul" ***@***.***>, Author ***@***.***>
Subject: Re: [zeromq/zeromq.js] npm install zeromq hangs (Issue #647)


Please try 6.0.1 and see if you still see the issue.

**Comment by pwcushman** [comment]
There may still be issues.  I have a package that uses another package that uses the ***@***.******@***.***> and when I run the following I see errrors:

***@***.*** wickrio-bot-api % npm audit fix



> ***@***.*** install /Users/paulcus/Development/wickrio-bot-api/node_modules/zeromq

> (npm run build.js || echo __skipping_js_build__) && cross-env npm_config_build_from_source=true aminya-node-gyp-build





> ***@***.*** build.js /Users/paulcus/Development/wickrio-bot-api/node_modules/zeromq

> run-p build.script build.library



sh: run-p: command not found

npm ERR! code ELIFECYCLE

npm ERR! syscall spawn

npm ERR! file sh

npm ERR! errno ENOENT

npm ERR! ***@***.*** build.js: `run-p build.script build.library`

npm ERR! spawn ENOENT

npm ERR!

npm ERR! Failed at the ***@***.*** build.js script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/paulcus/.npm/_logs/2024-08-23T15_55_07_137Z-debug.log

__skipping_js_build__

added 6 packages from 5 contributors and updated 2 packages in 4.491s



118 packages are looking for funding

  run `npm fund` for details



fixed 0 of 9 vulnerabilities in 809 scanned packages

  6 vulnerabilities required manual review and could not be updated

  2 package updates for 3 vulnerabilities involved breaking changes

  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)


From: Amin Yahyaabadi ***@***.***>
Reply-To: "zeromq/zeromq.js" ***@***.***>
Date: Thursday, August 22, 2024 at 6:52 PM
To: "zeromq/zeromq.js" ***@***.***>
Cc: "Cushman, Paul" ***@***.***>, Author ***@***.***>
Subject: Re: [zeromq/zeromq.js] npm install zeromq hangs (Issue #647)


Please try 6.0.1 and see if you still see the issue.

**Comment by aminya** [comment]
Please try 6.0.3 and check if you still see the issue.

**Comment by pwcushman** [comment]
It is actually worse now:



***@***.*** wickrio_addon % npm install



> ***@***.*** install /Users/paulcus/Development/wickrio_addon/node_modules/deasync

> node ./build.js



`darwin-x64-node-14` exists; testing

Binary is fine; exiting



> ***@***.*** install /Users/paulcus/Development/wickrio_addon/node_modules/zeromq

> cross-env npm_config_build_from_source=true aminya-node-gyp-build



No native build was found for platform=darwin arch=x64 runtime=node abi=83 uv=1 libc=glibc node=14.19.1

    loaded from: /Users/paulcus/Development/wickrio_addon/node_modules/zeromq



Traceback (most recent call last):

  File "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>

    sys.exit(gyp.script_main())

             ^^^^^^^^^^^^^^^^^

  File "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main

    return main(sys.argv[1:])

           ^^^^^^^^^^^^^^^^^^

  File "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main

    return gyp_main(args)

           ^^^^^^^^^^^^^^

  File "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 520, in gyp_main

    [generator, flat_list, targets, data] = Load(

                                            ^^^^^

  File "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 136, in Load

    result = gyp.input.Load(build_files, default_variables, includes[:],

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2782, in Load

    LoadTargetBuildFile(build_file, data, aux_data,

  File "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 391, in LoadTargetBuildFile

    build_file_data = LoadOneBuildFile(build_file_path, data, aux_data,

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 234, in LoadOneBuildFile

    build_file_contents = open(build_file_path, 'rU').read()

                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: invalid mode: 'rU' while trying to load binding.gyp

gyp ERR! configure error

gyp ERR! stack Error: `gyp` failed with exit code: 1

gyp ERR! stack     at ChildProcess.onCpExit (/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)

gyp ERR! stack     at ChildProcess.emit (events.js:400:28)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)

gyp ERR! System Darwin 23.6.0

gyp ERR! command "/Users/paulcus/.nvm/versions/node/v14.19.1/bin/node" "/Users/paulcus/.nvm/versions/node/v14.19.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /Users/paulcus/Development/wickrio_addon/node_modules/zeromq

gyp ERR! node -v v14.19.1

gyp ERR! node-gyp -v v5.1.0

gyp ERR! not ok

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! ***@***.*** install: `cross-env npm_config_build_from_source=true aminya-node-gyp-build`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the ***@***.*** install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.



npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/paulcus/.npm/_logs/2024-08-24T01_33_24_141Z-debug.log

***@***.*** wickrio_addon %


From: Amin Yahyaabadi ***@***.***>
Reply-To: "zeromq/zeromq.js" ***@***.***>
Date: Friday, August 23, 2024 at 4:14 PM
To: "zeromq/zeromq.js" ***@***.***>
Cc: "Cushman, Paul" ***@***.***>, Author ***@***.***>
Subject: Re: [zeromq/zeromq.js] npm install zeromq hangs (Issue #647)


Please try 6.0.3 and check if you still see the issue.

**Comment by aminya** [comment]
Published `v6.0.4`. It should fix the issue for you!

**Comment by pwcushman** [comment]
Disregard my last response.  My terminal was using Node 14.  Using Node 18 it works.
I will have to try on Node 20 later.

Thanks
Paul

From: Amin Yahyaabadi ***@***.***>
Reply-To: "zeromq/zeromq.js" ***@***.***>
Date: Friday, August 23, 2024 at 10:02 PM
To: "zeromq/zeromq.js" ***@***.***>
Cc: "Cushman, Paul" ***@***.***>, Author ***@***.***>
Subject: Re: [zeromq/zeromq.js] npm install zeromq hangs (Issue #647)


Published v6.0.4. It should fix the issue for you!
