### ISSUE TITLE
Name change to zeromq

### ISSUE THREAD

**Issue by rgbkrk** [zeromq/zeromq.js#65]
[TJ Holowaychuk was kind enough to give us the name `zeromq` on npm](https://twitter.com/tjholowaychuk/status/787406916221743104). Since we both have prebuilds and can do fallbacks/building from source cleanly across the three major operating systems, it's time for a name change that reflects our ability to provide ØMQ in general.

Let's figure out our next steps. *(edited by @lgeiger)*

* [x] Transfer ownership of this repository to the [ØMQ project](https://github.com/zeromq/)
* [x] Rename the repo to `zeromq.js` or `node-zeromq`
* [x] Update the package details in `package.json` and README
* [x] Activate Travis and AppVeyor
* [x] Check if the webhooks still work
* [x] Figure out what to do with the [docs on gh-pages](https://nteract.io/zmq-prebuilt/)
* [ ] Provide more detail in the intro of our README about how you can still build from source (for node, [for Atom](https://github.com/nteract/hydrogen/pull/476), and  [for electron](https://github.com/nteract/nteract/pull/940))
* [x] Choose a version number for release of `zeromq` (maybe`v3.0.0`?)
* [x] Publish `zeromq` to npm
* [x] [Deprecate](https://docs.npmjs.com/cli/deprecate) the `zmq-prebuilt` npm package

**Comment by lgeiger** [comment]
Big 👍 from me.

We may also have to update github token on Travis when we change the repository name.

**Comment by lgeiger** [comment]
[Luca Boccassi and Doron Somech](http://lists.zeromq.org/pipermail/zeromq-dev/2016-October/031031.html) where kind enough to give us access to the [ØMQ organization](https://github.com/zeromq/).
Now we can maintain `zmq-prebuilt` within the zeromq community as the *official* node binding.

I updated the todo list.

**Comment by bluca** [comment]
Thanks for working on this guys!

Under the repo settings https://github.com/nteract/zmq-prebuilt/settings there's a "Transfer ownership" at the bottom, now that you have permissions on the zeromq org you should be able to select it and do the move. This will move the whole thing including settings, issues and PRs (and their history) which is nice, which is probably what you want. Of course you can also choose to fork it instead and keep this here, it's up to you.

You should also have automatically rights to enable travis and appveyor, we already use them in a few repositories. The token might have to be updated.

Let us know if you have any issues!

**Comment by lgeiger** [comment]
@bluca Thanks a lot for your help! I'm going to tackle this now 🚀

**Comment by bluca** [comment]
Everything seems to have worked!

For Appveyor I enabled this repo.

As I wrote on the email if you log out and log back in through Github you should be able to pick the organization account and do any changes you need.

**Comment by lgeiger** [comment]
Awesome AppVeyor works. I just don't have access to it 👍

**Comment by bluca** [comment]
@sappo - I think the Appveyor account for the org was authorized through your user:

```AppVeyor was authorized a year ago for admin:repo_hook,read:org,repo:status access to GitHub repositories as sappo account.```

I can't see anywhere on the Appveyor page how to allow other admins access, any idea?

**Comment by lgeiger** [comment]
@bluca Thanks a lot for adding me. It works excellent now 👍

**Comment by sappo** [comment]
@bluca great, for future reference how did you achieve it?

**Comment by lgeiger** [comment]
At https://ci.appveyor.com/team you can add new team members.

**Comment by lgeiger** [comment]
What do you think should we release `zeromq` v3.0.0 now?

**Comment by rgbkrk** [comment]
Yeah I think we can make the 3.0.0 release.

**Comment by lgeiger** [comment]
zeromq v3.0.0 has been published to https://www.npmjs.com/package/zeromq

Thanks for the support and encouragement we're really happy to be part of the zeromq community.
