### ISSUE TITLE
Cannot find module 'zeromq' or its corresponding type declarations

### ISSUE THREAD

**Issue by 6sigmadc** [zeromq/zeromq.js#651]
**Describe the bug**
I upgraded from v6.0.0-beta.20 to v6.0.2 but unfortunately it starts to report error - "Cannot find module 'zeromq' or its corresponding type declarations".
I compared the differences of the folder and files in node_modules folder between v6.0.0-beta.20 and v6.0.2, discovered that the folder lib/ts3.7 is missing from v6.0.2.
As a test, I took a copy of the ts3.7 folder from v6.0.0-beta.20, upgrade to v6.0.2, and pasted the ts3.7 folder manually in the right place - that fixed the issue.

**Reproducing**
Upgrade from v6.0.0-beta.20 to v6.0.2

**Expected behavior**
typescript compiler should run correctly

**Tested on**
- OS: Windows 11
- ZeroMQ.js version: 6.0.2
- Typescript: 5.4.5

**Comment by aminya** [comment]
Please try 6.0.3 and check if you still see the issue.

**Comment by 6sigmadc** [comment]
It works perfectly now in v6.0.4 - thanks for the prompt response.

On a different note, and for what it's worth, appreciate your work in zeromq and it is making a difference to the world for the better.
