### ISSUE TITLE
win10 install error

### ISSUE THREAD

**Issue by muscleman** [zeromq/zeromq.js#658]
On win10, npm install zeromq-6.0.0-beta-20 installs fine.

anything above this version throws a error

`C:\windows\system32\cmd.exe /d /s /c (npm runb build.js || echo ok) && cross-env npm_config_build_from_source=true aminya-node-gyp-build

windows 11, mac and ubuntu builds are fine.

**Comment by muscleman** [comment]
actually i have to remove zeromq from package.json, install dependencies then run

npm i zeromq-6.0.0-beta-20 --build-from-source

**Comment by ArqTras** [comment]
1599 error command C:\Windows\system32\cmd.exe /d /s /c (npm run build.js || echo ok) && aminya-node-gyp-build --build-from-source
1600 error > zeromq@6.0.0 build.js
1600 error > run-p build.script build.library
1600 error
1600 error ok
1601 error 'run-p' is not recognized as an internal or external command,
1601 error operable program or batch file.
1601 error ^C
1602 silly unfinished npm timer reify 1727869347590
1603 silly unfinished npm timer idealTree:node_modules/caniuse-api/node_modules/browserslist 1727869357724
1604 silly unfinished npm timer reify:build 1727869401422
1605 silly unfinished npm timer build 1727869401425
1606 silly unfinished npm timer build:deps 1727869401426
1607 silly unfinished npm timer build:run:install 1727869402402
1608 silly unfinished npm timer build:run:install:node_modules/zeromq 1727869402402
1609 verbose cwd C:\Github\xeq-wallet
1610 verbose os Windows_NT 10.0.19045
1611 verbose node v20.17.0
1612 verbose npm  v10.8.3
1613 verbose exit 3221225786
1614 verbose code 3221225786

**Comment by aminya** [comment]
> On win10, npm install zeromq-6.0.0-beta-20 installs fine.
> 
> anything above this version throws a error
> 
> `C:\windows\system32\cmd.exe /d /s /c (npm runb build.js || echo ok) && cross-env npm_config_build_from_source=true aminya-node-gyp-build
> 
> windows 11, mac and ubuntu builds are fine.

What's the error you're getting?

> 1600 error > zeromq@6.0.0 build.js

You should install 6.0.4

**Comment by ArqTras** [comment]
same issue, when we build our project with 6.0.4 it works just fine on mac osx 15 ubuntu 22.04 and windows 11 , however even compilation success on win 10 pro its not portable anymore.
So build on win 10 works on build machine, and on win 11 but not work on any other win 10.
We did test versions from 6.0 .0 up to 6.0.4

**Comment by aminya** [comment]
https://github.com/zeromq/zeromq.js/releases/tag/v6.0.6

**Comment by aminya** [comment]
As mentioned in the readme now, Zeromq binaries on Windows 10 or older need [Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version) to be installed.
