### ISSUE TITLE
Proxy not working from version v6.0.0-beta.20 to v6.0.8

### ISSUE THREAD

**Issue by dhilip89** [zeromq/zeromq.js#662]
**Describe the bug** 
Proxy is throwing different error on different environment with the version (from v6.0.0-beta.20 to v6.0.8), it was working fine in v6.0.0-beta.19.

**On Windows machine:**
> Waiting for the debugger to disconnect...
> node:internal/process/promises:289
>             triggerUncaughtException(err, true /* fromPromise */);
>             ^
> 
> [Error: Unknown error] { errno: 10045, code: '' }

**On Ubuntu machine:**
> Debugger attached.
> Waiting for the debugger to disconnect...
> node:internal/process/promises:391
>     triggerUncaughtException(err, true /* fromPromise */);
>     ^
> 
> [Error: Operation not supported] { errno: 95, code: 'ENOTSUP' }

**Reproducing** 
Using example from the [official documentation](https://zeromq.github.io/zeromq.js/classes/Proxy.html):
```js
import { Proxy, Router, Dealer } from "zeromq"

// Proxy between a router/dealer socket for 5 seconds.
const proxy = new Proxy(new Router, new Dealer)
await proxy.frontEnd.bind("tcp://*:3001")
await proxy.backEnd.bind("tcp://*:3002")
setTimeout(() => proxy.terminate(), 5000)
await proxy.run() // <-- This line throws unknown error on Windows, ENOTSUP on Linux
```
Downgrade zeromq.js to [v6.0.0-beta.19](https://github.com/zeromq/zeromq.js/releases/tag/v6.0.0-beta.19) then the code will not throw error.

**Expected behavior** 
Proxy should be working correctly without throwing error like with previous version.

**Tested on**

- OS: Windows Server 2022, Ubuntu 24.10
- ZeroMQ.js versions: 6.0.0-beta.19, 6.0.0-beta.20, 6.0.0 - 6.0.8
- Node,js version: 20.11.1, 20.16.0

**Comment by aminya** [comment]
@dhilip89 Could you confirm that the latest release fixed this?

**Comment by dhilip89** [comment]
> @dhilip89 Could you confirm that the latest release fixed this or not?

Just upgraded to latest version (6.1.1), everything seems working as expected on both Windows and Linux machines.

**Comment by aminya** [comment]
Awesome! Thanks for confirming
