### ISSUE TITLE
zlib dependency breaks the npm install

### ISSUE THREAD

**Issue by anttud** [zeromq/zeromq.js#667]
Hope I am not missing something.

**Describe the bug**
Running npm install zeromq leads to npm error
Same error occures when running npm install zlib
zlib is deprecated and should not be used
I am guessing the error is coming from here?https://github.com/zeromq/zeromq.js/blob/b28a42b0be543e6eb17843a5cdda8a07ef192707/pnpm-lock.yaml#L4228

```
npm error code 127
npm error path .../node_modules/zlib
npm error command failed
npm error command sh -c node-waf clean || true; node-waf configure build
npm error sh: 1: node-waf: not found
```

**Reproducing** 
Run npm install zeromq

**Tested on**
- OS: [Ubuntu 20.04, POPOS 22.04]
- ZeroMQ.js version: [6.1.0]

Also tested with docker running alpine container
Tested with and without .npmrc **build_from_source=true**

**Comment by aminya** [comment]
It's weird. The error doesn't happen with pnpm. Anyways, I have forked cmake-ts to resolve the issues. See #669
