### ISSUE TITLE
Failed to load zeromq.js addon.node: ReferenceError: __dirname is not defined

### ISSUE THREAD

**Issue by yuqianliuli** [zeromq/zeromq.js#675]
**Describe the bug** Failed to load zeromq.js addon.node: ReferenceError: __dirname is not defined

**Reproducing** I create a vue project and use  typescript. It is a pure project created by the command` npm create vue@latest` and then I install the zeromq amd use it like this:
code :
```
<script setup lang="ts">
import TheWelcome from '../components/TheWelcome.vue'
import * as zmq from 'zeromq'
import { onMounted, watch, ref, reactive, onUnmounted } from 'vue'
onMounted(() => {
  async () => {
   let socket = new zmq.Subscriber()
    socket.connect('tcp://127.0.0.1:5556')
    socket.subscribe('datarecv')
    console.log('Subscriber connected to port 5556')
    for await (const [topic, msg] of socket) {
      console.log('received a message related to:', topic, 'containing message:', msg)
    }
  }
})
```
when  I open the browser ，this comes out:
Failed to load zeromq.js addon.node: ReferenceError: __dirname is not defined
![image](https://github.com/user-attachments/assets/fd91d363-c0b3-4609-960a-7cd670107e74)

**Tested on**

- OS: [Windows 10]

**Comment by aminya** [comment]
You can't run zeromq inside the browser. It is designed to be used with Nodejs.

**Comment by yuqianliuli** [comment]
Thank you .BTW ,Can you tell me how can I use the zeromq in a electron-vue project ? I've been troubled for several days
