### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by lgeiger** [zeromq/zeromq.js#79]
We should provide more detail in the intro of our README about how you can still build from source for:
- node
- [Electron](https://github.com/nteract/nteract/pull/940)
- [Atom](https://github.com/nteract/hydrogen/pull/476) and

**Comment by aj-ptw** [comment]
Would love this for Electron! Struggling to get this working :/ can't even use the prebuilt one for some reason! Running node 7 and using electron 1.4.5 and am getting this weird error: 
```
$ npm install zmq-prebuilt
npm WARN deprecated zmq-prebuilt@2.1.0: zmq-prebuilt has been renamed to zeromq. For more information visit https://github.com/zeromq/zeromq.js
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g

> zmq-prebuilt@2.1.0 install /Users/andrewkeller/Downloads/thinker-newish/app/node_modules/zmq-prebuilt

> prebuild --install

prebuild WARN install No prebuilt binaries found (target=v7.0.0 arch=x64 platform=darwin)
```

```
$ node -v
v7.0.0
```

**Comment by rgbkrk** [comment]
For electron, you have to run a rebuild so that the node headers match that of Electron and not your local node.

```
npm rebuild zeromq --runtime=electron --target=1.4.3 --disturl=https://atom.io/download/atom-shell --build-from-source
```

Note: replace the target number with the version of electron that you're using.

Within [nteract](https://github.com/nteract/nteract) we use `electron-rebuild` to handle this directly for us (no longer having to do the rebuild manually or as part of a postinstall).

**Comment by aj-ptw** [comment]
Hey @rgbkrk thanks for the reply. Are you using `zeromq` or `zmq-prebuilt`?

**Comment by rgbkrk** [comment]
We're now using zeromq thought we were using zmq-prebuilt before (which was what got renamed into zeromq.js).

Thats interesting that it says that it won't pack it in the archive and yet it tries to resolve it within the archive. Whats your electron version?

**Comment by lgeiger** [comment]
> `prebuild WARN install No prebuilt binaries found (target=v7.0.0 arch=x64 platform=darwin)`

You get this error because `zmq-prebuilt` doesn't ship prebuilt binaries for Node 7. Please use `zeromq` instead.
I think the default behavior of `prebuild` should be to build from source instead of throwing a exception. We should open a issue on `prebuild` for that.

> `node_modules/zmq-prebuilt is not packed into asar archive - contains executable code`

You can ignore this warning. It was removed in [`electron-builder` 7.23.0](https://github.com/electron-userland/electron-builder/releases/tag/v7.23.0).

Please use `zeromq`.  Also with `electron-builder` you don't need to rebuild manually.
I suppose this error is caused by `zmq-prebuilt` not installing on Node 7.

**Comment by lgeiger** [comment]
@aj-ptw We updated our installation instructions: #91
